### PR TITLE
Fix multiple issues with minirepro and gpsd

### LINKED ISSUE #10435: minirepro doesn't work on master
### Greenplum version or build
master (7 alpha, commit 9a574915df534 as of writing)

### Step to reproduce the behavior
1. Create a database `pivotal`

1. Run the follow SQL in the database through `psql`:

    ```sql
    CREATE TABLE foo(a) AS SELECT generate_series(1, 12) DISTRIBUTED BY (a);
    ```

1. Put the following trivial query into `q.sql`

    ```sql
    SELECT a FROM foo;
    ````

1. `minirepro pivotal -q q.sql -f minirepro.sql`

### Expected behavior

minirepro is able to generate a minimal schema and statistics dump, and restoring said dump back to an empty database should work.

### Actual behavior

```
Connecting to database: host=814e18cdb000, port=7000, user=gpadmin, db=pivotal ...
Traceback (most recent call last):
  File "/build/install/bin/minirepro", line 423, in <module>
    main()
  File "/build/install/bin/minirepro", line 335, in main
    conn = pgdb.connect(connectionString)
  File "/build/install/lib/python/pgdb.py", line 1690, in connect
    cnx = _connect(dbname, dbhost, dbport, dbopt, dbuser, dbpasswd)
pg.InternalError: FATAL:  no pg_hba.conf entry for host "172.17.0.3", user "pivotal", database "7000"

```

This seems to be a PyGreSQL-related breakage. But even after I bandaided over that, the generated SQL is still broken, as evidenced by trying to run the generated minirepro...

### PR DESCRIPTION
**Pull request by soumyadeep2007**
Catalog table pg_statistic was updated in the PG12 merge. Issue is that
scripts minirepro and gpsd have hardcoded expectations for the
pg_statistic schema.

After commit f5758021be34 pygresql automatically converts postgres array
literals into python lists, which threw off the existing array
formatting logic for the insert statement (whenever a pg_statistic
tuple had a non-empty array in one of its slots). So we introduced the
format_array_literal() for formatting array literals for the insert
statement output.

There are subtle differences between the dump stats function in
minirepro and gpsd with respect to formatting the insert statement. We
took the opportunity to extract the common formatting logic into a
shared gppylib function. We also simplified the formatting logic.

Also introduced tests for gpsd and minirepro to guard against catalog
changes without accompanying minirepro/gpsd changes.

This closes #10435 and #10941

Co-authored-by: David Kimura <dkimura@pivotal.io>

### CODE REVIEW

File: src/test/regress/init_file [hunk 1]
```diff
@@ -124,4 +124,8 @@ s/nodename nor servname provided, or not known/Name or service not known/
 m/ERROR:  could not devise a query plan for the given query \(.*\)/
 s/ERROR:  could not devise a query plan for the given query \(.*\)/ERROR:  could not devise a query plan for the given query/
 
+# psql 9 changes now shows username on connection. Ignore the added username.
```
Comment (ashwinstar) [inline src/test/regress/init_file:127]: If this applicable for only couple of tests better to define it in those specific tests instead of having in global file. Helps to avoid applying the rule to non-relevant tests and saves time while running tests.

File: src/test/regress/sql/gpsd.sql [hunk 2]
```diff
@@ -0,0 +1,126 @@
+-- Ensure that our expectation of pg_statistic's schema is up-to-date
+\d+ pg_statistic
+
+--------------------------------------------------------------------------------
+-- Scenario: Table without hll flag
+--------------------------------------------------------------------------------
+
+drop database if exists gpsd_db;
```
Comment (ashwinstar) [inline src/test/regress/sql/gpsd.sql:8]: Not required if we are dropping the database at end of the tests.

File: src/test/regress/sql/gpsd.sql [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+create table gpsd_foo(a int, s text) partition by range(a);
+create table gpsd_foo_1 partition of gpsd_foo for values from (1) to (5);
+insert into gpsd_foo values(1, 'something');
+analyze gpsd_foo;
+
+set allow_system_table_mods to on;
+update pg_statistic set stavalues3='{"hello", "''world''"}'::text[] where starelid='gpsd_foo'::regclass and staattnum=2;
+
+-- start_ignore
+\! gpsd gpsd_db > /tmp/gpsd-without-hll.sql
```
Comment (ashwinstar) [inline src/test/regress/sql/gpsd.sql:21]: Maybe we should write this tests in isolation2 where at least check the exit code for commands

Instead of `/tmp` would prefer to write the file in `data` sub-directory under regress/isolation2 directories and add it to `.gitignore`

**Review by ashwinstar — COMMENTED** [review]
Thank You for adding tests.

As discussed offline do we wish to turn orca off for minirepor and gpsd (to speed them up)? Maybe can add it as separate commit in this PR.

File: src/test/regress/sql/gpsd.sql (hunk 3 above)
Comment (dgkimura) [reply src/test/regress/sql/gpsd.sql:21]: We gave this a quick try, however currently seems isolation2 does not support psql commands such as `\d+ table` or `gset`.  We want to use these in tests we are adding for work on for extended statistics as well.

We will change to write the temp file in data sub-directory of regress.

File: src/test/regress/sql/gpsd.sql (hunk 2 above)
Comment (dgkimura) [reply src/test/regress/sql/gpsd.sql:8]: We're thinking to keep the database around after the test to improve debugging.  That way we'll have artifacts in event of flaky test. We'll create separate databases for with_hll and without_hll to do this.

File: src/test/regress/sql/gpsd.sql (hunk 3 above)
Comment (ashwinstar) [reply src/test/regress/sql/gpsd.sql]: Sure, sounds good! Thanks for update.

File: src/test/regress/sql/gpsd.sql [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+create database gpsd_db_without_hll;
+\c gpsd_db_without_hll
+
+create table gpsd_foo(a int, s text) partition by range(a);
+create table gpsd_foo_1 partition of gpsd_foo for values from (1) to (5);
+insert into gpsd_foo values(1, 'something');
+analyze gpsd_foo;
+
+set allow_system_table_mods to on;
+update pg_statistic set stavalues3='{"hello", "''world''"}'::text[] where starelid='gpsd_foo'::regclass and staattnum=2;
```
Comment (d) [inline src/test/regress/sql/gpsd.sql:26]: Do I see an implicit assumption about `stakind3` being a particular kind?

Comment (soumyadeep2007) [reply src/test/regress/sql/gpsd.sql:26]: Ah, we are setting `stavalues3` without regard to `stakind3` (which is 0 for the column corresponding to the pg_statistic row), in order to test if gpsd can dump stats that have text values with quotes.

I'll add a comment to make that clearer.

File: gpMgmt/bin/gppylib/utils.py [hunk 5]
```diff
@@ -501,3 +502,93 @@ def escapeDoubleQuoteInSQLString(string, forceDoubleQuote=True):
     if forceDoubleQuote:
         string = '"' + string + '"'
     return string
+
+
+def E(query_str):
```
Comment (chrishajas) [inline gpMgmt/bin/gppylib/utils.py:507]: We also have dbconn if we want to put all pgdb functions within that file. Can we also rename this function to something more descriptive.

File: src/test/regress/sql/gpsd.sql [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+
+-- start_ignore
+\! gpsd gpsd_db_without_hll > data/gpsd-without-hll.sql
+-- end_ignore
+
+\c regression
+drop database gpsd_db_without_hll;
```
Comment (chrishajas) [inline src/test/regress/sql/gpsd.sql:33]: Is there any value in keeping these around after the test?. If it's only used in one regress test, it should be simple to repro.

**Review by chrishajas — APPROVED** [review]
Looks good! Thanks for adding tests too!

File: src/test/regress/sql/gpsd.sql (hunk 6 above)
Comment (soumyadeep2007) [reply src/test/regress/sql/gpsd.sql:33]: What David said [here](https://github.com/greenplum-db/gpdb/pull/11279#discussion_r545478312)

File: gpMgmt/bin/gppylib/utils.py (hunk 5 above)
Comment (soumyadeep2007) [reply gpMgmt/bin/gppylib/utils.py]: Renamed. I would rather keep it where it is as the dbconn file currently deals with more higher level connection stuff.
