### PR TITLE
Fix memory leak in ao_truncate_replay

### LINKED ISSUE #11202: Memory leak in ao_truncate_replay
### Greenplum version or build

```
PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.14088.g9e45a68ef1 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 6.5.1 20190307 (Alibaba 6.5.1-1 2.17), 64-bit compiled on Nov 23 2020 20:01:14 (with assert checking)
````

### Step to reproduce the behavior

```bash
DATADIRS=~/dbdata NUM_PRIMARY_MIRROR_PAIRS=1 make cluster
createdb aocsoom

# create a table table0 with 1024 columns
psql -d aocsoom -f ddl.sql

# insert table0 created as above. The insert.sql looks like:
# 1: begin;
# 2: begin;
# 1: insert into table0 values(...);
# 2: insert into table0 values(...);
# 1: commit;
# 1q:
# 2: commit;
# 2q:
# After this, table0 will have 127 segments.
python3 sql_isolation_testcase.py --dbname=aocsoom < ~/tmp/aocsoom/insert.sql > ~/tmp/aocsoom/insert.log 2>&1

# do vacuum table0, and now mirror will keep calling ao_truncate_replay()
nohup pgbench -f vacuum.sql -c 1 -l -n -T 3600000 -d aocsoom 1>pgben.log 2>&1 &
```

[ddl.sql.txt](https://github.com/greenplum-db/gpdb/files/5587899/ddl.sql.txt)
[insert.sql.txt](https://github.com/greenplum-db/gpdb/files/5587902/insert.sql.txt)

### Root cause

It seems we should do `pfree(dbPath)` in ao_truncate_replay().

```c
static void
ao_truncate_replay(XLogReaderState *record)
{
        char       *dbPath;
        char            path[MAXPGPATH];
        File            file;

        xl_ao_truncate *xlrec = (xl_ao_truncate*) XLogRecGetData(record);

        dbPath = GetDatabasePath(xlrec->target.node.dbNode,
                                                         xlrec->target.node.spcNode);

        // It seems we should do `pfree(dbPath)` here.
        FileClose(file);
}
```

There is no invocation of `pfree()`, and the `CurrentMemoryContext` is `TopMemoryContext`

```
(gdb) c
Continuing.

Breakpoint 1, ao_truncate_replay (record=0x625000011950) at cdbappendonlyxlog.c:134
134		xl_ao_truncate *xlrec = (xl_ao_truncate*) XLogRecGetData(record);
(gdb) p *CurrentMemoryContext
$1 = {type = T_AllocSetContext, isReset = false, allowInCritSection = false, mem_allocated = 412728, methods = 0x1e0b1e0 <AllocSetMethods>, parent = 0x0, firstchild = 0x62500001e110, prevchild = 0x0, nextchild = 0x0, name = 0x1e10160 "TopMemoryContext", ident = 0x0, reset_cbs = 0x0}
(gdb) b palloc
Breakpoint 2 at 0x178694d: file mcxt.c, line 1141.
(gdb) b pfree
Breakpoint 3 at 0x1787192: file mcxt.c, line 1246.
(gdb) c
Continuing.

Breakpoint 2, palloc (size=128) at mcxt.c:1141
1141		MemoryContext context = CurrentMemoryContext;
(gdb) c
Continuing.

Breakpoint 1, ao_truncate_replay (record=0x625000011950) at cdbappendonlyxlog.c:134
134		xl_ao_truncate *xlrec = (xl_ao_truncate*) XLogRecGetData(record);
(gdb) c
Continuing.

Breakpoint 2, palloc (size=128) at mcxt.c:1141
1141		MemoryContext context = CurrentMemoryContext;
(gdb) c
Continuing.

Breakpoint 1, ao_truncate_replay (record=0x625000011950) at cdbappendonlyxlog.c:134
134		xl_ao_truncate *xlrec = (xl_ao_truncate*) XLogRecGetData(record);
(gdb) c
Continuing.

Breakpoint 2, palloc (size=128) at mcxt.c:1141
1141		MemoryContext context = CurrentMemoryContext;
```

### PR DESCRIPTION
**Pull request by hidva**
The value returned by GetDatabasePath is palloc'd, and
CurrentMemoryContext is TopMemoryContext when we enter
ao_truncate_replay(), so we should do a pfree.

Fix #11202

### CODE REVIEW

File: src/backend/cdb/cdbappendonlyxlog.c [hunk 1]
```diff
@@ -140,6 +140,7 @@ ao_truncate_replay(XLogReaderState *record)
 		snprintf(path, MAXPGPATH, "%s/%u", dbPath, xlrec->target.node.relNode);
 	else
 		snprintf(path, MAXPGPATH, "%s/%u.%u", dbPath, xlrec->target.node.relNode, xlrec->target.segment_filenum);
+	pfree(dbPath);
```
Comment (ashwinstar) [inline src/backend/cdb/cdbappendonlyxlog.c:143]: I would prefer if we add `dbPath=NULL;` after pfree to make sure no code logic tries to use it after free. Will add that and commit.

**Review by ashwinstar — APPROVED** [review]
Thanks for finding the issue and PR. Just curious to learn how did you uncover this to be a problem?

File: src/backend/cdb/cdbappendonlyxlog.c (hunk 1 above)
Comment (hidva) [reply src/backend/cdb/cdbappendonlyxlog.c:143]: done

**Comment by hidva** [comment]
> Thanks for finding the issue and PR. Just curious to learn how did you uncover this to be a problem?

The detailed story is described in [https://blog.hidva.com/2020/11/24/memory-leak-again/](https://blog.hidva.com/2020/11/24/memory-leak-again/) (but written in Chinese). The simple version is that we receive an alert that tells us the used memory of some nodes has been slowly rising in the past 30 days.

**Comment by kainwen** [comment]
Nice job.

Thanks for your contribution. Pushed to master.

**Comment by ashwinstar** [comment]
Backported the commit to 6X_STABLE via fa7444bb87585f8bdb3b3d6839c9962b7ed6f076

**Comment by ashwinstar** [comment]
> > Thanks for finding the issue and PR. Just curious to learn how did you uncover this to be a problem?
> 
> The detailed story is described in [https://blog.hidva.com/2020/11/24/memory-leak/](https://blog.hidva.com/2020/11/24/memory-leak-again/) (but written in Chinese). The simple version is that we receive an alert that tells us the used memory of some nodes has been slowly rising in the past 30 days.

I enjoyed reading your blog on this @hidva (I used google translate to read it in English). Thanks for code and blog contribution.
