### PR TITLE
Use finish_heap_swap to swap relation files and else in ALTER TABLE DISTRIBUTED BY

### LINKED ISSUE #15534: ALTER TABLE SET DISTRIBUTED BY could create inconsistent toast table names
### Greenplum version or build
main branch, HEAD 5de7ba5ce8df1c2f03a10fa9f602abf9933555df

### Expected behavior
A table's toast table should have a name such as `pg_toast_<tableoid>`. The `<tableoid>` should be the OID of the main table, and it shouldn't change during table rewrite, since the main table's OID won't change during table rewrite.

### Actual behavior
`ALTER TABLE DISTRIBUTED BY` would change the name of the toast table. It's probably being changed to have the table OID of the temporary table that's created during a table rewrite.

This inconsistency won't cause immediate impact, but could have a problem when the OID wraps around: we could be creating a table with a table OID same as the temporary table mentioned before, which doesn't exist anymore (since it doesn't exist, we can pick up the same OID). And, if the new table needs a toast table, we would be creating a toast table with the same name as the one that still exists, resulting in errors like : 
```
ERROR:  relation "pg_toast_32794" already exists
```

Found this in some CI flakiness where the exact above scenario happened, around the regress test `oid_wraparound` which manually makes OID wrapped around.

### Step to reproduce the behavior
Let's see three cases:
1. Bad case: `ALTER TABLE SET DISTRIBUTED BY`:
```sql
postgres=# create table t1(a text, b int);
CREATE TABLE
postgres=# alter table t1 set distributed by (b);
ALTER TABLE
postgres=# select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 't1';
  oid  | relname | reltoastrelid |      reltoastrelid
-------+---------+---------------+-------------------------
 16384 | t1      |         16393 | pg_toast.pg_toast_16390
(1 row)
```
The toast table name has 16390 instead of 16384.

2. Good case: `ALTER TABLE SET LOGGED|UNLOGGED`:
```sql
postgres=# create table t2(a text, b int);
CREATE TABLE
postgres=# alter table t2 set logged;
ALTER TABLE
postgres=# alter table t2 set unlogged;
ALTER TABLE
postgres=# select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 't2';
  oid  | relname | reltoastrelid |      reltoastrelid
-------+---------+---------------+-------------------------
 16396 | t2      |         16405 | pg_toast.pg_toast_16396
(1 row)
```
The toast table name is unchanged.

3. Good case: `ALTER TABLE SET ACCESS METHOD`:
```sql
postgres=# create table t3(a text, b int);
CREATE TABLE
postgres=# alter table t3 set access method ao_row;
ALTER TABLE
postgres=# alter table t3 set access method heap;
ALTER TABLE
postgres=# select oid,relname,reltoastrelid,reltoastrelid::regclass from pg_class where relname = 't3';
  oid  | relname | reltoastrelid |      reltoastrelid
-------+---------+---------------+-------------------------
 16408 | t3      |         16427 | pg_toast.pg_toast_16408
(1 row)
```
The toast table name is unchanged.

### PR DESCRIPTION
**Pull request by huansong**
Currently we are doing `swap_relation_files` and a few other steps in ALTER TABLE DISTRIBUTE BY. However, we are missing some necessary steps such as renaming toast tables or clearing missing-attribute related stuff (RelationClearMissing). The `finish_heap_swap()` function which is used by the other ALTER TABLE commands should be used to take care of these general table-rewriting tasks (apart from toast table renaming, also including things like reindex of the old table and deletion of the new table). There should be no reason that ALTER TABLE DISTRIBUTED BY could not use `finish_heap_swap`. It appears that it is just at the time when the related changes of ALTER TABLE DISTRIBUTED BY was introduced, we did not have finish_heap_swap yet (e.g. https://github.com/pivotal/gp-gpdb-historical/commit/5c13332a5bb3).

Fix #15534, which was initially fixed in d38d978e54b1b0375cf1fb29c0726bca4de65a78 but was reverted due to problem in #16650.

P.S. `swap_relation_files` is still directly used by EXPAND TABLE too (`ATExecExpandTableCTAS`) so similar issue might exists there. Will test and address that later.

Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/at-dist-by-toast

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by huansong** [comment]
@gtygo @linxuh  Please take a look if you are interested. Thanks!

File: src/test/regress/sql/alter_distribution_policy.sql [hunk 1]
```diff
@@ -637,3 +637,9 @@ reset gp_force_random_redistribution;
 CREATE TABLE atsdby_multiple(i int, j int);
 ALTER TABLE atsdby_multiple SET DISTRIBUTED BY(j), ADD COLUMN k int;
 ALTER TABLE atsdby_multiple SET WITH (reorganize=true), ADD COLUMN k int;
+
+-- Check that after AT SET DISTRIBUTED BY, the toast table name is still 'pg_toast_<tableoid>'
+create table atsdby_toastname(a text, b int);
+alter table atsdby_toastname set distributed by (b);
+select reltoastrelid::regclass = ('pg_toast.pg_toast_' || oid::text)::regclass
+from pg_class where relname = 'atsdby_toastname';
```
Comment (interma) [inline src/test/regress/sql/alter_distribution_policy.sql:645]: Do we need to add the insert/select statements like the repro case of https://github.com/greenplum-db/gpdb/issues/16650:
`INSERT INTO toastable_heap VALUES(repeat('A',1000000), repeat('B',1000001), 3);`
`select * from toastable_heap;`

**Review by interma — APPROVED** [review]
LGTM, just small questions.

File: src/backend/commands/tablecmds.c [hunk 2]
```diff
@@ -18273,17 +18267,6 @@ ATExecSetDistributedBy(Relation rel, Node *node, AlterTableCmd *cmd)
...
-	/* Step (h) Drop the table */
-	if (need_reorg)
-	{
-		ObjectAddress object;
-		object.classId = RelationRelationId;
-		object.objectId = tmprelid;
-		object.objectSubId = 0;
-
-		performDeletion(&object, DROP_RESTRICT, 0);
-	}
```
Comment (interma) [inline src/backend/commands/tablecmds.c:18285]: I am not very familiar with the related code.
The logic which starts at line 18261 and 18277 are integrated in `finish_heap_swap()`, right?

Comment (huansong) [reply src/backend/commands/tablecmds.c:18285]: Yes, those logic (i.e. reindex of "old table" and deletion of "new table") are part of the general table-rewriting tasks that `finish_heap_swap` handles. I've modified PR desc / commit msg to make it more clear.

File: src/test/regress/sql/alter_distribution_policy.sql (hunk 1 above)
Comment (huansong) [reply src/test/regress/sql/alter_distribution_policy.sql:645]: Actually that won't help as it's for a different issue. And the case has been included in https://github.com/greenplum-db/gpdb/pull/16657 .

Comment (interma) [reply src/test/regress/sql/alter_distribution_policy.sql:645]: Got it, thanks.

File: src/test/regress/sql/alter_distribution_policy.sql [hunk 3]
```diff
@@ -637,3 +637,9 @@ reset gp_force_random_redistribution;
 CREATE TABLE atsdby_multiple(i int, j int);
 ALTER TABLE atsdby_multiple SET DISTRIBUTED BY(j), ADD COLUMN k int;
 ALTER TABLE atsdby_multiple SET WITH (reorganize=true), ADD COLUMN k int;
+
+-- Check that after AT SET DISTRIBUTED BY, the toast table name is still 'pg_toast_<tableoid>'
+create table atsdby_toastname(a text, b int);
```
Comment (soumyadeep2007) [inline src/test/regress/sql/alter_distribution_policy.sql:642]: Let's also add a smoke to ensure that indexes were reindexed (since we are touching that piece a bit + adds coverage for future changes)

File: src/backend/commands/tablecmds.c [hunk 4]
```diff
@@ -18273,17 +18267,6 @@ ATExecSetDistributedBy(Relation rel, Node *node, AlterTableCmd *cmd)
 		cmd->policy = policy;
 	}
 
-	/* Step (h) Drop the table */
```
Comment (soumyadeep2007) [inline src/backend/commands/tablecmds.c:18276]: We need to update the comments about the steps, few lines above to remove step h.

File: src/backend/commands/tablecmds.c [hunk 5]
```diff
@@ -18246,22 +18246,16 @@ ATExecSetDistributedBy(Relation rel, Node *node, AlterTableCmd *cmd)
...
 							false, /* swap_stats */
-							true,
+						 	false, /* check_constraints */
+						 	true, /* is_internal */
 							RecentXmin,
 							ReadNextMultiXactId(),
-							NULL);
-
-		/* Make changes from swapping relation files visible. */
-		CommandCounterIncrement();
```
Comment (soumyadeep2007) [inline src/backend/commands/tablecmds.c:18261]: Okay so this isn't necessary anymore since:
`/* performDeletion does CommandCounterIncrement at end */` inside `finish_heap_swap()`

**Review by soumyadeep2007 — APPROVED** [review]
LGTM! Solid and very welcome change! Minor comments.

File: src/test/regress/sql/alter_distribution_policy.sql (hunk 3 above)
Comment (huansong) [reply src/test/regress/sql/alter_distribution_policy.sql:642]: Sure, added

File: src/backend/commands/tablecmds.c (hunk 4 above)
Comment (huansong) [reply src/backend/commands/tablecmds.c:18276]: Oh yes, good catch!

File: src/backend/commands/tablecmds.c (hunk 5 above)
Comment (huansong) [reply src/backend/commands/tablecmds.c:18261]: I think this was for `reindex_index` but it might be outdated anyway because `reindex_index` does that: https://github.com/greenplum-db/gpdb/blob/76e3f182da0bd041e12d81c78861901a4b39d1f6/src/backend/commands/cluster.c#L1675-L1676

And yes `performDeletion` will perform the final `CommandCounterIncrement`
