### PR TITLE
Reset synchronous_standby_names on FTS mirror promotion.

### LINKED ISSUE #4764: fts handler process get a SIGSEGV when gpstart
### Actual behavior
Backtrace is:
```
#8  ResourceOwnerEnlargeCatCacheRefs (owner=0x0) at resowner.c:712
#9  0x0000000000975204 in SearchCatCache (cache=0x15d5500,
    v1=v1@entry=10, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0)
    at catcache.c:1209
#10 0x0000000000984714 in SearchSysCache (cacheId=cacheId@entry=11,
    key1=key1@entry=10, key2=key2@entry=0, key3=key3@entry=0,
    key4=key4@entry=0) at syscache.c:840
#11 0x00000000009d3bc0 in superuser_arg (roleid=10)
    at superuser.c:79
#12 superuser () at superuser.c:49
#13 0x00000000009d92cc in set_gp_replication_config (
    name=name@entry=0xcab69b "synchronous_standby_names",
    value=value@entry=0xc3fbba "*") at guc_gp.c:5273
---Type <return> to continue, or q <return> to quit---
#14 0x0000000000837783 in SetSyncStandbysDefined ()
    at gp_replication.c:108
#15 0x000000000070ba33 in HandleFtsWalRepProbe ()
    at ftsmessagehandler.c:269
#16 HandleFtsMessage (query_string=<optimized out>,
    query_string@entry=0x14e2830 "PROBE") at ftsmessagehandler.c:343
#17 0x000000000087251b in PostgresMain (argc=<optimized out>,
    argv=argv@entry=0x14f6560, dbname=0x14f6520 "",
    username=<optimized out>) at postgres.c:5223
#18 0x000000000080b056 in BackendRun (port=0x14ede70)
    at postmaster.c:4243
#19 BackendStartup (port=0x14ede70) at postmaster.c:3923
#20 ServerLoop () at postmaster.c:1735
```
### Step to reproduce the behavior
comment out the cache optimization in supperuser_arg() can reproduce this issue.
```
--- a/src/backend/utils/misc/superuser.c
+++ b/src/backend/utils/misc/superuser.c
@@ -68,8 +68,8 @@ superuser_arg(Oid roleid)
        HeapTuple       rtup;

        /* Quick out for cache hit */
-       if (OidIsValid(last_roleid) && last_roleid == roleid)
-               return last_roleid_is_super;
+//     if (OidIsValid(last_roleid) && last_roleid == roleid)
+//             return last_roleid_is_super;
```

@ashwinstar  @jimmyyih  @asimrp please help to take a look, seems fts handler process is accessing the system cache with an empty transaction and empty resource owner.

### PR DESCRIPTION
**Pull request by ashwinstar**
**Reset synchronous_standby_names on FTS mirror promotion.**

    When FTS promotes mirror, in gp_segment_configuration it marks mirror as
    not in sync ('n'). Hence, on mirror when promotion request is received,
    best to reset the synchronous_standby_names. If this is not done,
    commits hang/wait after promotion till next FTS probe cycle to detect
    this condition and reset the synchronous_standby_names.

While adding that fix, encountered the issue mentioned in #4764 hence fixing the same here.

**Avoid superuser() from FTS message handler process.**

    FTS message handler process is special system process, which doesn't
    have access to catalog. Hence, it shouldn't be performing any catalog
    access. Calling `superuser()` via `set_gp_replication_config()` or
    `pg_reload_conf()` results in error for the same reason. Hence, if
    `am_ftshandler` process avoid calling `superuser()` and thereby avoid
    catalog access. Rest all the stuff performed by this process doesn't
    need catalog access.

    Fixes #4764 github issue.

## Here are some reminders before you submit the pull request
- [X] Add tests for the change
- [] Document changes
- [] Communicate in the mailing list if needed
- [X] Pass `make installcheck`

### CODE REVIEW

**Comment by ashwinstar** [comment]
This fix cuts down 1 min from `fts_errors` test (1 min 26 secs before to 26 secs now) and few more cycles from some other walrep related tests. Missed mentioning in the PR description this is fallout from looking into why fts_errors test was taking that long.

File: src/backend/fts/ftsmessagehandler.c [hunk 1]
```diff
@@ -339,7 +339,18 @@ HandleFtsWalRepPromote(void)
...
+	{
+		/*
+		 * Reset sync_standby_names on promotion. This is to avoid commits
+		 * hanging/waiting for replication till next FTS probe. Next FTS probe
+		 * will detect this node to be not in sync and reset the same which
+		 * can take a min. Since we know on mirror promotion its marked as not
+		 * in sync in gp_segment_configuration, best to right away clean the
+		 * sync_standby_names.
+		 */
+		UnsetSyncStandbysDefined();
```
Comment (pengzhout) [inline src/backend/fts/ftsmessagehandler.c]: Make sense, nice catch.
