### PR TITLE
pg_dump: Preserve OID for schema "public" during upgrade

### LINKED ISSUE #6166: pg_upgrade fails if 'public' schema has non-default OID
### Greenplum version or build

`master` branch

### Problem

When upgrading a cluster that has had its `public` schema dropped and recreated, so that its OID is not the default `2200`, pg_upgrade fails to match tables in that schema across the old and new clusters:

```
No match found in old cluster for new relation with OID 16416 in database "regression": "public.test"
No match found in new cluster for old relation with OID 27655 in database "regression": "public.test"
```

It looks like OID preassignment for the `public` schema is skipped, because pg_restore [is skipping the `CREATE SCHEMA public` statement entirely](https://github.com/greenplum-db/gpdb/blob/master/src/bin/pg_dump/pg_backup_archiver.c#L3088-L3102). This causes the OID lookups for the contained tables to fail, because the new cluster thinks those tables should be in a schema with OID `2200`, and the old cluster has a different OID for `public`.

### Upstream Behavior

Interestingly, PostgreSQL as of v11 doesn't maintain the `public` schema OID across upgrade either -- if you `DROP` and re-`CREATE` it, it will have an OID of `2200` again after the upgrade. This doesn't appear to be as big a problem for upstream as it is for us, since the OID preassignment is much simpler.

### PR DESCRIPTION
**Pull request by d**
Given a database in which the "public" schema does not have its default
OID 2200 (e.g. it was dropped and recreated), pg_upgrade would ignore
the previous OID and use the built-in "public" schema at restoration.
This is because creation of the "public" schema is skipped in
dump / restore.

Add a binary_upgrade field to RestoreOptions, to teach pg_dump /
pg_restore not to skip the public schema during binary upgrade. This
adds a new "--binary-upgrade" option to pg_restore.

Co-authored-by: Jacob Champion <pchampion@pivotal.io>
Co-authored-by: Jesse Zhang <sbjesse@gmail.com>

Fixes #6166 

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`

### CODE REVIEW

**Comment by hlinnaka** [comment]
Why is this needed in GPDB, when Postgres works fine without it?

**Comment by d** [comment]
> Why is this needed in GPDB, when Postgres works fine without it?

OID pre-assignment works differently in Greenplum than upstream: rather than simply specifying the OID for "the next" table, in Greenplum we specify the OID for "table named foo in database OID X and schema OID Y".

File: src/bin/pg_dump/pg_backup_archiver.c [hunk 1]
```diff
@@ -383,12 +383,22 @@ RestoreArchive(Archive *AHX)
...
+	if (ropt->dropSchema || ropt->binary_upgrade)
 	{
 		for (te = AH->toc->prev; te != AH->toc; te = te->prev)
 		{
 			AH->currentTE = te;
 
+			/*
+			 * GPDB: In order to maintain the OID of the public schema during
+			 * binary upgrade, we have to drop (and recreate) it even if the
+			 * user doesn't specify --clean.
```
Comment (asimrp) [inline src/bin/pg_dump/pg_backup_archiver.c]: The case of the user specifying --clean is not applicable in `binary_upgrade` mode because `pg_restore` is invoked from `pg_upgrade` without the --clean option.  Is it, then, more readable to `Assert(!ropt->dropSchema)` instead of the `&& !ropt->dropSchema` below?

**Comment by asimrp** [comment]
@d how does upstream OID pre-assignment deals with tables with identical names but different namespaces?

File: src/bin/pg_dump/pg_backup_archiver.c (hunk 1 above)
Comment (jchampio) [reply src/bin/pg_dump/pg_backup_archiver.c]: We considered doing this, but we actually used `pg_dump --binary-upgrade --clean` to reason about how the archiver was doing its work and didn't want to deprive other developers of that debugging tool.

**Comment by jchampio** [comment]
@asimrp Upstream doesn't specify which preassigned OID belongs to what table; it just puts the current object's OID into the global "next OID" variable and assumes that no other object of that type will need to be created before calling the corresponding DDL. (There are similar accommodations made for related toast tables, indexes, etc.)

File: src/bin/pg_dump/pg_backup_archiver.c (hunk 1 above)
Comment (asimrp) [reply src/bin/pg_dump/pg_backup_archiver.c]: Ah, I missed checking `pg_dump` invocations.  Makes sense.
