### PR TITLE
Correctly set locus for WorkTable Scan

### LINKED ISSUE #15555: The result of the hierarchical query is incorrect
### Greenplum version or build
7.0.0-beta.3
### OS version and uname -a
rockylinux
Linux localhost.localdomain 4.18.0-425.3.1.el8.x86_64
### autoconf options used ( config.status --config )
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/home/green/gpdb'
### Installation information ( pg_config )
BINDIR = /home/green/gpdb/bin
DOCDIR = /home/green/gpdb/share/doc/postgresql
HTMLDIR = /home/green/gpdb/share/doc/postgresql
INCLUDEDIR = /home/green/gpdb/include
PKGINCLUDEDIR = /home/green/gpdb/include/postgresql
INCLUDEDIR-SERVER = /home/green/gpdb/include/postgresql/server
LIBDIR = /home/green/gpdb/lib
PKGLIBDIR = /home/green/gpdb/lib/postgresql
LOCALEDIR = /home/green/gpdb/share/locale
MANDIR = /home/green/gpdb/share/man
SHAREDIR = /home/green/gpdb/share/postgresql
SYSCONFDIR = /home/green/gpdb/etc/postgresql
PGXS = /home/green/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/home/green/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/green/gpdb/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -L/usr/lib -lzstd 
VERSION = PostgreSQL 12.12

### Expected behavior
 empno | ename  |   job    | mgr  |  hiredate  |   sal   |  comm   | deptno 
-------+--------+----------+------+------------+---------+---------+--------
  7698 | BLAKE  | MANAGER  | 7839 | 1981-05-01 | 2850.00 |         |     30
  7654 | MARTIN | SALESMAN | 7698 | 1981-09-28 | 1250.00 | 1400.00 |     30
  7499 | ALLEN  | SALESMAN | 7698 | 1981-02-20 | 1600.00 |  300.00 |     30
  7900 | JAMES  | CLERK    | 7698 | 1981-12-03 |  950.00 |         |     30
  7844 | TURNER | SALESMAN | 7698 | 1981-09-08 | 1500.00 |    0.00 |     30
  7521 | WARD   | SALESMAN | 7698 | 1981-02-22 | 1250.00 |  500.00 |     30
(6 rows)

### Actual behavior
 empno | ename |   job   | mgr  |  hiredate  |   sal   | comm | deptno 
-------+-------+---------+------+------------+---------+------+--------
  7698 | BLAKE | MANAGER | 7839 | 1981-05-01 | 2850.00 |      |     30

### Step to reproduce the behaviorvim 1
CREATE TABLE emp_ (
empno NUMERIC(4) NOT NULL,
ename VARCHAR(10),
job VARCHAR(9),
mgr int,
hiredate DATE,
sal NUMERIC(7,2),
comm NUMERIC(7,2),
deptno NUMERIC(2)
) distributed by (empno);

set DateStyle to "ISO, MDY"; 

INSERT INTO emp_ VALUES (7369,'SMITH','CLERK',7902,'17-DEC-80',800,NULL,20);
INSERT INTO emp_ VALUES (7499,'ALLEN','SALESMAN',7698,'20-FEB-81',1600,300,30);
INSERT INTO emp_ VALUES (7521,'WARD','SALESMAN',7698,'22-FEB-81',1250,500,30);
INSERT INTO emp_ VALUES (7566,'JONES','MANAGER',7839,'02-APR-81',2975,NULL,20);
INSERT INTO emp_ VALUES (7654,'MARTIN','SALESMAN',7698,'28-SEP-81',1250,1400,30);
INSERT INTO emp_ VALUES (7698,'BLAKE','MANAGER',7839,'01-MAY-81',2850,NULL,30);
INSERT INTO emp_ VALUES (7782,'CLARK','MANAGER',7839,'09-JUN-81',2450,NULL,10);
INSERT INTO emp_ VALUES (7788,'SCOTT','ANALYST',7566,'19-APR-87',3000,NULL,20);
INSERT INTO emp_ VALUES (7839,'KING','PRESIDENT',NULL,'17-NOV-81',5000,NULL,10);
INSERT INTO emp_ VALUES (7844,'TURNER','SALESMAN',7698,'08-SEP-81',1500,0,30);
INSERT INTO emp_ VALUES (7876,'ADAMS','CLERK',7788,'23-MAY-87',1100,NULL,20);
INSERT INTO emp_ VALUES (7900,'JAMES','CLERK',7698,'03-DEC-81',950,NULL,30);
INSERT INTO emp_ VALUES (7902,'FORD','ANALYST',7566,'03-DEC-81',3000,NULL,20);
INSERT INTO emp_ VALUES (7934,'MILLER','CLERK',7782,'23-JAN-82',1300,NULL,10);
-- explain 
WITH RECURSIVE cte_emp_ AS (
         SELECT emp_.empno,
            emp_.ename,
            emp_.job,
            emp_.mgr,
            emp_.hiredate,
            emp_.sal,
            emp_.comm,
            emp_.deptno
           FROM emp_
          WHERE emp_.empno = 7698::numeric::numeric
        UNION ALL
         SELECT emp_.empno,
            emp_.ename,
            emp_.job, 
            emp_.mgr,
            emp_.hiredate,
            emp_.sal,
            emp_.comm,
            emp_.deptno
            FROM emp_,
            cte_emp_ cte_emp__1 
            WHERE cte_emp__1.empno = emp_.mgr
        )
 SELECT cte_emp_.empno,
    cte_emp_.ename,
    cte_emp_.job,
    cte_emp_.mgr,
    cte_emp_.hiredate,
    cte_emp_.sal,
    cte_emp_.comm,
    cte_emp_.deptno
   FROM cte_emp_;

### PR DESCRIPTION
**Pull request by l-wang**
Prior to 9.6 merge, given the locus of the non-recursive path of a
recursive CTE as input, we used to set the locus of the recursive
path, aka WorkTaleScan, to Strewn in some cases.

This logic was first introduced by commit fd61a4ca26 which initially
brought recursive CTE into Greeanplum. However the logic was lost
during PostgreSQL 9.6 merge by commit
greenplum-db/gpdb-postgres-merge@799c7f90fc in iteration_REL9_6 merge
branch. A GPDB_96_MERGE_FIXME had been added by a merge commit
greenplum-db/gpdb-postgres-merge@c67c3ec4f8, along with this merge
commit, an additional add-on to the logic for OuterQuery by Greenplum
commit 00e25afe11 was also overlooked. Later on by commit b5bc9dfcf9,
even the merge FIXME was innocently removed.

This patch adds the missing logic back and adds test for the same.

Fixes #15555

Proposed-by: Zhenghua Lyu <kainwen@gmail.com>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

File: src/backend/optimizer/util/pathnode.c [hunk 1]
```diff
@@ -3257,6 +3257,31 @@ create_worktablescan_path(PlannerInfo *root, RelOptInfo *rel,
 						  Relids required_outer)
 {
 	Path	   *pathnode = makeNode(Path);
+	CdbPathLocus result;
+	int			numsegments;
+
+	if (rel->cdbpolicy)
+		numsegments = rel->cdbpolicy->numsegments;
+	else
+		numsegments = getgpsegmentCount(); /* FIXME */
```
Comment (kainwen) [inline src/backend/optimizer/util/pathnode.c:3266]: I think numsegments can be set just using the ctelocus's. Others LGTM. Thanks!

**Comment by l-wang** [comment]
While I'm working on this fix, I noticed the following `GPDB_96_MERGE_FIXME` introduced by https://github.com/greenplum-db/gpdb-postgres-merge/commit/c67c3ec4f8 . As the FIXME claims it largely reverted ad6a6067d9. This is another major difference between 6X and 7X for recursive CTE and locus. The code being reverted is more complicated and I don't understand the logic well enough to address it at the moment. Noting this down for now and hope to revisit in the future.

```
	/*
	 * If the non-recursive side is SegmentGeneral, force it to be executed
	 * on exactly one segment. The worktable scan we build on the recursive
	 * side will use the same locus as the non-recursive side, and if it's
	 * SegmentGeneral, the result of the join may end up having a different
	 * locus.
	 *
	 * GPDB_96_MERGE_FIXME: On coordinator, before the merge, more complicated
	 * logic was added in commit ad6a6067d9 to make the loci on the WorkTableScan
	 * and the RecursiveUnion correct. That was largely reverted as part of the
	 * merge, and things seem to be working with this much simpler thing, but
	 * I'm not sure if the logic is 100% correct now.
	 */
	if (CdbPathLocus_IsSegmentGeneral(lpath->locus))
	{
		CdbPathLocus gather_locus;

		CdbPathLocus_MakeSingleQE(&gather_locus, lpath->locus.numsegments);
		lpath = cdbpath_create_motion_path(root, lpath, NIL, false, gather_locus);
	}
```

CC: @kainwen @QingMa-gp

File: src/test/regress/sql/gp_recursive_cte.sql [hunk 2]
```diff
@@ -445,3 +445,26 @@ with recursive cte (n) as
   ) q
 )
 select * from cte;
+
```
Comment (kainwen) [inline src/test/regress/sql/gp_recursive_cte.sql:448]: Recommend just using the cases in the Issue. The case in the PR gives the same result without the patch even with a bad plan. I have verified the case in the issue will give correct result under this PR's patch and wrong without this patch.

**Review by kainwen — COMMENTED** [review]
LGTM. Thanks a lot! Only with cases change suggested.

There are 2 TODOs in my mind, I have asked the team to create internal stories to record.

1. Can we improve the code to avoid motion? That is can we create hash distributed locus work table scan? It should be possible to use non-recursive part's locus as template.
2. SegmentGeneral transformation is introduced by me, now I look back it seems not the best way to fix issue before. Let's reconsider the design of it.

**Review by kainwen — APPROVED** [review]

File: src/test/regress/sql/gp_recursive_cte.sql (hunk 2 above)
Comment (l-wang) [reply src/test/regress/sql/gp_recursive_cte.sql:448]: Thank you @kainwen for trying out the test case and great catch! I'm supersized that swapping the two tables of the inner join can actually change the plan!

Initially I had the following test case which generates wrong plan AND wrong result:
```
postgres=# explain (costs off) WITH RECURSIVE cte (i, j) AS (
    SELECT a, b FROM recursive_table_6 WHERE a = 0::numeric::numeric
    UNION ALL
    SELECT a, b FROM recursive_table_6, cte WHERE cte.i = recursive_table_6.b
)
SELECT i, j FROM cte;
                                   QUERY PLAN                                    
---------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Recursive Union
         ->  Seq Scan on recursive_table_6
               Filter: (a = '0'::numeric)
         ->  Hash Join
               Hash Cond: (cte.i = (recursive_table_6_1.b)::numeric)
               ->  WorkTable Scan on cte
               ->  Hash
                     ->  Redistribute Motion 3:3  (slice2; segments: 3)
                           Hash Key: recursive_table_6_1.a
                           ->  Seq Scan on recursive_table_6 recursive_table_6_1
 Optimizer: Postgres query optimizer
(12 rows)

postgres=# WITH RECURSIVE cte (i, j) AS (
    SELECT a, b FROM recursive_table_6 WHERE a = 0::numeric::numeric
    UNION ALL
    SELECT a, b FROM recursive_table_6, cte WHERE cte.i = recursive_table_6.b
)
SELECT i, j FROM cte;
 i | j 
---+---
 0 | 3
(1 row)
```

After writing the fix and tested, I swapped `recursive_table_6` and `cte` in the join of the test case and did not do another round of negative test. My intention was to make the join order in the query same as in the plan only to make the test more readable. I did NOT expect that would change the hash key in the plan to `'0'::numeric` instead of `recursive_table_6_1.a` to below w/o the fix and even (by luck?) produce correct result!

```
postgres=# explain (costs off) WITH RECURSIVE cte (i, j) AS (
    SELECT a, b FROM recursive_table_6 WHERE a = 0::numeric::numeric
    UNION ALL
    SELECT a, b FROM cte, recursive_table_6 WHERE cte.i = recursive_table_6.b
)
SELECT i, j FROM cte;
                                   QUERY PLAN                                    
---------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   ->  Recursive Union
         ->  Seq Scan on recursive_table_6
               Filter: (a = '0'::numeric)
         ->  Hash Join
               Hash Cond: (cte.i = (recursive_table_6_1.b)::numeric)
               ->  WorkTable Scan on cte
               ->  Hash
                     ->  Redistribute Motion 3:3  (slice2; segments: 3)
                           Hash Key: '0'::numeric
                           ->  Seq Scan on recursive_table_6 recursive_table_6_1
 Optimizer: Postgres query optimizer
(12 rows)

postgres=# WITH RECURSIVE cte (i, j) AS (
    SELECT a, b FROM recursive_table_6 WHERE a = 0::numeric::numeric
    UNION ALL
    SELECT a, b FROM cte, recursive_table_6 WHERE cte.i = recursive_table_6.b
)
SELECT i, j FROM cte;
 i | j 
---+---
 0 | 3
 2 | 0
 5 | 0
(3 rows)
```

Thank you so much for investigating! I'm updating the test!

But really, what does it even mean by using a CONST as hash key?

Comment (kainwen) [reply src/test/regress/sql/gp_recursive_cte.sql:448]: > But really, what does it even mean by using a CONST as hash key?

@l-wang  Hash Keys are just expressions to evaluate to some value (const value).
A const expression is also an expression.

**Comment by l-wang** [comment]
> 1. Can we improve the code to avoid motion? That is can we create hash distributed locus work table scan? It should be possible to use non-recursive part's locus as template.

@kainwen +1! I was thinking the same. I was wondering, for the current test case, as well as the case in the original issue, it seems OK for the work table scan to using the non-recursive part's distribution key, and just remove its equivalence class? (I have not thought of other cases though that may need more change).

**Comment by kainwen** [comment]
> > 1. Can we improve the code to avoid motion? That is can we create hash distributed locus work table scan? It should be possible to use non-recursive part's locus as template.
> 
> @kainwen +1! I was thinking the same. I was wondering, for the current test case, as well as the case in the original issue, it seems OK for the work table scan to use the non-recursive part's distribution key, and just remove its equivalence class? (I have not thought of other cases though that may need more change).

It needs some thought an design and we have created internal story.
