### PR TITLE
Fix "cannot execute squelched plan node of type" error (greenplum-db#11673)

### LINKED ISSUE #15415: Why are enable_nestloop and enable_mergejoin set to 'off' by default? Some known issues about nestloop join in legacy planner
## Enhancement
  We are aware that in earlier versions of Greenplum, enable_nestloop and enable_mergejoin were set to 'off' by default, whereas in PostgreSQL upstream they are 'on'.

  We had met several problems when enable_nestloop set to 'off', here using TPC-H tables to help me explain:
```
CREATE TABLE public.orders (
    o_orderkey bigint NOT NULL,
    o_custkey bigint NOT NULL,
    o_orderstatus character(1),
    o_totalprice numeric(15,2),
    o_orderdate date,
    o_orderpriority character(15),
    o_clerk character(15),
    o_shippriority integer,
    o_comment character varying(79)
)
 DISTRIBUTED BY (o_orderkey);
CREATE INDEX custkey_idx ON public.orders USING btree (o_custkey);
CREATE INDEX orderkey_idx ON public.orders USING btree (o_orderkey);
```

```
CREATE TABLE public.nation (
    n_nationkey bigint NOT NULL,
    n_name character(25),
    n_regionkey bigint NOT NULL,
    n_comment character varying(152)
)
 DISTRIBUTED REPLICATED;
CREATE INDEX nation_idx ON public.nation USING btree (n_nationkey);
```

### planner cannot choose index join most of time
  Because enable_nestloop to set to off, a disable_cost is added to nestloop join, hash join will always have a lower cost. So index join, which is presented as nestloop join, cannot be used in planner. But hash join is slower than index join in many cases, for explain:
```
tpch=# set optimizer to off;
SET
tpch=# explain analyze select o_orderkey from orders join nation on o_orderkey = n_nationkey;
                                                          QUERY PLAN                                                           
-------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=3.52..28573.89 rows=23 width=8) (actual time=745.986..860.032 rows=7 loops=1)
   ->  Hash Join  (cost=3.52..28573.89 rows=8 width=8) (actual time=37.496..859.274 rows=4 loops=1)
         Hash Cond: (orders.o_orderkey = nation.n_nationkey)
         Extra Text: (seg0)   Hash chain length 1.0 avg, 1 max, using 23 of 8388608 buckets.
         ->  Seq Scan on orders  (cost=0.00..21846.00 rows=500000 width=8) (actual time=0.009..276.440 rows=500449 loops=1)
         ->  Hash  (cost=3.23..3.23 rows=8 width=8) (actual time=0.044..0.044 rows=23 loops=1)
               ->  Seq Scan on nation  (cost=0.00..3.23 rows=23 width=8) (actual time=0.009..0.018 rows=23 loops=1)
 Planning time: 3.671 ms
   (slice0)    Executor memory: 59K bytes.
   (slice1)    Executor memory: 65610K bytes avg x 3 workers, 65610K bytes max (seg0).  Work_mem: 1K bytes max.
 Memory used:  2097152kB
 Optimizer: Postgres query optimizer
 Execution time: 861.305 ms
(13 rows)
```
By setting nestloop join cost to normal, planner choose index join, and we get a better Execution time.

```
tpch=# set enable_nestloop to on;
SET
tpch=# explain analyze select o_orderkey from orders join nation on o_orderkey = n_nationkey;
                                                              QUERY PLAN                                                               
---------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.18..92.00 rows=23 width=8) (actual time=0.816..0.835 rows=7 loops=1)
   ->  Nested Loop  (cost=0.18..92.00 rows=8 width=8) (actual time=0.033..0.109 rows=4 loops=1)
         ->  Seq Scan on nation  (cost=0.00..3.23 rows=23 width=8) (actual time=0.005..0.010 rows=23 loops=1)
         ->  Index Only Scan using orderkey_idx on orders  (cost=0.18..3.85 rows=1 width=8) (actual time=0.001..0.003 rows=0 loops=23)
               Index Cond: (o_orderkey = nation.n_nationkey)
               Heap Fetches: 0
 Planning time: 3.573 ms
   (slice0)    Executor memory: 92K bytes.
   (slice1)    Executor memory: 154K bytes avg x 3 workers, 154K bytes max (seg0).
 Memory used:  2097152kB
 Optimizer: Postgres query optimizer
 Execution time: 2.017 ms
(12 rows)
```

### planner cannot create hash path, disable cost becomes a disaster
  When join clause is not an equal expr or NULL, planner cannot create hash path, nestloop path will be chosen, but because of disable cost, other paths cost may be treated properly. For example:
```
tpch=# explain analyze select o_custkey, max(o_orderdate) from orders join nation on o_orderkey = n_nationkey where n_nationkey = 1 group by o_custkey;
                                                                  QUERY PLAN                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=10000000000.18..10000054037.02 rows=1 width=12) (actual time=505.427..514.614 rows=1 loops=1)
   ->  GroupAggregate  (cost=10000000000.18..10000054037.02 rows=1 width=12) (actual time=504.597..504.598 rows=1 loops=1)
         Group Key: orders.o_custkey
         ->  Nested Loop  (cost=10000000000.18..10000054037.00 rows=2 width=12) (actual time=125.283..504.583 rows=1 loops=1)
               ->  Index Scan using custkey_idx on orders  (cost=0.18..54033.70 rows=1 width=20) (actual time=125.258..504.553 rows=1 loops=1)
                     Filter: (o_orderkey = 1)
               ->  Seq Scan on nation  (cost=0.00..3.29 rows=2 width=8) (actual time=0.014..0.018 rows=1 loops=1)
                     Filter: (n_nationkey = 1)
 Planning time: 2.493 ms
   (slice0)    Executor memory: 156K bytes.
   (slice1)    Executor memory: 92K bytes avg x 3 workers, 92K bytes max (seg0).
 Memory used:  2097152kB
 Optimizer: Postgres query optimizer
 Execution time: 515.969 ms
(14 rows)
```
This query cannot use hash join because join clause is optimized by _equivclass_, join key is empty, this is fine. But table orders scan does not use orderkey_idx to do the filter,   custkey_idx is chosen because of disable cost.(Why this happened? See _add_path()_, orderkey_idx path's cost is not 1.01 better than custkey_idx path's cost , path key leading).
By setting enable_nestloop to on, plan is good enough.

```
tpch=# set enable_nestloop to on;
SET
tpch=# explain analyze select o_custkey, max(o_orderdate) from orders join nation on o_orderkey = n_nationkey where n_nationkey = 1 group by o_custkey;
                                                               QUERY PLAN                                                               
----------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=11.51..11.52 rows=1 width=12) (actual time=1.482..1.482 rows=1 loops=1)
   ->  HashAggregate  (cost=11.51..11.52 rows=1 width=12) (actual time=0.094..0.122 rows=1 loops=1)
         Group Key: orders.o_custkey
         Extra Text: (seg1)   Hash chain length 1.0 avg, 1 max, using 1 of 32 buckets; total 0 expansions.
 
         ->  Nested Loop  (cost=0.18..11.49 rows=2 width=12) (actual time=0.033..0.039 rows=1 loops=1)
               ->  Index Scan using orderkey_idx on orders  (cost=0.18..8.20 rows=1 width=20) (actual time=0.015..0.016 rows=1 loops=1)
                     Index Cond: (o_orderkey = 1)
               ->  Seq Scan on nation  (cost=0.00..3.29 rows=2 width=8) (actual time=0.012..0.016 rows=1 loops=1)
                     Filter: (n_nationkey = 1)
 Planning time: 2.521 ms
   (slice0)    Executor memory: 156K bytes.
   (slice1)    Executor memory: 141K bytes avg x 3 workers, 180K bytes max (seg1).
 Memory used:  2097152kB
 Optimizer: Postgres query optimizer
 Execution time: 2.756 ms
(16 rows)
```

### JIT execution
In GP7, we get JIT execution ability from PG upsteam. In some queries nestloop join is chosen instead of hash join because of non-equal join clause, due to nestloop disabled cost, planner further choosing JIT execution. This results in worse performance compared to interpreted execution, because when querying with simple data set, JIT execution init time is longer than execution time, should not be chosen.

## Some thoughts and conclusions 
1. In SQL session, 'set enable_nestloop to on;' is a way to solve problem in above examples I've gave, but in many scenarios, we cannot simply turn on nestloop, or we need to spend a lot of time pinpointing the issues caused by nestloop being turned off.
2. In my opinions that in past nestloop and mergejoin were set to off,  because GP legacy planner may produce some bad plans with nestloop plan and cause performance problems in GP MPP execution mode. And I was also told by chatGPT that:
> However, nested loop joins can be inefficient for large tables, as they require a lot of processing power and memory. Therefore, the Nestloop parameter in Greenplum is set to off by default to prevent unnecessary use of nested loop joins.
3. Nowadays, legacy planner had fixed many issues, nestloop and mergejoin should be much safer in legacy planner, and we may not avoid to turn them to on, same to PG. There may remain some issues, but we can fix them, rather than to turn nestloop off.

### PR DESCRIPTION
**Pull request by wuyuhao28**
This error is caused by the execution logic of Hash Join Node, when the outernode does not fetch a tuple, it calls the ExecSquelchNode method let the lowernodes not to produce tuples anymore, leaving the inner node "squalched" but "un-executed" state. If the hash join needs to be rescanned, then the inner nodes has to be rescanned too if Hash Node's lefttree does not have chgParam, and finally a node does not have chgParam but "squelched" will cause ERROR.

Let's explain with example given in issue #11673 

```
gpadmin=# set from_collapse_limit = 1; set join_collapse_limit = 1;
SET
gpadmin=# explain select * from pg_namespace  join lateral  (select * from aclexplode(nspacl) x join pg_authid  on x.grantee = pg_authid.oid) z on true;
                                  QUERY PLAN
-------------------------------------------------------------------------------
 Nested Loop  (cost=10000000001.02..10000000003.52 rows=24 width=284)
   ->  Seq Scan on pg_namespace  (cost=0.00..1.07 rows=7 width=113)
   ->  Hash Join  (cost=1.02..1.20 rows=4 width=171)
         Hash Cond: (x.grantee = pg_authid.oid)
         ->  Function Scan on aclexplode x  (cost=0.00..0.10 rows=10 width=41)
         ->  Hash  (cost=1.01..1.01 rows=1 width=134)
               ->  Seq Scan on pg_authid  (cost=0.00..1.01 rows=1 width=134)
 Optimizer: Postgres query optimizer
(8 rows)

gpadmin=#  select * from pg_namespace  join lateral  (select * from aclexplode(nspacl) x join pg_authid  on x.grantee = pg_authid.oid) z on true;
ERROR:  cannot execute squelched plan node of type: 211 (execProcnode.c:612)
```
The executor do the following steps:
1. node Nestloop fetch an outer node's tuple, and begin to fetch an inner node, which is Hash Join's tuple to join;
2. Hash Join "prefetch" a tuple first(Which is from Function Scan), before build hash table, to see if outer node's has tuples, in this case, first output from aclexplode(nspacl) with input nspacl is empty, so Hash Join will set hj_OuterNotEmpty to false, return empty tuple and do not build hash table. Which means Hash Join's inner node is never executed now;
3. Before Hash Join return empty to upper node, Hash Join will do squelch work, set HashJoin->Hash->SeqScan node's squelched flag to true;
4. NestLoop Node fetch empty inner tuple, current Outer tuple cannot join. Next will get a new outer join, and begin to rescan inner Nodes to get new inner tuple;
5. When ExecReScanHashJoin, because hash table has not been built, HashJoin inner node's would not exec rescan to set squelched flag to false. See void ExecReScanHashJoin(HashJoinState *node) implement;
6. Finally when Hash Join "prefetch" a tuple from outer Node, begin to build hash table from inner Nodes, a squelched SeqScan in execProcNode will raise ERROR.

In conclusion, the bug occurs when HashJoin's outer node's has chgParam, but the first output tuple from outer node is empty, when combing with rescan, such as NestLoop inner node, the ERROR is raised.
I've also met this bug when I tried to fix #15415 (Looking forward for someone to discuss), the SQL plan shown as below, we can see HashJoin's outer Node is Index Scan with chgParam:

```
regression=#  explain  SELECT 1 AS VisimapPresent FROM pg_appendonly WHERE visimaprelid is
not NULL AND visimapidxid is not NULL AND relid in (SELECT c.oid FROM
pg_class c join pg_namespace n on c.relnamespace = n.oid and
 c.relname like 'sto_alt_uao_part_splitpartition%' and
 n.nspname = 'alter_ao_part_tables_splitpartition_row');
                                              QUERY PLAN                                               
-------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=10.37..10.40 rows=4 width=6)
   Group Key: pg_appendonly.ctid
   ->  Nested Loop  (cost=1.27..10.37 rows=4 width=6)
         ->  Seq Scan on pg_appendonly  (cost=0.00..1.00 rows=1 width=10)
               Filter: ((visimaprelid IS NOT NULL) AND (visimapidxid IS NOT NULL))
         ->  Hash Join  (cost=1.27..9.33 rows=4 width=4)
               Hash Cond: (c.relnamespace = n.oid)
               ->  Index Scan using pg_class_oid_index on pg_class c  (cost=0.15..8.17 rows=1 width=8)
                     Index Cond: (oid = pg_appendonly.relid)
                     Filter: (relname ~~ 'sto_alt_uao_part_splitpartition%'::text)
               ->  Hash  (cost=1.11..1.11 rows=1 width=4)
                     ->  Seq Scan on pg_namespace n  (cost=0.00..1.11 rows=1 width=4)
                           Filter: (nspname = 'alter_ao_part_tables_splitpartition_row'::name)
 Optimizer: Postgres query optimizer
(14 rows)
```

This commit resolves the issue by handling of the rescan method in HashJoin Node, when hash table does not build, plan will do rescan to reset squelched flag.

This fix hasn't undergone thorough testing yet. Can I have some review feedback first, please? Thanks

### CODE REVIEW

**Comment by kainwen** [comment]
Seems like just the same idea of yours @zxuejing in our previous discussion. Please help review it. Thanks.

-------

@wuyuhao28 Thanks for your contribution. Please add a test case.

**Comment by zxuejing** [comment]
> Seems like just the same idea of yours @zxuejing in our previous discussion. Please help review it. Thanks.

hi @wuyuhao28 Your analysis is fantastic, I tried to fix this issue the similar way with you.
But due to this is caused by lateral join, and GPDB does not support lateral feature officially.
So we did not fix it.
I will review the pr.
can you add some testcases？Thank you for your contribution!

File: src/backend/executor/nodeHashjoin.c [hunk 1]
```diff
@@ -1684,6 +1684,15 @@ ExecReScanHashJoin(HashJoinState *node)
 				ExecReScan(node->js.ps.righttree);
 		}
 	}
+	else 
+	{
+		/*
+		 * HashTable Not build, plan need rescan to reset squelched flag, which
+		 * is set by ExecSquelchHashJoin
+		 */
+		if (node->js.ps.righttree->chgParam == NULL)
```
Comment (zxuejing) [inline src/backend/executor/nodeHashjoin.c:1693]: if (node->js.ps.righttree->chgParam == NULL
			&& node->js.ps.righttree->squelched)
			ExecReScan(node->js.ps.righttree);
shall we judge the squelched mark to reduce some none necessary call of ExecReScan?

File: src/test/regress/sql/bfv_joins.sql [hunk 2]
```diff
@@ -497,6 +497,34 @@ join baz on varchar_3=text_any;
 select varchar_3, char_3, text_any from foo join bar on varchar_3=char_3
 join baz on varchar_3=text_any;
 
+--
+-- Test case for Hash Join rescan after squelched without hashtable built
+-- See https://github.com/greenplum-db/gpdb/pull/15590
+--
+create table l_table (a int,  b int) distributed replicated;
```
Comment (zxuejing) [inline src/test/regress/sql/bfv_joins.sql:504]: The test case you construct is very ingenious.
And we can also add the lateral test case which reported in issue#11673

File: src/backend/executor/nodeHashjoin.c [hunk 3]
```diff
@@ -1684,6 +1684,17 @@ ExecReScanHashJoin(HashJoinState *node)
...
 	}
+	else 
+	{
+		/*
+		 * GPDB: HashTable not built with righttree may be squelched,
+		 * HashJoin need rescan righttree to reset its squelch flag.
+		 */
+		if (node->js.ps.righttree->chgParam == NULL &&
+			node->js.ps.righttree->squelched &&
+			node->hj_JoinState == HJ_BUILD_HASHTABLE)
```
Comment (zxuejing) [inline src/backend/executor/nodeHashjoin.c:1695]: Hi
else branch means (node->hj_HashTable == NULL)
if (node->hj_HashTable == NULL) the node->hj_JoinState is always HJ_BUILD_HASHTABLE.
So here we do not need to judge (node->hj_JoinState == HJ_BUILD_HASHTABLE)

**Review by zxuejing — APPROVED** [review]

**Comment by zxuejing** [comment]
I will run a pipeline.

**Comment by kainwen** [comment]
What a clever test case!
