### PR TITLE
Use the right rel for largest_child_relation().

### LINKED ISSUE #6599: Planner sigsegv
I compiled lastest master on Mac and following query encountered crash sometimes.
```
CREATE TABLE t1 (id int, c1 text)
DISTRIBUTED BY (id)
PARTITION BY RANGE (id) (DEFAULT PARTITION p1);

SELECT DISTINCT hostname, c1 FROM (
  SELECT *, rank() over (partition by dbid) rn
  FROM (
    SELECT dbid, gpseg.hostname, c1
    FROM t1, gp_segment_configuration gpseg
  ) AS dt
) AS dt2 WHERE dt2.rn <= 1;
```

This query not always crash. Need to submit the query repeatly to reproduce it.
```
± |master → origin ?:3 ✗| → psql
psql (9.4.20)
Type "help" for help.

template1=# SELECT DISTINCT hostname, c1 FROM (
template1(#   SELECT *, rank() over (partition by dbid) rn
template1(#   FROM (
template1(#     SELECT dbid, gpseg.hostname, c1
template1(#     FROM t1, gp_segment_configuration gpseg
template1(#   ) AS dt
template1(# ) AS dt2 WHERE dt2.rn <= 1;
 hostname | c1
----------+----
(0 rows)

template1=# SELECT DISTINCT hostname, c1 FROM (
template1(#   SELECT *, rank() over (partition by dbid) rn
template1(#   FROM (
template1(#     SELECT dbid, gpseg.hostname, c1
template1(#     FROM t1, gp_segment_configuration gpseg
template1(#   ) AS dt
template1(# ) AS dt2 WHERE dt2.rn <= 1;
 hostname | c1
----------+----
(0 rows)

template1=# SELECT DISTINCT hostname, c1 FROM (
template1(#   SELECT *, rank() over (partition by dbid) rn
template1(#   FROM (
template1(#     SELECT dbid, gpseg.hostname, c1
template1(#     FROM t1, gp_segment_configuration gpseg
template1(#   ) AS dt
template1(# ) AS dt2 WHERE dt2.rn <= 1;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```

```
2019-01-03 11:45:20.355095 CST,,,p41462,th0,,,2019-01-03 11:45:18 CST,0,con9,cmd5,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x101557b24 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x204
2    0x1013a0e7f postgres CdbProgramErrorHandler + 0x13f
3    0x7fff586a1b3d libsystem_platform.dylib _sigtramp + 0x1d
4    0x1015966d7 postgres pfree + 0x47
5    0x1014ca87e postgres largest_child_relation + 0x4e
6    0x1014c491a postgres examine_simple_variable + 0x1ea
7    0x1014c4d2e postgres examine_simple_variable + 0x5fe
8    0x1014bf62a postgres examine_variable + 0x1ba
9    0x1014c38f8 postgres estimate_num_groups + 0xb8
10   0x1012aa5c8 postgres grouping_planner + 0x728
11   0x1012a87d6 postgres subquery_planner + 0x8c6
12   0x1012a77a5 postgres standard_planner + 0x435
13   0x1012a7358 postgres planner + 0x168
14   0x10139d4c3 postgres pg_plan_query + 0x53
15   0x10139d59d postgres pg_plan_queries + 0x6d
16   0x1013a1667 postgres exec_simple_query + 0x4e7
17   0x10139fdd4 postgres PostgresMain + 0xdb4
18   0x1013096b9 postgres BackendRun + 0x269
19   0x101308779 postgres BackendStartup + 0x199
```

### Greenplum version or build
PostgreSQL 9.4.20 (Greenplum Database 6.0.0-alpha.0+dev.15431.gbf78d5c41e build dev-oss) on x86_64-apple-darwin18.2.0, compiled by Apple LLVM version 10.0.0 (clang-1000.10.44.4), 64-bit compiled on Jan  2 2019 19:30:10

### OS version and uname -a
MacOS Mojave 10.14.1
Darwin Haos-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

### autoconf options used ( config.status --config )
--prefix=/Users/haowang/usr/local/greenplum-db-master-94' '--with-gssapi' '--with-pgport=5432' '--with-libedit-preferred' '--with-python' '--with-pam' '--with-ldap' '--enable-debug' '--enable-depend' '--disable-orca' '--disable-gpfdist' 'CFLAGS=-O0 -g3 -glldb

### Installation information ( pg_config )
BINDIR = /Users/haowang/usr/local/greenplum-db-master-94/bin
DOCDIR = /Users/haowang/usr/local/greenplum-db-master-94/share/doc/postgresql
HTMLDIR = /Users/haowang/usr/local/greenplum-db-master-94/share/doc/postgresql
INCLUDEDIR = /Users/haowang/usr/local/greenplum-db-master-94/include
PKGINCLUDEDIR = /Users/haowang/usr/local/greenplum-db-master-94/include/postgresql
INCLUDEDIR-SERVER = /Users/haowang/usr/local/greenplum-db-master-94/include/postgresql/server
LIBDIR = /Users/haowang/usr/local/greenplum-db-master-94/lib
PKGLIBDIR = /Users/haowang/usr/local/greenplum-db-master-94/lib/postgresql
LOCALEDIR = /Users/haowang/usr/local/greenplum-db-master-94/share/locale
MANDIR = /Users/haowang/usr/local/greenplum-db-master-94/share/man
SHAREDIR = /Users/haowang/usr/local/greenplum-db-master-94/share/postgresql
SYSCONFDIR = /Users/haowang/usr/local/greenplum-db-master-94/etc/postgresql
PGXS = /Users/haowang/usr/local/greenplum-db-master-94/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/Users/haowang/usr/local/greenplum-db-master-94' '--with-gssapi' '--with-pgport=5432' '--with-libedit-preferred' '--with-python' '--with-pam' '--with-ldap' '--enable-debug' '--enable-depend' '--disable-orca' '--disable-gpfdist' 'CFLAGS=-O0 -g3 -glldb'
CC = gcc
CPPFLAGS = -I/Users/haowang/usr/local/greenplum-db-master-94/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-address -Wno-unused-command-line-argument -g -ggdb -O0 -g3 -glldb -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/Users/haowang/usr/local/greenplum-db-master-94/include
CFLAGS_SL =
LDFLAGS = -Wl,-dead_strip_dylibs -L/Users/haowang/usr/local/greenplum-db-master-94/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpam -lgssapi_krb5 -lm -L/Users/haowang/usr/local/greenplum-db-master-94/lib
VERSION = PostgreSQL 9.4.20

### Step to reproduce the behavior
I can't reproduce it on my centos enviourment.

### PR DESCRIPTION
**Pull request by guofengrichard**
Function largest_child_relation() is used to find the largest child
relation for an inherited/partitioned relation, recursively. Previously
we passed a wrong rel as its param.

This patch finds in root->simple_rel_array the right rel for
largest_child_relation(). Also it replaces several rt_fetch with a
search in root->simple_rte_array.

This patch fixes #6599.

Co-authored-by-by: Melanie Plageman <mplageman@pivotal.io>

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`

### CODE REVIEW

**Comment by magi345** [comment]
Thanks for investigation on this.
Do you consider include the SQL in https://github.com/greenplum-db/gpdb/issues/6599 into ICW test?

File: src/backend/utils/adt/selfuncs.c [hunk 1]
```diff
@@ -4600,7 +4600,7 @@ static void
 examine_simple_variable(PlannerInfo *root, Var *var,
 						VariableStatData *vardata)
 {
-	RangeTblEntry *rte = rt_fetch(var->varno, root->parse->rtable);
+	RangeTblEntry *rte = root->simple_rte_array[var->varno];
```
Comment (hlinnaka) [inline src/backend/utils/adt/selfuncs.c]: Elsewhere in selfuncs.c, we use planner_rt_fetch(). That seems like a good idea here, too.

Comment (hlinnaka) [reply src/backend/utils/adt/selfuncs.c]: I take that back. Upstream uses `simple_rte_array` directly. So yeah, let's do that in GPDB, too.
