### PR TITLE
Vacuum fix for ERROR updated tuple is already HEAP_MOVED_OFF.

### LINKED ISSUE #4298: 'updated tuple is already HEAP_MOVED_OFF' error in gpexpand
On the walreplication branch, we're seeing a failure like this in the `gpexpand` regression tests:

```
20180111:16:00:06:025858 gpexpand:mdw:gpadmin-[INFO]:-Syncing Greenplum Database extensions
20180111:16:00:07:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw4 are consistent.
20180111:16:00:08:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw1 are consistent.
20180111:16:00:09:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw2 are consistent.
20180111:16:00:09:025858 gpexpand:mdw:gpadmin-[INFO]:-The packages on sdw3 are consistent.
20180111:16:00:10:025858 gpexpand:mdw:gpadmin-[INFO]:-Creating segment template
20180111:16:00:10:025858 gpexpand:mdw:gpadmin-[INFO]:-VACUUM FULL on the catalog tables
20180111:16:00:11:025858 gpexpand:mdw:gpadmin-[ERROR]:-gpexpand failed: Traceback (most recent call last):
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 2795, in main
    _gp_expand.add_segments()
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 1345, in add_segments
    self.segTemplate.build_segment_template()
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 688, in build_segment_template
    self._create_template()
  File "/usr/local/greenplum-db-devel/bin/gpexpand", line 707, in _create_template
    catalog.vacuum_catalog(self.dburl, self.conn, full=True, utility=True)
  File "/usr/local/greenplum-db-devel/lib/python/gppylib/db/catalog.py", line 132, in vacuum_catalog
    vac_curs.execute(sql)
  File "/usr/local/greenplum-db-devel/lib/python/pygresql/pgdb.py", line 259, in execute
    self.executemany(operation, (params,))
  File "/usr/local/greenplum-db-devel/lib/python/pygresql/pgdb.py", line 289, in executemany
    raise DatabaseError("error '%s' in '%s'" % (msg, sql))
DatabaseError: error 'ERROR:  updated tuple is already HEAP_MOVED_OFF (vacuum.c:3906)
' in 'VACUUM FULL pg_catalog.pg_stat_last_operation'
```

I don't know why we're suddenly seeing this on the `walreplication` branch, and not on master, but I was able to reproduce this on `master` too, with the attached script.
[updated-tuple-is-already-HEAP_MOVED_OFF-repro.sql.txt](https://github.com/greenplum-db/gpdb/files/1623546/updated-tuple-is-already-HEAP_MOVED_OFF-repro.sql.txt)

### PR DESCRIPTION
**Pull request by ashwinstar**
`repair_frag()` should consult distributed snapshot
(`localXidSatisfiesAnyDistributedSnapshot()`) while following and moving chains
of updated tuples. Vacuum consults distributed snapshot
(`localXidSatisfiesAnyDistributedSnapshot()`) to find which tuples can be
deleted and not. For RECENTLY_DEAD tuples it used to make decision just based on
comparison with OldestXmin which is not sufficient and even there distributed
snapshot must be checked.

Fixes #4298

### CODE REVIEW

**Comment by ashwinstar** [comment]
On Mon, Jan 29, 2018 at 12:40 PM, Asim RP <notifications@github.com> wrote:

> *@asimrp* approved this pull request.
>
> What confuses me is the following observation. In all calls to
> localXidSatisfiesAnyDistributedSnapshot(), the order is first check local
> snapshot and then check distributed snapshot. Whereas in
> HeapTupleSatisfiesMVCC() the order is to check distributed snapshot first
> and then local snapshot.
>
Let me know if this helps to clear out the confusion,
localXidSatisfiesAnyDistributedSnapshot() is not literally testing against
distributed snapshot. For matter of vacuum, it kind of never uses snapshot
per say. But just oldest in system concept.

So, all uses of localXidSatisfiesAnyDistributedSnapsho() lets the system
decide first based on local check as its cheaper to know if someone locally
can see why bother checking globally. Only if locally we say can be removed
we move ahead to check globally as its more boolean thing and not checking
the in-progress array.

For MVCC snapshot, checking local first doesn't give us any advantage like
that at all, as irrespective need to consult the distributed snapshot and
only if distributed snapshot says it can be ignored can consult the local
and make decision based on it, else just make decision based on distributed
only.

File: src/backend/commands/vacuum.c [hunk 1]
```diff
@@ -3793,8 +3793,10 @@ repair_frag(VRelStats *vacrelstats, Relation onerel,
 			 * separately movable chain, ignoring any intervening DEAD ones.
 			 */
 			if (((tuple.t_data->t_infomask & HEAP_UPDATED) &&
-				 !TransactionIdPrecedes(HeapTupleHeaderGetXmin(tuple.t_data),
-										OldestXmin)) ||
+				 (!TransactionIdPrecedes(HeapTupleHeaderGetXmin(tuple.t_data),
```
Comment (asimrp) [inline src/backend/commands/vacuum.c]: Thank you for the sound explanation, I like it.  There is this case, however, where the argument that "if locally an XID is not old enough then don't bother checking distributed snapshot" doesn't seem to hold.  The objective here is to determine if a XID is not old enough.  Even if a XID is older than`OldestXmin` locally, can it happen that it is still recent globally?  This check ignores such XIDs as dead.

Comment (ashwinstar) [reply src/backend/commands/vacuum.c]: I thought that's the exact case I tried to cover here, with `||`. If XID is older than `OldestXmin` then `!TransactionIdPrecedes(HeapTupleHeaderGetXmin(tuple.t_data),OldestXmin)` will be false and would go to check distributed.

Comment (asimrp) [reply src/backend/commands/vacuum.c]: Indeed!  If an XID is newer than `OldestXmin` it is definitely recent enough regardless of distributed snapshot.  I am convinced, thank you for patiently taking me through it.
