### PR TITLE
Fix incorrect hash-key of Redistribute-Motion when creating path for multi-DQA expr.

### LINKED ISSUE #14096: DISTINCT gives incorrect result in array_agg
### Greenplum version or build
 PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.15588.gfad65d7 build commit:fad65d796f7d2b7c17884d67ed7b79b216f11a71) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Jul 30 2022 08:03:10

### OS version and uname -a
CentOS Linux release 7.9.2009
Linux 9175ca1f-1cd7-47df-4867-6ab7cbcce4b4 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

gcr.io/data-gpdb-public-images/gpdb7-centos7-build

### autoconf options used ( config.status --config )
Concourse `bin_gpdb`: gs://pivotal-gpdb-concourse-resources-prod/server/published/master/server-rc-7.0.0-alpha.0+dev.15588.gfad65d7-rhel7_x86_64.tar.gz

### Step to reproduce the behavior
```
DROP TABLE IF EXISTS abalone_special_char2;
CREATE TABLE abalone_special_char2 (
    id serial,
    sex character varying,
    length double precision,
    diameter double precision,
    height double precision,
    class bigint
);
COPY abalone_special_char2 (sex, length, diameter, height, class) FROM stdin WITH DELIMITER '|' NULL as '@';
FFa|0.475|0.37|0.125|2
FFs|0.55|0.44|0.15|0
FFd|0.565|0.44|0.155|2
MMa|0.44|0.365|0.125|0
MMs|0.475|0.37|0.125|2
MMd|0.47|0.355|0.100|1
F|0.55|0.44|0.15|0
\.

SELECT array_agg(DISTINCT (class)::TEXT) AS class, array_agg(DISTINCT (id)::TEXT) AS id,
array_agg(DISTINCT (sex)::TEXT) AS sex
  FROM abalone_special_char2;
```

### Expected behavior
`class` should have 0,1,2 in some order

### Actual behavior
`class` has duplicate values
```
   class   |       id        |             sex             
-----------+-----------------+-----------------------------
 {2,1,0,2} | {4,2,1,3,5,6,7} | {F,MMd,FFa,FFs,MMa,FFd,MMs}
```

### Similar queries:
Not casting to TEXT:
```
SELECT array_agg(DISTINCT (class)) AS class, array_agg(DISTINCT (id)::TEXT) AS id,
array_agg(DISTINCT (sex)::TEXT) AS sex
  FROM abalone_special_char2;
    class    |       id        |             sex             
-------------+-----------------+-----------------------------
 {0,1,2,2,2} | {1,3,5,6,7,4,2} | {FFd,MMs,F,MMd,FFa,FFs,MMa}
```
Remove `sex` array_agg (correct result):
 ```
SELECT array_agg(DISTINCT (class)) AS class, array_agg(DISTINCT (id)::TEXT) AS id 
  FROM abalone_special_char2;         
  class  |       id        
---------+-----------------
 {2,0,1} | {7,1,2,3,4,6,5}
```
Remove `id` array_agg:
```
SELECT array_agg(DISTINCT (class)) AS class,                                      
array_agg(DISTINCT (sex)::TEXT) AS sex
  FROM abalone_special_char2;
    class    |             sex             
-------------+-----------------------------
 {1,2,0,2,2} | {FFa,FFd,F,FFs,MMa,MMd,MMs}
```
If the table is distributed on class, it works correctly. I was not able to repro this locally on Mac but it consistently happens on concourse.

### PR DESCRIPTION
**Pull request by higuoxing**
This patch is to fix #14096.

How does multi-DQA work:

When creating path for multi-DQA (multiple distinct qualified aggregate), the planner generates the plan as follows:

```
Finalize Aggregate
  -> Gather Motion
       -> Partial Aggregate
            -> HashAggregate, to remove duplicates
                 -> Redistribute Motion
                      -> TupleSplit (according to DISTINCT expr)
                           -> input
```

The plan is generated via the following steps:

1. The planner compares the expr in DQA with the input tuples, if the DQA expr is not in PathTarget, the TupleSplit node will append the corresponding column the the PathTarget together with a special column 'AggExprId' to the output tuple. E.g., if the input of TupleSplit is '(a: 1, b: 2, c: 3)' and the DQA expressions are 'DQA(a)', 'DQA(b)', the output of TupleSplit are '(a: 1, b: null, c: 3, AggExprId: 1)', '(a: null, b: 2, c: 3, AggExprId: 2)'. Only one of the DQA expr's column is set to non-null per tuple and the AggExprId is used to indicate which DQA expr's column is non-null in that tuple.

2. The output tuples of TupleSplit are hashed and sent to different segments via Redistribute-Motion. Because in the previous stage, only one of the DQA expr's column is set to non-null per tuple, DQA expr with same value is gathered on the same segment and we can apply HashAggregate on these tuples to remove duplicate values.

3. We apply Partial Aggregate function on tuples across segments.

4. We gather tuples to QD and apply the Finalize Aggregate function on tuples.

The RCA is given below:

1. When there're type conversions in DQA exprs, the planner will wrap the expr with type conversion node. E.g., for binary-compatible datatypes, like 'VARCHAR' and 'TEXT' the expr will be wrapped with 'ReplabelType' node.

2. When there are queries like 'SELECT DQA(a::TEXT) FROM foo(a VARCHAR)', the planner compares the DQA expr with exprs in PathTarget directly without removing the 'RelabelType' node. So, the TupleSplit looks like:

   ```
   TupleSplit:
     Input: a
     Output: a, a::TEXT
   ```

3. When the planner generating the Redistribute-Motion operator, it tries to find the expr of equivalent class with the expr in targetlist as the hashkey (src/backend/cdb/cdbpullup.c:cdbpullup_findEclassInTargetList). However, in this stage, the planner will ignore the 'RelabelType' when comparing two exprs. Finally, the planner may choose incorrect column as the hash key.

This patch helps resolve the issue by teaching 'TupleSplit' node to ignore 'RelabelType' node when comparing DQA expr and the one in PathTarget. So the TupleSplit node looks like:

```
TupleSplit:
  Input: a
  Output: a
```

when planning queries like: 'SELECT DQA(a::TEXT) FROM foo(a VARCHAR)'.

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [x] Pass `make installcheck`

### CODE REVIEW

File: src/backend/cdb/cdbgroupingpaths.c [hunk 1]
```diff
@@ -2031,12 +2031,29 @@ fetch_multi_dqas_info(PlannerInfo *root,
...
 			int         dqa_idx = 0;
+			Expr		*naked_tle_expr = arg_tle->expr;
+
+			/*
+			 * When conversions between two binary-compatible types happen in
+			 * DQA expressions, the expr(s) in arg_tle and proj_target->exprs
+			 * may be wrapped with a RelabelType node. The RelabelType node doesn't
+			 * affect the semantics, so we ignore it here.
+			 * For conversions that are not binary-compatible, the expr is wrapped with
+			 * a CoerceViaIO node.
```
Comment (higuoxing) [inline src/backend/cdb/cdbgroupingpaths.c:2042]: There're also other types of nodes for datatype conversion, I will update this comment later.

**Review by kainwen — APPROVED** [review]
LGTM. Thanks.

I do not find the `array_agg` case in the original issue, please also add the case in that issue.

**Comment by higuoxing** [comment]
> LGTM. Thanks.
> 
> I do not find the `array_agg` case in the original issue, please also add the case in that issue.

I'm afraid of the result of `array_agg` isn't stable (if I add `ORDER BY` clause to DQA expr the issue is gone), so I replace it with `count()` in my tests.

The result isn't stable:
```
postgres=# SELECT array_agg(DISTINCT class) AS class, array_agg(DISTINCT (id)::TEXT) AS id, array_agg(DISTINCT (sex)::TEXT) AS sex FROM abalone_special_char2;
    class    |       id        |             sex
-------------+-----------------+-----------------------------
 {2,0,1,2,2} | {2,1,3,5,6,7,4} | {FFa,FFs,MMa,FFd,MMs,F,MMd}
(1 row)

postgres=# SELECT array_agg(DISTINCT class) AS class, array_agg(DISTINCT (id)::TEXT) AS id, array_agg(DISTINCT (sex)::TEXT) AS sex FROM abalone_special_char2;
    class    |       id        |             sex
-------------+-----------------+-----------------------------
 {0,1,2,2,2} | {1,3,5,6,7,4,2} | {FFd,MMs,F,MMd,FFa,FFs,MMa}
(1 row)
```

After adding `ORDER BY` clause, the issue is gone:
```
postgres=# SELECT array_agg(DISTINCT class ORDER BY class) AS class, array_agg(DISTINCT (id)::TEXT) AS id, array_agg(DISTINCT (sex)::TEXT) AS sex FROM abalone_special_char2;
  class  |       id        |             sex
---------+-----------------+-----------------------------
 {0,1,2} | {1,2,3,4,5,6,7} | {F,FFa,FFd,FFs,MMa,MMd,MMs}
(1 row)
```

**Comment by kainwen** [comment]
> > LGTM. Thanks.
> > I do not find the `array_agg` case in the original issue, please also add the case in that issue.
> 
> I'm afraid of the result of `array_agg` isn't stable (if I add `ORDER BY` clause to DQA expr the issue is gone), so I replace it with `count()` in my tests.
> 
> The result isn't stable:
> 
> ```
> postgres=# SELECT array_agg(DISTINCT class) AS class, array_agg(DISTINCT (id)::TEXT) AS id, array_agg(DISTINCT (sex)::TEXT) AS sex FROM abalone_special_char2;
>     class    |       id        |             sex
> -------------+-----------------+-----------------------------
>  {2,0,1,2,2} | {2,1,3,5,6,7,4} | {FFa,FFs,MMa,FFd,MMs,F,MMd}
> (1 row)
> 
> postgres=# SELECT array_agg(DISTINCT class) AS class, array_agg(DISTINCT (id)::TEXT) AS id, array_agg(DISTINCT (sex)::TEXT) AS sex FROM abalone_special_char2;
>     class    |       id        |             sex
> -------------+-----------------+-----------------------------
>  {0,1,2,2,2} | {1,3,5,6,7,4,2} | {FFd,MMs,F,MMd,FFa,FFs,MMa}
> (1 row)
> ```
> 
> After adding `ORDER BY` clause, the issue is gone:
> 
> ```
> postgres=# SELECT array_agg(DISTINCT class ORDER BY class) AS class, array_agg(DISTINCT (id)::TEXT) AS id, array_agg(DISTINCT (sex)::TEXT) AS sex FROM abalone_special_char2;
>   class  |       id        |             sex
> ---------+-----------------+-----------------------------
>  {0,1,2} | {1,2,3,4,5,6,7} | {F,FFa,FFd,FFs,MMa,MMd,MMs}
> (1 row)
> ```

Make sense. `order by` change the plan.

**Review by adam8157 — APPROVED** [review]
Excellent PR.

The added case could be reproduced without this fix, right?

**Comment by higuoxing** [comment]
> Excellent PR.
> 
> The added case could be reproduced without this fix, right?

Yes. Below is the result of one of the test case without this fix:

```
postgres=# select count(distinct (b)::text) as b, count(distinct (a)::text) as a from dqa_f3;
explain (verbose, costs off) select count(distinct (b)::text) as b, count(distinct (a)::text) as a from dqa_f3;
 b | a
---+---
 4 | 7
(1 row)

                                           QUERY PLAN
------------------------------------------------------------------------------------------------
 Finalize Aggregate
   Output: count(DISTINCT ((b)::text)), count(DISTINCT ((a)::text))
   ->  Gather Motion 3:1  (slice1; segments: 3)
         Output: (PARTIAL count(DISTINCT ((b)::text))), (PARTIAL count(DISTINCT ((a)::text)))
         ->  Partial Aggregate
               Output: PARTIAL count(DISTINCT ((b)::text)), PARTIAL count(DISTINCT ((a)::text))
               ->  Redistribute Motion 3:3  (slice2; segments: 3)
                     Output: b, a, ((b)::text), ((a)::text), (AggExprId)
                     Hash Key: ((b)::text), a, (AggExprId)
                     ->  Streaming HashAggregate
                           Output: b, a, ((b)::text), ((a)::text), (AggExprId)
                           Group Key: AggExprId, ((dqa_f3.b)::text), ((dqa_f3.a)::text)
                           ->  TupleSplit
                                 Output: b, a, ((b)::text), ((a)::text), AggExprId
                                 Split by Col: (((dqa_f3.b)::text)), (((dqa_f3.a)::text))
                                 ->  Seq Scan on public.dqa_f3
                                       Output: b, a, (b)::text, (a)::text
 Optimizer: Postgres query optimizer
(18 rows)
```

**Comment by kainwen** [comment]
Let's comment the above case mentioned in https://github.com/greenplum-db/gpdb/pull/14135#issuecomment-1253262116
in the original issue and then push this PR.

Thanks for you contribution!
