### PR TITLE
COPY: remove redundant delimiter checking

### LINKED ISSUE #9111: create external table with delimiter off option， return error.
### Greenplum version or build
Greenplum Database 6.0.1 & Greenplum Database 6.1.0
### OS version and uname -a
Linux master 4.18.0-80.4.2.el8_0.x86_64 #1 SMP Fri Jun 14 13:20:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
`CREATE EXTERNAL TABLE`
### Actual behavior
`ERROR:  COPY delimiter must be a single one-byte character`
### Step to reproduce the behavior
when create external table with delimiter off option, return `ERROR:  COPY delimiter must be a single one-byte character`;

SQL: ```create external table test_delimiter(data text) location('gpfdist://127.0.0.1/test_delimiter.txt') format 'text' (delimiter 'off');```

image

LOG:  2019-11-24 06:21:37.013353 UTC,"gpadmin","ysda",p22194,th470934976,"[local]",,2019-11-24 05:15:30 UTC,0,con967,cmd17,seg-1,,dx875517,,sx1,"ERROR","0A000","COPY delimiter must be a single one-byte character",,,,,,"create external table test_delimiter(data text) location('gpfdist://127.0.0.1/test_delimiter.txt') format 'text' (delimiter 'off');",0,,"copy.c",1467,

it seems `/src/backend/commands/copy.c` at line 1464, hiven't consider the external table.

### PR DESCRIPTION
**Pull request by adam8157**
There is one after and with correct delim_off checking.

And take the chance to tidy the ProcessCopyOptions(), align with
upstream, handle delim_off.

Fixes #9111

### CODE REVIEW

**Comment by hlinnaka** [comment]
I think we need to stop storing the string "off" in cstate->delim. It leads to all kinds of weirdness. For example:

```
-- This works
postgres=# CREATE EXTERNAL TABLE test_delimiter1(data text) LOCATION('gpfdist://127.0.0.1/test_delimiter.txt') FORMAT 'text' (DELIMITER 'off' NULL 'nill');
CREATE EXTERNAL TABLE

-- But this does not.
postgres=# CREATE EXTERNAL TABLE test_delimiter2(data text) LOCATION('gpfdist://127.0.0.1/test_delimiter.txt') FORMAT 'text' (DELIMITER 'off' NULL 'noll');
ERROR:  COPY delimiter must not appear in the NULL specification
```
Of course, the NULL specification doesn't really contain a delimiter, because there is no delimiter when it's "off", but the check gets confused and throws an error if the NULL string contains 'o'. I think there are some other similar problems in the checks, too.

**Comment by hlinnaka** [comment]
What is the use case for `DELIMITER 'off'`? Without a delimiter, how do you delimit fields. Is it only useful if the input has only one column?

**Comment by hlinnaka** [comment]
> What is the use case for `DELIMITER 'off'`? Without a delimiter, how do you delimit fields. Is it only useful if the input has only one column?

To answer my own question, I dug up the old JIRA ticket about introducing that option from 2009:

> MPP-4900
> Description:
> support the scenario where a single column is being loaded via COPY or SELECT from external table with a single column defined, and data is "unstructured" in a way that no delimiter character ever exists.
> 
> this is needed for mapreduce.
>
> comment:
> external tables with a single column can now specify "delimiter 'off'" in the FORMAT string, just like "escape 'off'" in the past. this allows reading unstructured external data, and removes the obligation to find a suitable delimiter character (one that doesn't exist in the data) where in fast no delimiter is needed.
> 
> this is implemented for both text and csv formats in exttabs.
> 
> COPY does not support this feature, simply because it's more complicated to implement it there and there's no real requirement to do it at this time - so prefer to avoid the unnecessary risk and valuable time at this point. This feature is mostly needed for mapreduce which uses exttabs.

That's curious. Why is this needed for "mapreduce"? Why doesn't mapreduce quote/escape the strings like you usually do? What if the input contains newlines; don't you need to escape those anyway? Is DELIMITER 'off' still used by anyone?

File: src/backend/commands/copy.c [hunk 1]
```diff
@@ -1530,12 +1530,6 @@ ProcessCopyOptions(CopyState cstate,
 	if (!cstate->csv_mode && !cstate->escape)
 		cstate->escape = "\\";			/* default escape for text mode */
 
-	/* Only single-byte delimiter strings are supported. */
-	if (strlen(cstate->delim) != 1)
```
Comment (soumyadeep2007) [inline src/backend/commands/copy.c]: Don't we still need to disallow multi-character delimiters? 'off' is a special case.

Comment (adam8157) [reply src/backend/commands/copy.c]: There is another check of this after, and with delim_off check.

Seems this function has several redundant checking because of the merge, going to tidy it up.

**Comment by adam8157** [comment]
I walked through the ProcessCopyOptions(), it should be OK now.

And check #9111, users are using it. Also according to PM, the delimiter 'off' is widely used by the custom_formatter cases.

File: src/backend/commands/copy.c (hunk 1 above)
Comment (soumyadeep2007) [reply src/backend/commands/copy.c]: Got it, thanks!
