### PR TITLE
Fix REORGANIZE=true not redistributing randomly-distributed tables

### LINKED ISSUE #15733: Reorganize the table with distributed randomly not work
### Greenplum version or build

main branch

### Step to reproduce the behavior

```
postgres=# create table tbl(v int) with(appendonly=true, orientation=column) distributed by(v);
CREATE TABLE
postgres=# insert into tbl select generate_series(1,1000);
INSERT 0 1000
postgres=# select gp_segment_id, count(*) from tbl group by gp_segment_id;
 gp_segment_id | count
---------------+-------
             0 |   508
             1 |   492
(2 rows)

postgres=# alter table tbl set with (reorganize=true) distributed randomly;
ALTER TABLE
postgres=# select gp_segment_id, count(*) from tbl group by gp_segment_id;
 gp_segment_id | count
---------------+-------
             0 |   508
             1 |   492
(2 rows)
```

### PR DESCRIPTION
**Pull request by huansong**
We made an optimization (1dc3e975b8a) in which we skip redistribution in an INSERT query if the target table is randomly-distributed. In normal cases that makes sense, but in case of ALTER TABLE SET (REORGANIZE=true), the expectation is that the table's data should be redistributed randomly again.

So now adding a GUC `gp_force_random_redistribution` to force the redistribution if wished (i.e. for REORGANIZE=true). The default is set to false to keep the aforementioned optimization unaffected.

Fix #15733.

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

File: src/backend/commands/tablecmds.c [hunk 1]
```diff
@@ -17726,12 +17726,17 @@ ATExecSetDistributedBy(Relation rel, Node *node, AlterTableCmd *cmd)
 		if (need_reorg)
 		{
 			/*
+			 * Make sure the redistribution happens for a randomly distributed table.
+			 *
 			 * Force the use of Postgres query optimizer, since Pivotal Optimizer (GPORCA) will not
 			 * redistribute the tuples if the current and required distributions
 			 * are both RANDOM even when reorganize is set to "true"
+			 * Also set gp_force_random_redistribution to true.
```
Comment (kainwen) [inline src/backend/commands/tablecmds.c:17734]: For some cases (AO COL) CTAS will pre-built the relation and then insert. That is why it will enter the code path of `create_motion_path_for_insert`. 

For normal heap table, it will enter the code:

```c
/*
 * Add a suitable Motion Path so that the input tuples from 'subpath' are
 * distributed correctly for insertion into target table.
 */
Path *
create_motion_path_for_ctas(PlannerInfo *root, GpPolicy *policy, Path *subpath)
{
	GpPolicyType	policyType = policy->ptype;

	if (policyType == POLICYTYPE_PARTITIONED && policy->nattrs == 0)
	{
		/*
		 * If the target table is DISTRIBUTED RANDOMLY, and the input data
		 * is already partitioned, we could let the insertions happen where
		 * they are. But to ensure more random distribution, redistribute.
		 * This is different from create_motion_path_for_insert().
		 */
		CdbPathLocus targetLocus;

		CdbPathLocus_MakeStrewn(&targetLocus, policy->numsegments);
		return cdbpath_create_motion_path(root, subpath, NIL, false, targetLocus);
	}
	else
		return create_motion_path_for_insert(root, policy, subpath);
}
```

The `if` branch will not consider the new GUC.

So with this patch, setting the new GUC off, CTAS a randomly distributed will still add a redistribute motion.

Other part of code change LGTM.

I think we need to make the behavior clean:

* CTAS
* select into
* alter set distributed by

**Review by kainwen — COMMENTED** [review]
Code change LGMT. Two things:

* leave some comments
* I think test case is a little hard to understand at the 1st glance, maybe just check the plan of CTAS or SELECT-INTO is enough

File: src/backend/commands/tablecmds.c (hunk 1 above)
Comment (huansong) [reply src/backend/commands/tablecmds.c:17734]: Yes this issue is limited to _some_ cases of `REORGANIZE=true` which uses `INSERT ... SELECT` instead of CTAS, as mentioned in the original [issue](https://github.com/greenplum-db/gpdb/issues/15733#issuecomment-1585023374):
```
1. The table is a CO table;
2. The table is an AO table with index;
3. The table has dropped column.
```
I think the previous commit message is not very clear. I've made it better now.

**Comment by huansong** [comment]
> I think test case is a little hard to understand at the 1st glance, maybe just check the plan of CTAS or SELECT-INTO is enough

The thing is that the original issue is for setting distribution policy so I wanted to have a test to show exactly how the bug is gone instead of showing what internally is being resolved (note that the test is in `alter_distribution_policy.sql`). I hope after the commit message is made better, the test case would appear more clear now. LMK if otherwise.

But `EXPLAIN INSERT ...` is probably also valuable to show the direct outcome of setting the GUC. Added in another test file. Thanks for the suggestion!

File: src/include/utils/sync_guc_name.h [hunk 2]
```diff
@@ -51,6 +51,7 @@
 		"gp_ignore_error_table",
 		"gp_indexcheck_insert",
 		"gp_initial_bad_row_limit",
+		"gp_force_random_redistribution",
```
Comment (kainwen) [inline src/include/utils/sync_guc_name.h:54]: Seems this GUC does not need to be sync?

**Review by kainwen — APPROVED** [review]
LGTM.

The new added GUC seems not need to be sync.

File: src/include/utils/sync_guc_name.h (hunk 2 above)
Comment (huansong) [reply src/include/utils/sync_guc_name.h]: Yeah I think you are right. It is only used in planning phase so no need to sync to QEs.
