### PR TITLE
Fix gpinitsystem/gpconfig comment other GUCs with same prefix.

### LINKED ISSUE #12957: gpconfig/gpinitsystem comments other GUC with same prefix by accident
## Bug Report
When we use **gpconfig** to add a new parameter, it may comment another parameter with the same prefix, because in **gpconfig_hepler.py** line 96, the function **_comment_parameter()_** uses _**startswith**_ to match the GUC.

For example, if we use gpconfig to add 2 GUCs, **gp_resqueue_priority** and **gp_resqueue_priority_cpucores_per_segment** to the postgresql.conf:
image

Then we try to modify **gp_resqueue_priority** to 'on' by typing **_gpconfig -c gp_resqueue_priority -v 'on'_**.

Now we go back to the postgresql.conf in either master node or segment node, we will find:
image

The GUC **gp_resqueue_priority_cpucores_per_segment** is also commented because it has the same prefix with **gp_resqueue_priority**.

The same accident also happens in **gpinitsystem** with **-p** option, it will call _**SED_PG_CONF**_ in **gp_bash_functions.sh**, which also uses prefix match somewhere.

### Greenplum version or build
6X_STABLE

### OS version and uname -a
CentOS 7

### Expected behavior
When adding a GUC, only the exact old GUC in postgresql.conf would be commented.

### Actual behavior
Other GUCs with same prefix would also be commented.

### Step to reproduce the behavior
$ gpconfig -c gp_resqueue_priority -v 'off'
$ gpconfig -c gp_resqueue_priority_cpucores_per_segment -v '2'
$ gpconfig -c gp_resqueue_priority -v 'on'

### PR DESCRIPTION
**Pull request by DellCurry**
Fix #12957, modify regex in **gp_bash_functions.sh** and **gpconfig_helper.py** from prefix match to full match after removing spaces.

6X_STABLE and other branches will also benefit from this commit.

### CODE REVIEW

File: gpMgmt/bin/lib/gp_bash_functions.sh [hunk 1]
```diff
@@ -339,11 +339,11 @@ SED_PG_CONF () {
 	KEEP_PREV=$1;shift
 	SED_HOST=$1
 	if [ x"" == x"$SED_HOST" ]; then
-			if [ `$GREP -c "${SEARCH_TXT}[ ]*=" $FILENAME` -gt 1 ]; then
+			if [ `$GREP -c "^[ ]*${SEARCH_TXT}[ ]*=" $FILENAME` -gt 1 ]; then
```
Comment (zhaorui20005) [inline gpMgmt/bin/lib/gp_bash_functions.sh:342]: Since I did not read the whole gpinitsystem, I guess the `^[ ]*` is to avoid greping one line `#port=5432` for `port` as a valid value assignment. So this is another fix for the gpinitsystem?

Comment (DellCurry) [reply gpMgmt/bin/lib/gp_bash_functions.sh:342]: Great catch! I didn't realize that. I add `^[ ]*` just for robustness. Certainly it would also fix the case you illustrate.

**Review by zhaorui20005 — APPROVED** [review]
LGTB. Thanks for your contribution.
