### PR TITLE
Set a flag when window's child is exhausted.

### LINKED ISSUE #2571: Assert failure within HashJoin node
Just encounter an unexpected assertion if plan contain a WINDOW node with a HASHJOIN node as child.

repo steps,

```
create table bar (c int, d int);
create table foo (a int, b int);
insert into bar select i,i from generate_series(1,10) i;
insert into foo select i,i from generate_series(1,10) i;

set optimizer_segments to 1;   // To help generate a plan that WINDOW node with a HASHJOIN node as child
SELECT bar.*, count(*) OVER() AS e FROM foo, bar where foo.b = bar.d;
```

error message:
```
gpadmin=# SELECT bar.*, count(*) OVER() AS e FROM foo, bar where foo.b = bar.d;
FATAL:  Unexpected internal error (nodeHashjoin.c:271)
DETAIL:  FailedAssertion("!(!hashtable->eagerlyReleased)", File: "nodeHashjoin.c", Line: 271)
HINT:  Process 3995 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

Orca is on, assert is enabled.

### PR DESCRIPTION
**Pull request by kavinderd**
There is an assert failure when Window's child is a HashJoin operator
and while filling its buffer Window receives a NULL tuple. In this case
HashJoin will call ExecEagerFreeHashJoin() since it is done returning
any tuples. However, Window once it has returned all the tuples in its
input buffer will call ExecProcNode() on HashJoin. This casues an assert
failure in HashJoin that states that ExecHashJoin() should not be called
if HashJoin's hashtable has already been released.

This commit fixes the above issue by setting a flag in WindowState when
Window encounters a null tuple while filling its buffer. This flag then
guards any subsequent call to ExecProcNode() from fetchCurrentRow()

This fixes #2571

### CODE REVIEW

File: src/backend/executor/nodeWindow.c [hunk 1]
```diff
@@ -4532,7 +4533,7 @@ fetchCurrentRow(WindowState * wstate)
 	else
 	{
 		/* Fetch the first tuple from the outer plan */
-		TupleTableSlot *slot = ExecProcNode(outerPlanState(wstate));
+		TupleTableSlot *slot = !wstate->is_input_done ? ExecProcNode(outerPlanState(wstate)) : NULL;
```
Comment (foyzur) [inline src/backend/executor/nodeWindow.c]: Can you rewrite this to return immediately if is_input_done. Otherwise, assign to slot and continue. This saves one assignment and another TupIsNull comparison.

File: src/backend/executor/nodeWindow.c [hunk 2]
```diff
@@ -2990,6 +2990,7 @@ makeWindowState(Window * window, EState *estate)
 
 	numlevels = list_length(window->windowKeys);
 	wstate->numlevels = numlevels;
+	wstate->is_input_done = false;
```
Comment (foyzur) [inline src/backend/executor/nodeWindow.c]: Not necessary. The makeNode will take care of that.

File: src/backend/executor/nodeWindow.c [hunk 3]
```diff
@@ -4766,7 +4767,10 @@ fetchTupleSlotThroughBuf(WindowState * wstate)
 		TupleTableSlot *slot = ExecProcNode(outerPlanState(wstate));
 
 		if (TupIsNull(slot))
+		{
+			wstate->is_input_done = true;
```
Comment (foyzur) [inline src/backend/executor/nodeWindow.c]: You need to reset it to false when ExecRescanWindow is called.

File: src/backend/executor/nodeWindow.c [hunk 4]
```diff
@@ -4532,7 +4533,7 @@ fetchCurrentRow(WindowState * wstate)
 	else
 	{
 		/* Fetch the first tuple from the outer plan */
```
Comment (foyzur) [inline src/backend/executor/nodeWindow.c]: What is this "first tuple" business? Clearly for first tuple your flag would be false. And subsequently you can call this to fetch other tuples. Is this comment valid?

Comment (kavinderd) [inline src/backend/executor/nodeWindow.c]: This is a pre-existing comment. I think it refers to the fact that the first time `fetchCurrentRow()` is called `ExecProcNode()` must be invoked. Should I leave it in?

File: src/backend/executor/nodeWindow.c (hunk 3 above)
Comment (kavinderd) [inline src/backend/executor/nodeWindow.c]: Good catch, done

**Comment by hsyuan** [comment]
Is the query in the issue included in ICG? If not, can we add a test to cover the changes?

**Comment by kavinderd** [comment]
@hsyuan I added a test case to `olap_window_seq.sql` I think that is the appropriate place

**Comment by d** [comment]
The test exercises `window` over `join`, can you find a case where `window` is rescanned? Like window under `nestloop` maybe?

**Comment by kavinderd** [comment]
@d, will do
