### PR TITLE
set memory allocated by malloc to 0 to fix 'error: ‘data’ may be used uninitialized'

### LINKED ISSUE #13102: Compile failure on Ubuntu 22.04 with gcc 11.2
### Greenplum version or build
master branch
### OS version and uname -a
Ubuntu 22.04
### autoconf options used ( config.status --config )
`./configure`
### Expected behavior
Compile successfully.
### Actual behavior
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration -I../../../../src/include   -D_GNU_SOURCE   -c -o gp_hyperloglog.o gp_hyperloglog.c
In function ‘gp_hll_compress_dense’,
    inlined from ‘gp_hll_compress’ at gp_hyperloglog.c:533:13:
gp_hyperloglog.c:584:11: error: ‘data’ may be used uninitialized [-Werror=maybe-uninitialized]
  584 |     len = pglz_compress(data,data_rawsize,dest,PGLZ_strategy_always);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       ^~~~~~~~~~~~~

```
### Step to reproduce the behavior
`configure && make`

### PR DESCRIPTION
**Pull request by lij55**
set data with bzero in order to fix #13102 comiling error cause by GCC 11.2  [-Werror=maybe-uninitialized].

### CODE REVIEW

File: src/backend/utils/hyperloglog/gp_hyperloglog.c [hunk 1]
```diff
@@ -571,6 +571,7 @@ gp_hll_compress_dense(GpHLLCounter hloglog)
                  errmsg("out of memory"),
                  errdetail("Failed on request of size %zu.", data_rawsize)));
     }
+    bzero(data, data_rawsize);
```
Comment (higuoxing) [inline src/backend/utils/hyperloglog/gp_hyperloglog.c:574]: Maybe using `memset` for better portability?

Comment (lij55) [reply src/backend/utils/hyperloglog/gp_hyperloglog.c:574]: the reason I prefer bzero is from <UNIX Network Programming> of Richard Stevens, which emphasize and use bzero in all the code of the book. Both memset and bzero does the same thing: set memory to 0x00. Advantage of bzero are:
- retuan vaule is void instead of void * so no need to check return value safely.
- one less argument than memset so less change to pass a wrong argument. The 2ed and 3rd argument of memset are hard to remember the type and meaning.

I'm not quite clear about our rule about these functions. It is OK to change it to memset if we have any special rules.

Comment (higuoxing) [reply src/backend/utils/hyperloglog/gp_hyperloglog.c:574]: Thanks for your explanation. It sounds reasonable to me :-)

**Review by higuoxing — APPROVED** [review]

**Comment by lij55** [comment]
this is a stack overflow discussion about those two functions: https://stackoverflow.com/questions/17096990/why-use-bzero-over-memset

There are about 1k memset and about 5 bzero in srouce code. Change to memset here.
