### PR TITLE
Don't simplify uncorrelated EXISTS sublink in some cases

### LINKED ISSUE #11849: ERROR: simplify EXISTS subquery incorrectly
### Greenplum version or build
```
Greenplum Database 7.0.0-alpha.0+dev.14556.gb82efe5b25 build dev
```
### OS version and uname -a
```
x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.27), 64-bit compiled
```

### Expected behavior
```
postgres=# explain select c3 from tmbk where exists (select avg(c1) from tmbk group by c1);
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Result  (cost=26.96..48.26 rows=1130 width=8)
   One-Time Filter: $0
   InitPlan 1 (returns $0)
     ->  HashAggregate  (cost=26.95..29.45 rows=200 width=36)
           Group Key: tmbk_1.c1
           ->  Seq Scan on tmbk tmbk_1  (cost=0.00..21.30 rows=1130 width=4)
   ->  Seq Scan on tmbk  (cost=26.96..48.26 rows=1130 width=8)
(7 rows)
```

### Actual behavior
```
postgres=# explain select c3 from tmbk where exists (select avg(c1) from tmbk group by c1);
psql: ERROR:  ORDER/GROUP BY expression not found in targetlist (tlist.c:421)
```
### Step to reproduce the behavior

`CREATE TABLE tmbk (c1 INT, c2 VARCHAR, c3 TIMESTAMP ) DISTRIBUTED BY (c2);`

`explain select c3 from tmbk where exists (select avg(c1) from tmbk group by c1);`

`psql: ERROR:  ORDER/GROUP BY expression not found in targetlist (tlist.c:421)`

@kainwen @guofengrichard

### PR DESCRIPTION
**Pull request by SmartKeyerror**
This is another way to fix #11849, more details can be found at #13823.

And is this fix, there has no regression on uncorrelated EXISTS sublinks 
that have DISTINCT/DISTINCT ON/ORDER BY clause, but the logic of the 
function `simplify_EXISTS_query()` is more complicated.

This PR and #13823 both can fix issue #11849, and #13823 makes 
`simplify_EXISTS_query()`  easier to understand, but has regression in some 
cases. This PR makes `simplify_EXISTS_query()` a little more complicated, 
but has no regression.

### CODE REVIEW

File: src/backend/optimizer/plan/subselect.c [hunk 1]
```diff
@@ -1824,7 +1832,13 @@ simplify_EXISTS_query(PlannerInfo *root, Query *query)
...
+
+	/*
+	 * Those clauses could be throwed in correlated and uncorrelated sublinks,
+	 * it will not change the correctness of the results, except windowClause.
+	 */
+	if (is_correlated)
+		query->windowClause = NIL;
 	query->distinctClause = NIL;
 	query->sortClause = NIL;
 	query->hasDistinctOn = false;
```
Comment (adam8157) [inline src/backend/optimizer/plan/subselect.c:1844]: What about `DISTINCT ON`? Better to have a case.

**Review by adam8157 — COMMENTED** [review]
Sure I like this no-regression one.

File: src/backend/optimizer/plan/subselect.c (hunk 1 above)
Comment (SmartKeyerror) [reply src/backend/optimizer/plan/subselect.c:1844]: Yes, there has a case in the test file that this PR added.

Comment (adam8157) [reply src/backend/optimizer/plan/subselect.c:1844]: Ah, there is one.

File: src/backend/optimizer/plan/subselect.c [hunk 2]
```diff
@@ -1824,7 +1832,13 @@ simplify_EXISTS_query(PlannerInfo *root, Query *query)
...
 	if (!query->hasAggs)
 		query->groupClause = NIL;
-	query->windowClause = NIL;
+
+	/*
+	 * Those clauses could be throwed in correlated and uncorrelated sublinks,
+	 * it will not change the correctness of the results, except windowClause.
+	 */
+	if (is_correlated)
+		query->windowClause = NIL;
```
Comment (kainwen) [inline src/backend/optimizer/plan/subselect.c:1841]: Why window agg impacts here?

Comment (SmartKeyerror) [reply src/backend/optimizer/plan/subselect.c:1841]: Because Greenplum will try to simplify the EXISTS sublink that has Window Function Node, if we just drop `windowClause` but not drop `WindowFunc` node for a window agg,  it'll cause inconsistent and error will happend.

**Review by adam8157 — APPROVED** [review]

**Comment by SmartKeyerror** [comment]
Have any other questions? If not, I will merge this.

**Review by kainwen — APPROVED** [review]

File: src/backend/optimizer/plan/subselect.c [hunk 3]
```diff
@@ -1748,6 +1748,9 @@ simplify_EXISTS_query(PlannerInfo *root, Query *query)
 		query->rowMarks)
 		return false;
 
+	bool is_correlated = contain_vars_of_level(query->jointree->quals, 1) ||
```
Comment (yaowangm) [inline src/backend/optimizer/plan/subselect.c:1751]: I suggest to add some brief explanations here about how to detect `is_correlated`. As we talked, it actually checks FROM and WHERE clauses in 1st level of the (sub) query. I understood the detailed description exists in external reference, but a brief introduction in code can help to understand the context, especially for reader without relevant knowledge.

File: src/backend/optimizer/plan/subselect.c [hunk 4]
```diff
@@ -1809,8 +1812,13 @@ simplify_EXISTS_query(PlannerInfo *root, Query *query)
 	 * change a nonzero-rows result to zero rows or vice versa.  (Furthermore,
 	 * since our parsetree representation of these clauses depends on the
 	 * targetlist, we'd better throw them away if we drop the targetlist.)
+	 *
+	 * We only throw targetlist in correlated sublinks. For uncorrelated
```
Comment (yaowangm) [inline src/backend/optimizer/plan/subselect.c:1816]: I'd suggest something like this:

We only throw targetlist in correlated sublinks because correlated sublinks will be promoted to JOIN later and targetlist will be useless then.

File: src/backend/optimizer/plan/subselect.c (hunk 2 above)
Comment (yaowangm) [reply src/backend/optimizer/plan/subselect.c:1841]: > Because Greenplum will try to simplify the EXISTS sublink that has Window Function Node, if we just drop windowClause but not drop WindowFunc node for a window agg, it'll cause inconsistent and error will happend.

As my understanding, Greenplum will simplify the EXISTS sublink with Window Function Node for correlated sublinks, just we did here to windowClause, right?

I'd suggest you add some more comments here including your answer to kainwen.

**Review by yaowangm — COMMENTED** [review]
Many thanks for your kind explanation offline. Just some minor comments and depend on your decision.

File: src/backend/optimizer/plan/subselect.c (hunk 3 above)
Comment (SmartKeyerror) [reply src/backend/optimizer/plan/subselect.c:1756]: Thanks for your suggestion, I'll add more detailed comments later.

**Review by yaowangm — APPROVED** [review]
LGTM

**Comment by SmartKeyerror** [comment]
The pipeline failed in the case which was not introduced by this PR, the other test cases are all passed, so merge it.
