### PR TITLE
Make the postgres_fdw extension work

### LINKED ISSUE #7935: unsupported frontend protocol 28675.0: server supports 1.0 to 3.0
### Greenplum version or build
latest master c30cd3ba99b46802e267f761aa616a1ba0879815

### Expected behavior
```
postgres=# select * from aa_foreign;
 a | b
---+---
 1 | 1
 1 | 2
 1 | 3
(3 rows)
```

### Actual behavior

Type command on  lastest master gpdb cluster
```
postgres=# select * from aa_foreign;
ERROR:  could not connect to server "postgres_server"
DETAIL:  FATAL:  unsupported frontend protocol 28675.0: server supports 1.0 to 3.0
```

### Step to reproduce the behavior

First create a 9_4_STABLE postgres instance

Then type following command on a  lastest master gpdb cluster
```
cd contrib/postgres_fdw/
make install
```
```
CREATE EXTENSION postgres_fdw;
CREATE SERVER postgres_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host 'localhost', port '5432', dbname 'postgres');
CREATE USER MAPPING FOR PUBLIC SERVER postgres_server OPTIONS (password '');
CREATE FOREIGN TABLE aa_foreign (a int, b int) SERVER postgres_server OPTIONS (table_name 'aa');
```

### PR DESCRIPTION
**Pull request by adam8157**
Please check the commit messages.

This PR is to make the postgres_fdw work, the major things I have done are:

1, complete the missing parts of the kernel, "Get the missing T_MergeAppend back in pathnode_walk_kids()" and "Add binary (de)serialize functions for RestrictInfo node"

2, hack the connection option GPCONN_TYPE with a new available value "pg_compatible", which makes the libpq connection to use PostgreSQL version number. (GPDB uses the high bits of the major version to indicate special internal communications at the backend, bypass the authentication, and FDW is happening at the backend), which fixed #7935

3, disable UPDATE/DELETE on foreign Greenplum servers, because UPDATE/DELETE requires
the hidden column gp_segment_id and the other "ModifyTable mixes distributed and entry-only tables" issue. However it would work fine on a foreign Postgres server.

And the things this PR hasn't done:

1, UPDATE/DELETE on foreign Greenplum servers. This extension will focus on the foreign Postgres servers.

2, pass all the postgres_fdw installcheck, I tested the functions work but I would like to defer it to next merge iteration. (to pass the installcheck, we need to either delete all UPDATE/DELETE queries or update the queries to not using loopback foreign server, they both will bring a lot of changes and make the merge work not happy)

### CODE REVIEW

**Comment by gkokolatos** [comment]
I am a bit confused here. The PostgreSQL FDW is supposed to be used for Greenplum to postgresql cases, right? Not Greenplum to Greenplum, correct?

**Comment by adam8157** [comment]
> I am a bit confused here. The PostgreSQL FDW is supposed to be used for Greenplum to postgresql cases, right? Not Greenplum to Greenplum, correct?

Yes, but it would be great also if it could connect two Greenplum master nodes.

It's not decided yet if we are going to support it officially, this PR is to make the simple queries work and fix other issues it exposes, like the MergeAppend and RestrictInfo issues.

**Comment by gkokolatos** [comment]
> 
> Yes, but it would be great also if it could connect two Greenplum master nodes.

Ok, now I understand why the tests are changed in that way. If indeed the 'ORDER BY' changes are because we are running the queries in Greenplum and order is not as stable as it is in Postgres, then I would suggest using gpdiff.pl instead, which takes care of that. If I am wrong, please ignore the suggestion.
 
> 
> It's not decided yet if we are going to support it officially, this PR is to make the simple queries work and fix other issues it exposes, like the MergeAppend and RestrictInfo issues.

I am a bit skeptical to be honest. I would love to have something that works for both, also I would love to have deviations from upstream that does not interfere too much with merging etc. How about a greenplum_fdw? Admittedly introducing a new contrib package has its own set of vulnerabilities. 

If it is supposed to support Postgres, should we test against a running Postgres instead/also? That would indeed require a deviation from upstream, though that should be mostly confined in the create server command around the connection info. And some scripts around installing/starting/stoping the foreign server. Hmm...

Anyways, thank you for your answers, they help me understand a bit better. One other question is more big picture. The query to a postgresql server is supposed to run from exactly one QE, right?

**Comment by adam8157** [comment]
@gkokolatos FDW on Greenplum supports the `mpp_execute` option, the value could be `master`, `any` or `all segments`. And I agree with you that connecting to a pure PG makes more sense.

About the postgres/greenplum_fdw, I'd like to poke @Eulerizeit , we have some options here to pass all the test queries:

1, check the foreign server, if it's a Greenplum, we take care of the `gp_segment_id`, and allow the error `ModifyTable mixes distributed and entry-only tables`. But is this unnecessary since we have another gp2gp is under development?

2, forbid modification on postgres_fdw if the server is a Greenplum. Run the tests against a pure PG or remove all UPDATE/DELETE queries from the test case.

What do you guys think?

**Comment by gkokolatos** [comment]
> @gkokolatos FDW on Greenplum supports the `mpp_execute` option, the value could be `master`, `any` or `all segments`. And I agree with you that connecting to a pure PG makes more sense.

Exactly, that is why I raised the question. I am trying to understand if all the supported options of `mpp_execute` make sense. For example if `all segments` is selected, one will get the all the results back * N of segments, no?

And just for the record, I am not against the PR, I am simply trying to understand. Thank you very much for your time and patience.

**Comment by gkokolatos** [comment]
Also for the record, I tried to play around with actually connecting to a PostgreSQL instance and run verbatim into [issue 7935](https://github.com/greenplum-db/gpdb/issues/7935).

**Comment by adam8157** [comment]
No worries, I need opinions.

FDWs run on the master by default. However, if an extension doesn't handle the `mpp_execute` option and set `mpp_execute` to `all segments`, it will get all the results back * N of segments.

Thanks for reminding me that internal protocol issue, it is on our list, I probably will take option 2 and don't test all the modification queries for now.

**Comment by Eulerizeit** [comment]
I had a chat with Georgios this morning trying to understand a bit what is being proposed. 

At a minimum the postgres_fdw needs to be able to query foreign Postgres instances. I have always assumed that would be the Greenplum master sending the query to the Postgres instance and then the data would be returned to the Greenplum master to be distributed to the appropriate segments. 

The other use case I had thought about was querying across databases within a Greenplum instance. Inthis case I imagined the segment would query data from the same segment and it would be distributed as it returns. 

The first is required. We need this to work for Postgres and then if there are any modifications outside the Postgres FDW we would want to consider that for other FDWs. (Oracle for instance)

**Comment by adam8157** [comment]
I appended two commits, which are supposed to fix #7935 and reject if the foreign server is a Greenplum on purpose, at least for now for this PR.

Not well tested yet.

**Comment by adam8157** [comment]
Confirmed this could fix #7935

**Comment by adam8157** [comment]
It's not WIP now, please review, and I updated the PR message to summary what this PR does.

**Comment by adam8157** [comment]
May I have this merged? The way I leverage connection option `GPCONN_TYPE` needs review, which is to make connections from Greenplum backends to Postgres possible.

File: src/interfaces/libpq/fe-connect.c [hunk 1]
```diff
@@ -1644,12 +1644,21 @@ connectDBStart(PGconn *conn)
 	conn->addrlist = addrs;
 	conn->addr_cur = addrs;
 	conn->addrlist_family = hint.ai_family;
+	if (conn->gpconntype && strcmp(conn->gpconntype, "pg_compatible") == 0)
```
Comment (hlinnaka) [inline src/interfaces/libpq/fe-connect.c]: I'd like to turn this logic on its head, so that you get a normal libpq connection by default, and you have to ask specifically for the QD-QE mode. That way, any other extension that uses libpq will also get the normal libpq mode without changes. (What about contrib/dblink?)

Maybe also better to have a special `PQconnectStartParamsToQE()` function, instead of making this available as a libpq option. Otherwise, you could still use dblink or postgres_fdw to connect in QE mode by supplying the special argument as an option. That would feel good from a security point of view. You're on shaky ground already if an untrusted user can create libpq connections with arbitrary options, but still.

File: contrib/postgres_fdw/postgres_fdw.c [hunk 2]
```diff
@@ -2041,8 +2042,19 @@ postgresIsForeignRelUpdatable(Relation rel)
...
+	if (!updatable)
+		return 0;
+
+	/*
+	 * Greenplum only supports INSERT, because UPDATE/DELETE SELECT requires
+	 * the hidden column gp_segment_id and the other "ModifyTable mixes
+	 * distributed and entry-only tables" issue.
+	 */
+	UserMapping *user = GetUserMapping(rel->rd_rel->relowner, table->serverid);
+	if (greenplumCheckIsGreenplum(user))
```
Comment (hlinnaka) [inline contrib/postgres_fdw/postgres_fdw.c]: This opens a connection to the server. That's a bit of a surprising side-effect. Maybe it would be better to allow UPDATE and DELETE here, but check and error out at execution time.

Comment (adam8157) [reply contrib/postgres_fdw/postgres_fdw.c]: postgres_fdw's `GetConnection()` reuses the libpq connections, and `IsForeignRelUpdatable` runs at the execution time, it should be fine, will double check.

File: src/interfaces/libpq/fe-connect.c (hunk 1 above)
Comment (adam8157) [reply src/interfaces/libpq/fe-connect.c]: Sounds great, thanks! Will look into it.

Comment (adam8157) [reply src/interfaces/libpq/fe-connect.c]: Confirmed dblink has the same issue, I'm thinking the trade-off.

Listing the Cons:
Current solution: need to change every extension's code, however they are only dblink and postgres_fdw for now.
Doing it the opposite way: it would be too easy to start an internal connection, but it's the same easy for hackers.
Special functions: we have six functions starting libpq connections, at least QE, FTS, fault injector and WAL use four different ones.

I'm trying to figure out a better way, but for now, the current solution looks better?

Comment (adam8157) [reply src/interfaces/libpq/fe-connect.c]: Hi, @hlinnaka I made the PG version default and GP version needs an extra param. However, I didn't duplicate the functions, since there are six and Greenplum uses four of them(And we might refactor the internal libpq in near future). How does it look now?

**Comment by adam8157** [comment]
Confirmed this fixes #4148 too.

File: src/interfaces/libpq/fe-connect.c (hunk 1 above)
Comment (hlinnaka) [reply src/interfaces/libpq/fe-connect.c]: > Hi, @hlinnaka I made the PG version default and GP version needs an extra param. However, I didn't duplicate the functions, since there are six and Greenplum uses four of them(And we might refactor the internal libpq in near future). How does it look now?

Hmm. I can see PQconnect*() variants being used in the backend that would need to be duplicated:

```
src/backend/fts/ftsprobe.c:     ftsInfo->conn = PQconnectStart(conninfo);
src/backend/replication/libpqwalreceiver/libpqwalreceiver.c:    streamConn = PQconnectdbParams(keys, vals, /* expand_dbname = */ true);
src/backend/cdb/dispatcher/cdbconn.c:   segdbDesc->conn = PQconnectStartParams(keywords, values, false);
```

What is the fourth one that I'm missing? There is PQconnectPoll(), but that's used together with PQconnectStart(), I don't think that needs to be changed.

Of these, I think the PQconnecStart() call in ftsprobe.c could easily be refactored to use PQconnectStartParams() instead.

> (And we might refactor the internal libpq in near future)

What do you have in mind there?

Comment (adam8157) [reply src/interfaces/libpq/fe-connect.c]: fault injector uses PQconnectdb().

I'm thinking of having a try to enable the authentication in internal connections. We have stories saying it's a security issue, and it would be nice if `postgres_fdw` could connect to a remote Postgres safely.

**Comment by adam8157** [comment]
If no objection, I will merge this PR.

File: src/test/walrep/expected/walreceiver.out [hunk 3]
```diff
@@ -1,8 +1,8 @@
 -- negative cases
 SELECT test_receive();
-ERROR:  could not receive data from WAL stream: connection pointer is NULL (libpqwalreceiver.c:628)
+ERROR:  could not receive data from WAL stream: connection pointer is NULL (libpqwalreceiver.c:631)
```
Comment (yydzero) [inline src/test/walrep/expected/walreceiver.out:3]: better to use init to ignore line number changes.

File: contrib/postgres_fdw/connection.c [hunk 4]
```diff
@@ -729,17 +729,12 @@ pgfdw_xact_callback(XactEvent event, void *arg)
...
-					 * read-only cases.  Note that the error will cause us to
-					 * come right back here with event == XACT_EVENT_ABORT, so
-					 * we'll clean up the connection state at that point.
+					 * FDW update is not the same as Greenplum segments update,
+					 * doesn't need the two-phase commit.
+					 *
+					 * Besides that, Greenplum prepares on many cases including
+					 * DTX distributing for MPP usages, just break here.
 					 */
-					ereport(ERROR,
```
Comment (yydzero) [inline contrib/postgres_fdw/connection.c:740]: Does this means postgres_fdw does not support update/delete when connecting from Greenplum to Greenplum?

Comment (adam8157) [reply contrib/postgres_fdw/connection.c:740]: It doesn't for now, but not because of the code here.

The changes here are just because Greenplum does lots of prepares, but postgres_fdw thinks it's not reasonable on the standalone Postgres.
