### PR TITLE
Fix memory leak in GpPolicyFetch() called in RelationBuildDesc()

### LINKED ISSUE #11244: Memory leak in GpPolicyFetch() called in RelationBuildDesc() when the table is an external table
### Greenplum version or build

```
PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.14108.g57d5181d5d build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 6.5.1 20190307 (Alibaba 6.5.1-1 2.17), 64-bit compiled on Dec  3 2020 21:51:34 (with assert checking)
```

### Step to reproduce the behavior

```
createdb tmp
nohup pgbench -c 1 -j 1 -f test.sql -n -T 3600000 tmp >/dev/null 2>&1 &
nohup pidstat -p ${QDPID} -r 1 >${QDPID}.pidstat.log 2>&1 &
```

The content of test.sql is:

```sql
select * from gp_toolkit.__gp_log_master_ext limit 1;
```

image

```
$ gcore ${QDPID}
$ strings core.${QDPID} | sort | uniq -c | sort -nr | head -n 16
1715633 encoding
1715626 command
1715625 quote
1715625 null
1715625 format
1715625 escape
1715625 delimiter
1715624 MASTER_ONLY
1715624 log_errors
1715624 is_writable
1715624 format_type
1715624 false
1715624 execute_on
1715624 cat $GP_SEG_DATADIR/log/*.csv
   2832 UTF-8
    841 ISO-8859-1
```

### Root Cause

`ExtTableEntry *e` is allocated in CacheMemoryContext that will **never** be reset or deleted.

```c
// RelationBuildDesc
if ((relation->rd_rel->relkind == RELKIND_RELATION && !IsSystemRelation(relation)) ||
    relation->rd_rel->relkind == RELKIND_PARTITIONED_TABLE ||
    relation->rd_rel->relkind == RELKIND_FOREIGN_TABLE ||
    relation->rd_rel->relkind == RELKIND_MATVIEW)
{
    MemoryContext oldcontext = MemoryContextSwitchTo(CacheMemoryContext);
    relation->rd_cdbpolicy = GpPolicyFetch(targetRelId);
    MemoryContextSwitchTo(oldcontext);
}
```

```c
GpPolicy *
GpPolicyFetch(Oid tbloid)
{
    if (rel_is_external_table(tbloid))
    {
        ExtTableEntry *e = GetExtTableEntryIfExists(tbloid);
```

### PR DESCRIPTION
**Pull request by hidva**
when the table is an external table.

Fix #11244

### CODE REVIEW

File: src/backend/utils/cache/relcache.c [hunk 1]
```diff
@@ -1261,8 +1261,16 @@ RelationBuildDesc(Oid targetRelId, bool insertIt)
 		relation->rd_rel->relkind == RELKIND_FOREIGN_TABLE ||
 		relation->rd_rel->relkind == RELKIND_MATVIEW)
 	{
+		/*
+		 * There are many memory allocations in GpPolicyFetch(), especially 
+		 * when targetRelId is a foreign table. These allocations are not bound to RelationData, 
+		 * so they cannot be freed during RelationDestroyRelation(),
+		 * that is, these allocations will never be freed.
+		 */
+		Assert(CurrentMemoryContext != CacheMemoryContext);
```
Comment (paul-guo-) [inline src/backend/utils/cache/relcache.c:1270]: Curious why does the below code previously use CacheMemoryContext instead of CurrentMemoryContext?

Comment (zhangh43) [reply src/backend/utils/cache/relcache.c:1270]: I think choose CacheMemoryContext here is due to relcache is long existing(not per transaction)

**Review by zhangh43 — APPROVED** [review]
LGTM

File: src/backend/utils/cache/relcache.c (hunk 1 above)
Comment (hidva) [reply src/backend/utils/cache/relcache.c:1270]: I don't know why the original code chooses CacheMemoryContext here. In PG, all objects allocated in CacheMemoryContext must be released in RelationDestroyRelation() to avoid a memory leak.
