### PR TITLE
Fix ORCA producing incorrect plan when handling SEMI join with RANDOM distributed table

### LINKED ISSUE #16611: SQL using EXIST may get wrong results with ORCA
## Bug Report
When the ORCA optimizer is enabled, queries that use EXIST may produce incorrect results, returning duplicate and excessive rows. We have currently observed this issue only when working with random tables.

### Greenplum version or build
7X and 6X

### Expected behavior
A simple step to reproduce the behavior with demo cluster:

```
create table table_left (l1 int, l2 int) distributed by (l1);
create table table_right (r1 int, r2 int) distributed randomly;
create index table_right_idx on table_right(r1);

insert into table_left  values (1,1);
insert into table_right select i, i from generate_series(1, 100000) i;
insert into table_right values  (1,1), (1,1), (1,1) ; 

analyze table_left;
analyze table_right;

explain select * from table_left where  exists (select 1  from table_right where l1 = r1);
select * from table_left where  exists (select 1  from table_right where l1 = r1);
```

We expect that only returns 1 row in this case.

### Actual behavior
2 or 3 rows may return

### PR DESCRIPTION
**Pull request by wuyuhao28**
When ORCA transforms a SEMI join to an INNER join, a LogicalGbAgg is introduced in the inner side of the INNER join to remove duplicate inner keys. Subsequently, this join is attempted to be transformed into a LogicalIndexApply. ORCA determines if this transformation can be done by checking if the inner side's grouping columns contain all distribution columns.

However, when the inner side's distribution columns come from a RANDOM table, the checking always evaluates to true and allows the transform to proceed. But RANDOM distribution cannot satisfy this transformation because the same 'distribution' key may appear in different segments.

This commit resolves the issue by adding a check for the size of RANDOM distribution columns and forbidding the illegal transform.

Fix #16611

### CODE REVIEW

File: src/test/regress/sql/subselect_gp2.sql [hunk 1]
```diff
@@ -74,6 +74,29 @@ INSERT INTO subselect2_bar VALUES (1,1);
...
+--
+create table table_left (l1 int, l2 int) distributed by (l1);
+create table table_right (r1 int, r2 int) distributed randomly;
+create index table_right_idx on table_right(r1);
+insert into table_left values (1,1);
+insert into table_right select i, i from generate_series(1, 100000) i;
+insert into table_right select 1, 1 from generate_series(1, 100) i;
+
+--- make sure the same value (1,1) rows are inserted into different segments
+select distinct gp_segment_id from table_right where r1 = 1;
```
Comment (dgkimura) [inline src/test/regress/sql/subselect_gp2.sql:89]: Are we guaranteed that the value (1,1) will always insert on each segment?  I think this approach relies on the implementation of random insert.  Alternatively, it may be more reliable to do that in an isolation2 test with syntax like:

```sql
0U: insert into table_right (1, 1);
1U: insert into table_right (1, 1);
2U: insert into table_right (1, 1);
```

**Review by dgkimura — COMMENTED** [review]
Nice find!  Fix looks reasonable to me.

File: src/test/regress/sql/subselect_gp2.sql (hunk 1 above)
Comment (wuyuhao28) [reply src/test/regress/sql/subselect_gp2.sql:89]: It relies on the Motion Sender random distribute, using _random() % numsegs_  in _cdbhashrandomseg()_,  and I've done some test that insert 100 rows will insert (1,1) to each segments, we can also insert more rows to guarantee that.
So isolation2 test with syntax will make it ? Let me do test test.

**Comment by pobbatihari** [comment]
Code changes Looks good to me.
Would you mind updating the code by running a clang-format check on it?

**Comment by pobbatihari** [comment]
I've observed that the planner produces different plan outputs for the newly added test scenarios, which could potentially break the pipeline. So could you please relocate the test cases to a subselect_gp.sql and update corresponding ouptut files.

**Comment by wuyuhao28** [comment]
> I've observed that the planner produces different plan outputs for the newly added test scenarios, which could potentially break the pipeline. So could you please relocate the test cases to a subselect_gp.sql and update corresponding ouptut files.

OK, format has checked, test case is moved to subselect_gp and Planner version's output is also added.

**Comment by pobbatihari** [comment]
Could you make the necessary updates to address any ctest failures, if they exist?
How to run ctest:
https://github.com/greenplum-db/gpdb/blob/main/src/backend/gporca/README.md

**Comment by wuyuhao28** [comment]
> Could you make the necessary updates to address any ctest failures, if they exist? How to run ctest: https://github.com/greenplum-db/gpdb/blob/main/src/backend/gporca/README.md

Sorry, it's my first time contribute to ORCA. I've done ctest and one test fail in _gporca_test_CSubqueryTest_:
```
2023-10-19 17:03:33:945911 CST,THD000,TRACE,"IsRunning test with EXHAUSTIVE SEARCH:",
2023-10-19 17:03:33:946063 CST,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/UnnestSQJoins.mdp",
2023-10-19 17:03:33:952775 CST,THD000,TRACE,"opening file ../data/dxl/minidump/UnnestSQJoins.mdp",
2023-10-19 17:03:33:961451 CST,THD000,TRACE,"executing ../data/dxl/minidump/UnnestSQJoins.mdp",
2023-10-19 17:03:33:961461 CST,THD000,TRACE,"parsing DXL File ../data/dxl/minidump/UnnestSQJoins.mdp",
2023-10-19 17:03:34:436934 CST,THD000,TRACE,"[OPT]: Number of plan alternatives: 49774
",
2023-10-19 17:03:34:443643 CST,THD000,TRACE,"timer:Minidump: 475ms",
2023-10-19 17:03:34:445103 CST,THD000,TRACE,"Plan space size comparison *** FAILED ***
Required comparison: 0
	Actual size: 49774
	Expected size: 51358
```

I think the reason is that this commit forbid some transform, the join space size is smaller now. After change space size in mdp,  Ctest all pass.

File: src/test/regress/sql/subselect_gp.sql [hunk 2]
```diff
@@ -1350,3 +1350,30 @@ explain (COSTS OFF) with t0 AS (
         JOIN s as t ON  true
    )
 SELECT c FROM t0;
+
+--
+-- Test case for ORCA semi join with random table
+-- See https://github.com/greenplum-db/gpdb/issues/16611
+--
+create table table_left (l1 int, l2 int) distributed by (l1);
+create table table_right (r1 int, r2 int) distributed randomly;
```
Comment (gpopt) [inline src/test/regress/sql/subselect_gp.sql:1359]: Can we have a test case where the table_right is a randomly distributed partition table that is partitioned by r1?

**Comment by wuyuhao28** [comment]
This PR should random distribute

**Comment by wuyuhao28** [comment]
_distributionCols_ size of replicated table will also be 0, but I think we should not forbid this transform because group agg with replicated table on one segment can satisfy SEMI join transform, and ORCA can produce correct plan now.

I've also add checking work for _EopLogicalDynamicGet_ of partition table, and tests case for these related cases. ctest has also checked.

File: src/test/regress/sql/subselect_gp.sql [hunk 3]
```diff
@@ -1350,3 +1350,49 @@ explain (COSTS OFF) with t0 AS (
...
+explain (costs off) select * from table_left where exists (select 1 from table_right where l1 = r1);
+select * from table_left where exists (select 1 from table_right where l1 = r1);
+explain (costs off) select * from table_left where l1 in (select r1 from table_right where l1 = r1);
+select * from table_left where exists (select 1 from table_right where l1 = r1);
+
+--- case for partition table with random distribute
+drop table table_right;
+create table table_right (r1 int, r2 int) distributed randomly partition by range (r1) ( start (0) end (100000) every (10000));
+create index table_right_idx on table_right(r1);
+insert into table_right select i, i from generate_series(1, 99999) i;
```
Comment (gpopt) [inline src/test/regress/sql/subselect_gp.sql:1388]: Is it possible to reduce the number of rows to less than 1000? as well as the partition number to be <= 3?

File: src/test/regress/expected/subselect_gp.out [hunk 4]
```diff
@@ -3482,3 +3482,180 @@ SELECT c FROM t0;
...
+--
+--- case for random distribute 
+create table table_left (l1 int, l2 int) distributed by (l1);
+create table table_right (r1 int, r2 int) distributed randomly;
+create index table_right_idx on table_right(r1);
+insert into table_left values (1,1);
+insert into table_right select i, i from generate_series(1, 300) i;
+insert into table_right select 1, 1 from generate_series(1, 100) i;
+--- make sure the same value (1,1) rows are inserted into different segments
+select distinct gp_segment_id from table_right where r1 = 1;
```
Comment (gpopt) [inline src/test/regress/expected/subselect_gp.out:3497]: Can we change the query to 
```sql
select count(distinct gp_segment_id) > 1 from table_right where r1 = 1;
```

So that the test is independent of number of segments.

File: src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp [hunk 5]
```diff
@@ -284,6 +287,16 @@ CXformJoin2IndexApplyGeneric::Transform(CXformContext *pxfctxt,
...
 				distributionCols = popDynamicGet->PcrsDist();
 				pexprGet = pexprCurrInnerChild;
+
+				if (nullptr != groupingColsToCheck.Value() &&
+					(!groupingColsToCheck->ContainsAll(distributionCols) ||
+					 ptabdescInner->GetRelDistribution() ==
+						 IMDRelation::EreldistrRandom))
+				{
+					// the grouping columns are not a superset of the distribution columns,
+					// or distribution columns is empty when random distribute
```
Comment (gpopt) [inline src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp:297]: distribution columns are empty when the table is randomly distributed.

Comment (gpopt) [reply src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp:297]: same with the other comment.

**Review by gpopt — APPROVED** [review]
+1
Thanks for the contribution!

**Review by pobbatihari — APPROVED** [review]
+1

**Comment by wuyuhao28** [comment]
> Hi @wuyuhao28, Can you please ensure that all comments in the pull request are addressed

Yes, I've checked all comments. Please remind me if there're any problems.

**Comment by gpopt** [comment]
@wuyuhao28 Can you also open a PR for 6X_STABLE? Thanks!

**Comment by wuyuhao28** [comment]
> @wuyuhao28 Can you also open a PR for 6X_STABLE? Thanks!

OK，I will open a PR soon
