### PR TITLE
Release locks when exiting from FileRepPrimary_IsMirroringRequired()

### LINKED ISSUE #1791: cs-fts:  gprecoverseg get stuck waiting on virtual xact lock
cs-fts pipeline get failed intermittently recently, the failed case is 
```
FtsTransitionsPart03.test_primary_resync_postmaster_reset_with_faults_test_37_primary_resync_system_failover
```
The case basically doing bellow steps:
```
gpfaultinjector  -f all -m async -y reset  -H ALL -r primary_mirror
gpfaultinjector  -f filerep_resync -m async -y reset -H ALL -r primary
gpfaultinjector  -f filerep_consumer -m async -y reset -H ALL -r primary
gpfaultinjector  -f filerep_consumer -m async -y fault  -H ALL -r primary
psql -f ./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/fts/fts_transitions/test_ddl.sql
gpfaultinjector  -f filerep_resync -m async -y suspend  -H ALL -r primary
gprecoverseg -a
gpfaultinjector  -f filerep_resync_worker_read -m async -y fault  -H ALL -r primary
gpfaultinjector  -f filerep_resync -m async -y resume  -H ALL -r primary
psql -f ./src/test/tinc/tincrepo/mpp/gpdb/tests/storage/fts/fts_transitions/test_ddl.sql
gpstate -s
gprecoverseg -a
gprecoverseg -a 
```
The last two "gprecoverseg" commands may get stuck for 10 mins and finally report a error.

The reason is when doing gprecoverseg, a QE get stuck with bellow backtrace:
```
:38]  
`#0  0x00007fc6e89624e7 in semop () from /lib64/libc.so.6
#1  0x00000000007c5674 in PGSemaphoreLock (
    sema=0x7fc6dcbdfbc0,
    interruptOK=interruptOK@entry=1 '\001') at pg_sema.c:433
#2  0x0000000000834041 in ProcSleep (
    locallock=locallock@entry=0x16989b8,
    lockMethodTable=lockMethodTable@entry=0xc7a900 <default_lockmethod>) at proc.c:1094
#3  0x000000000082df5b in WaitOnLock (
    locallock=locallock@entry=0x16989b8,
    owner=owner@entry=0x168c048) at lock.c:1315
#4  0x000000000082f161 in LockAcquire (
    locktag=locktag@entry=0x7fff0f28c020,
    lockmode=lockmode@entry=7,
    sessionLock=sessionLock@entry=0 '\000',
    dontWait=dontWait@entry=0 '\000') at lock.c:913
#5  0x000000000082da8c in VirtualXactLockTableInsert (
    vxid=..., vxid@entry=...) at lmgr.c:656
#6  0x00000000004eeb89 in StartTransaction () at xact.c:3249
#7  0x00000000004f0275 in StartTransactionCommand ()
    at xact.c:4196
#8  0x000000000097d5e6 in InitPostgres (
    in_dbname=0x15fa550 "template1", dboid=dboid@entry=0,
    username=username@entry=0x15fa510 "gpadmin",
    out_dbname=out_dbname@entry=0x0) at postinit.c:674
#9  0x0000000000846bb0 in PostgresMain (argc=1,
    argv=argv@entry=0x15fa5f0, dbname=0x15fa550 "template1",
    username=0x15fa510 "gpadmin") at postgres.c:4618
#10 0x00000000007dcf56 in BackendRun (port=0x160a880)`
```

I checked the proclock and found the proc holding it has already exited, by adding some debug info, it looks like be "primary resync worker #1 process" that acquired the lock and did not release it, those are all i get so far, @ashwinstar @asimrp.

### PR DESCRIPTION
**Pull request by asubramanya**
Commit d09cf2e6424470c3651365df133fcf4177a48871 introduced proc_exit(0) based
on the check that postmaster is not alive and the segment is at fault. The
check for postmaster being alive is incorrect when passed true for
`PostmasterIsAlive()` in case of resync worker as resync workers are not direct
children on postmaster. Because of the incorrect check proc_exit(0) is called
always for resync worker when segment is in fault. Also, the locks are not
released while exiting which might cause other backends `StartTransaction()` to
hang due to virtual xact lock.

Fixes #1791

### CODE REVIEW

**Comment by asubramanya** [comment]
Thanks for the review.

File: src/backend/cdb/cdbfilerepprimary.c [hunk 1]
```diff
@@ -269,8 +269,15 @@ FileRepPrimary_IsMirroringRequired(
...
 					}
 
-					if (!PostmasterIsAlive(true))
+					/*
+					 * This code path can be reached from backends which are
+					 * not directly spawned from PostMaster.  For e.g the
+					 * FileRepResyncWorker process is spawned by FileRepMain.
+					 * Hence PostmasterIsAlive() needs to be called with false.
+					 */
+					if (!PostmasterIsAlive(false))
```
Comment (pengzhout) [inline src/backend/cdb/cdbfilerepprimary.c]: Ah, didn't realize that this function is also called by resync workers

File: src/backend/cdb/cdbfilerepprimary.c [hunk 2]
```diff
@@ -269,8 +269,15 @@ FileRepPrimary_IsMirroringRequired(
...
 					{
+						LockReleaseAll(DEFAULT_LOCKMETHOD, false);
```
Comment (pengzhout) [inline src/backend/cdb/cdbfilerepprimary.c]: should we also release table locks in line 242?
