### PR TITLE
Fix memory leaks and spilling issues of hash aggregation

### LINKED ISSUE #7787: Possible memory leak when running hashagg
There are 3 possible problems:

#### 2. After using serial/deserial/combine function for multi-phase aggregation, then there are some changes:
 * instead of using type byte(oid=17), new hashagg uses internal type(oid=2281, INTERNALOID) for passing value between process
 * combine function such as `numeric_avg_combine` will work on a internal type transValue, maybe create a new one if last one is NULL

Then, with these changes, following step may cause memory leak:
 1. run combine functions multiple time, create a lot of internal type values
 2. no room for new one, then `spill_hash_table` write these internal type values to disk
 3. goto step 1 for rest tuples

These steps will cause memory leak because the internal type is special: it stores data in memory (`aggcontext`), but set `typeByVal` to `true` in `pg_type`. It looks like a "ByValue" type as long as the related memory context exist. Then, the "hybrid hash" table treats it as "ByValue" type, `spill_hash_table` writes it's value (actually the pointer for "real" data) to file, then, combine function create a new one because last value is cleared to NULL after spilling. All "real" data is always in `aggcontext`.

Possible fix: use serial/deserial function in "hybrid hash" table for spilling, write the "real" data, free it's memory.

### PR DESCRIPTION
**Pull request by adam8157**
Fix #7787 and #7984 

PR #5528 changed the transValue of aggstate to type INTERNAL, which are pointers with data allocated in aggcontext. It has two issues causing OOM and memory leaks.

1, just the pointers of aggstates are spilled, doesn't decrease the memory usage.
2, aggstates are not in the group_buf now, but Greenplum decides if to spill based on the usage of group_buf.

This PR fixes these two issues via using group_buf for aggregate transition data and serialize them while spilling hash table.

### CODE REVIEW

File: src/backend/executor/nodeAgg.c [hunk 1]
```diff
@@ -613,7 +611,9 @@ advance_aggregates(AggState *aggstate, AggStatePerGroup pergroup)
 			 * deserialfn_oid will be set if we must deserialize the input state
 			 * before calling the combine function
 			 */
-			if (OidIsValid(peraggstate->deserialfn_oid))
+			if (OidIsValid(peraggstate->deserialfn_oid) &&
```
Comment (berlin-ab) [inline src/backend/executor/nodeAgg.c]: There's duplication between this conditional and the one on 928. Is there some higher-level abstraction missing there?

File: src/backend/executor/nodeAgg.c [hunk 2]
```diff
@@ -2249,17 +2249,21 @@ ExecInitAgg(Agg *node, EState *estate, int eflags)
...
 			/* Likewise for deserialization functions */
 			if (aggref->aggstage == AGGSTAGE_INTERMEDIATE ||
 				aggref->aggstage == AGGSTAGE_FINAL)
 			{
 				if (!OidIsValid(aggform->aggdeserialfn))
 					elog(ERROR, "deserialfunc not provided for deserialization aggregation");
-				peraggstate->deserialfn_oid = aggform->aggdeserialfn;
 			}
+
+			if (OidIsValid(aggform->aggdeserialfn))
```
Comment (berlin-ab) [inline src/backend/executor/nodeAgg.c]: It seems weird that we keep checking to make sure these functions are valid. Couldn't we do some setup work early on and ensure these are set?

File: src/backend/utils/adt/numeric.c [hunk 3]
```diff
@@ -2870,13 +2873,23 @@ makeNumericAggState(FunctionCallInfo fcinfo, bool calcSumX2)
...
+	int agg_type;
 
-	if (!AggCheckCallContext(fcinfo, &agg_context))
+	if (!(agg_type = AggCheckCallContext(fcinfo, &agg_context)))
 		elog(ERROR, "aggregate function called in non-aggregate context");
 
 	old_context = MemoryContextSwitchTo(agg_context);
 
-	state = (NumericAggState *) palloc0(sizeof(NumericAggState));
+	AggState *aggstate = (AggState *)fcinfo->context;
```
Comment (berlin-ab) [inline src/backend/utils/adt/numeric.c]: Can we factor out the duplication between here and 3557?

File: src/backend/executor/execHHashagg.c [hunk 4]
```diff
@@ -207,14 +207,20 @@ calc_hash_value(AggState* aggstate, TupleTableSlot *inputslot)
  */
 static inline void
 adjustInputGroup(AggState *aggstate, 
-				 void *input_group)
+				 void *input_group,
```
Comment (berlin-ab) [inline src/backend/executor/execHHashagg.c]: It looks like this is a Greenplum-only function, therefore it would be nice to break this function down into two. One that is for temporary and one that is not, rather than take this new flag. It will probably require extracting reusable functions for the two implementations.

**Comment by bhuvnesh2703** [comment]
Do we already had the tests which go through the code path touched in this comment (if , else if condition), if yes, great, if not, could we add them?

File: src/backend/executor/nodeAgg.c (hunk 1 above)
Comment (adam8157) [reply src/backend/executor/nodeAgg.c]: Here is deserial, the other is serial.

Because I set their oid now no matter what the stage they are, doing serialization or deserialization needs to check the stage.

File: src/backend/executor/nodeAgg.c (hunk 2 above)
Comment (adam8157) [reply src/backend/executor/nodeAgg.c]: Here is the init function. The logic from PG as my understanding is: `serialfn` and `deserialfn` are set when it has the functions, `serialfn_oid` or `deserialfn_oid` is set when it needs to.

**Comment by adam8157** [comment]
TPC-DS covers this, and we have a hashagg_spill test case of ICW, will add a case with numeric type to cover it, thanks for the notice.

File: src/backend/executor/execHHashagg.c [hunk 5]
```diff
@@ -226,11 +228,45 @@ adjustInputGroup(AggState *aggstate,
...
+			if (temporary)
+				oldContext = MemoryContextSwitchTo(aggstate->tmpcontext->ecxt_per_tuple_memory);
+
+			pergroupstate->transValue = FunctionCallInvoke(dsinfo);
+
+			if (temporary)
+				MemoryContextSwitchTo(oldContext);
+
+			datum_size = datumGetSize(pergroupstate->transValue, false, -1);
+			Assert(MAXALIGN(datum_size) - datum_size <= MAXIMUM_ALIGNOF);
```
Comment (asimrp) [inline src/backend/executor/execHHashagg.c]: What is the purpose of this assert?  Looking at `MAXALIGN` definition, this expression appears to be always true.

Comment (adam8157) [reply src/backend/executor/execHHashagg.c]: I agree, copied that line from the existing process:)

Comment (jianlirong) [reply src/backend/executor/execHHashagg.c]: I think there is a typo error here. Instead of:

```C
datum_size = datumGetSize(pergroupstate->transValue, byteaTranstypeByVal, byteaTranstypeLen);
```
we should use the serialized value to calculate the size of the datum, rather the deserialized value:

```C
datum_size = datumGetSize(PointerGetDatum(datum), byteaTranstypeByVal, byteaTranstypeLen);
```
This is consistent with the logic of writeHashEntry.

Comment (adam8157) [reply src/backend/executor/execHHashagg.c]: You are right, great thanks.

File: src/test/regress/expected/workfile/hashagg_spill.out [hunk 6]
```diff
@@ -89,6 +89,16 @@ create table aggspill (i int, j int, t text) distributed by (i);
 insert into aggspill select i, i*2, i::text from generate_series(1, 10000) i;
 insert into aggspill select i, i*2, i::text from generate_series(1, 100000) i;
 insert into aggspill select i, i*2, i::text from generate_series(1, 1000000) i;
+drop table if exists aggspill_numeric;
+create table aggspill_numeric (i numeric, j numeric, t text) distributed by (i);
```
Comment (hlinnaka) [inline src/test/regress/expected/workfile/hashagg_spill.out]: Please add a comment to explain why testing with numeric is different from testing with text. (Because the transition type of numeric is internal, and hence it uses the serial/deserial functions when spilling)

File: src/backend/executor/nodeAgg.c [hunk 7]
```diff
@@ -927,7 +925,9 @@ finalize_aggregate(AggState *aggstate,
 	 * serialfn_oid will be set if we must serialize the transvalue before
 	 * returning it
 	 */
-	else if (OidIsValid(peraggstate->serialfn_oid))
+	else if (OidIsValid(peraggstate->serialfn_oid) &&
+			 (peraggstate->aggref->aggstage == AGGSTAGE_INTERMEDIATE ||
```
Comment (hlinnaka) [inline src/backend/executor/nodeAgg.c]: Why is this change needed? The initialization code in ExecInitAgg() should only set seriafn_oid, when aggstage is INTERMEDIATE or PARTIAL. The idea is that ExecInitAgg() figures out whether serialization is needed or not, and only sets serialfn_oid if it's needed.

File: src/backend/executor/execHHashagg.c [hunk 8]
```diff
@@ -1490,6 +1501,9 @@ spill_hash_table(AggState *aggstate)
 	/* Reset the buffer */
 	mpool_reset(hashtable->group_buf);
 
+	/* Reset serialization context */
+	MemoryContextReset(hashtable->serialization_cxt);
```
Comment (melanieplageman) [inline src/backend/executor/execHHashagg.c]: Even though `mpool_reset` is a thin wrapper around `MemoryContextReset`, what is the logic behind using `MemoryContextReset` itself here (as opposed to using `mpool_reset`)? do you not want to call `mpool_init`? Why does that differ for `group_buf` vs `serialization_cxt`?

File: src/backend/executor/execHHashagg.c [hunk 9]
```diff
@@ -226,11 +232,45 @@ adjustInputGroup(AggState *aggstate,
 	{
 		AggStatePerAgg peraggstate = &peragg[aggno];
 		AggStatePerGroup pergroupstate = &pergroup[aggno];
-		
-		if (!peraggstate->transtypeByVal &&
-			!pergroupstate->transValueIsNull)
+
+		/* Deserialize the aggregate states loaded from the spill file */
+		if (OidIsValid(peraggstate->deserialfn_oid) && !pergroupstate->transValueIsNull)
```
Comment (melanieplageman) [inline src/backend/executor/execHHashagg.c]: Since it seems like you don't want to do any of this if `pergroupstate->transValueIsNull` is true, can you have that as a separate `if` condition first and early exit? It would make this less confusing.

File: src/backend/executor/execHHashagg.c [hunk 10]
```diff
@@ -226,11 +232,45 @@ adjustInputGroup(AggState *aggstate,
...
+			dsinfo->arg[0] = PointerGetDatum(datum);
+			dsinfo->argnull[0] = pergroupstate->transValueIsNull;
+			/* Dummy second argument for type-safety reasons */
+			dsinfo->arg[1] = PointerGetDatum(NULL);
+			dsinfo->argnull[1] = false;
+
+			/*
+			 * We run the deserialization functions in per-input-tuple
+			 * memory context if it's useless after combined.
+			 */
```
Comment (melanieplageman) [inline src/backend/executor/execHHashagg.c]: So, more detail about this would be great. I'm not sure exactly what 'useless after combined' means. Could you add more details, either here or at the call sites to explain the memory context that it is being called in and why, for `agg_hash_reload` you want to run the deserialization functions in per-input-tuple memory context whereas when making the initial hashagg entry for the group you want to run the deserialization functions in a different context?

File: src/backend/executor/nodeAgg.c [hunk 11]
```diff
@@ -2249,17 +2249,21 @@ ExecInitAgg(Agg *node, EState *estate, int eflags)
 			{
 				if (!OidIsValid(aggform->aggserialfn))
 					elog(ERROR, "serialfunc not provided for serialization aggregation");
-				peraggstate->serialfn_oid = aggform->aggserialfn;
 			}
 
+			if (OidIsValid(aggform->aggserialfn))
```
Comment (melanieplageman) [inline src/backend/executor/nodeAgg.c]: Why was this moved outside of the above `if` statement?

File: src/test/regress/expected/workfile/hashagg_spill.out [hunk 12]
```diff
@@ -112,6 +122,18 @@ select count(*) from (select i, count(*) from aggspill group by i,j having count
  90000
 (1 row)
 
+select count(*) from (select i, count(*) from aggspill_numeric group by i,j having count(*) = 2) g;
```
Comment (melanieplageman) [inline src/test/regress/expected/workfile/hashagg_spill.out]: What is this testing? It doesn't seem to exercise most of the new code added.

File: src/test/regress/sql/workfile/hashagg_spill.sql [hunk 13]
```diff
@@ -83,6 +95,8 @@ set statement_mem = '10MB';
 select overflows >= 1 from hashagg_spill.num_hashagg_overflows('explain analyze
 select count(*) from (select i, count(*) from aggspill group by i,j having count(*) = 2) g') overflows;
 select count(*) from (select i, count(*) from aggspill group by i,j having count(*) = 2) g;
+select count(*) from (select i, count(*) from aggspill_numeric group by i,j having count(*) = 2) g;
```
Comment (melanieplageman) [inline src/test/regress/sql/workfile/hashagg_spill.sql]: So, I tried these tests on the patched code and wasn't exercising most of the new code added. Is it meant to?

File: src/test/regress/sql/workfile/hashagg_spill.sql [hunk 14]
```diff
@@ -83,6 +95,8 @@ set statement_mem = '10MB';
...
+select count(*) from (select a, avg(b), avg(c) from aggspill_avg group by a) g;
```
Comment (melanieplageman) [inline src/test/regress/sql/workfile/hashagg_spill.sql]: This one was exercising the new code -- could you add a bit more details about what the expectations are for these tests?

File: src/backend/executor/execHHashagg.c (hunk 8 above)
Comment (melanieplageman) [reply src/backend/executor/execHHashagg.c]: Also, is the reason you want to reset the `serialization_cxt` each time so that pointers to transvalues which have already been emitted for streaming agg are no longer hanging around?

File: src/backend/executor/execHHashagg.c [hunk 15]
```diff
@@ -226,11 +232,45 @@ adjustInputGroup(AggState *aggstate,
...
+			if (temporary)
+				oldContext = MemoryContextSwitchTo(aggstate->tmpcontext->ecxt_per_tuple_memory);
+
+			pergroupstate->transValue = FunctionCallInvoke(dsinfo);
```
Comment (melanieplageman) [inline src/backend/executor/execHHashagg.c]: So, I notice that the `serialization_cxt` bytes allocated is not increased pretty much ever after the initialization of it to 8192. For example, when doing this deserialization, `AllocSetAllocImpl` is called with the `HashAggTableEntrySerializationContext`. It seems like you added a new memory context and then it isn't being used for the trans value that you are deserializing, which I don't understand.

File: src/test/regress/sql/workfile/hashagg_spill.sql [hunk 16]
```diff
@@ -74,6 +74,18 @@ insert into aggspill select i, i*2, i::text from generate_series(1, 10000) i;
 insert into aggspill select i, i*2, i::text from generate_series(1, 100000) i;
 insert into aggspill select i, i*2, i::text from generate_series(1, 1000000) i;
 
+drop table if exists aggspill_numeric;
+create table aggspill_numeric (i numeric, j numeric, t text) distributed by (i);
+insert into aggspill_numeric select i, i*2, i::text from generate_series(1, 10000) i;
+insert into aggspill_numeric select i, i*2, i::text from generate_series(1, 100000) i;
+insert into aggspill_numeric select i, i*2, i::text from generate_series(1, 1000000) i;
+
+drop table if exists aggspill_avg;
```
Comment (melanieplageman) [inline src/test/regress/sql/workfile/hashagg_spill.sql]: So, ideally, we would have 
- 1 test case which, without the patch code, OOMs due only to underestimate of hashtable size due to counting only group_buf and aggstate not being allocated in group buf
- 1 test case which, without the patch code, OOMs due to not serializing and deserializing the real transvalues.
And then have a description in the tests which describes the scenarios.

File: src/backend/utils/adt/numeric.c [hunk 17]
```diff
@@ -2870,13 +2873,23 @@ makeNumericAggState(FunctionCallInfo fcinfo, bool calcSumX2)
...
+	if (agg_type == AGG_CONTEXT_AGGREGATE && aggstate->hhashtable)
+	{
+		state = (NumericAggState *) mpool_alloc(aggstate->hhashtable->group_buf, sizeof(NumericAggState));
```
Comment (melanieplageman) [inline src/backend/utils/adt/numeric.c]: Can you add a comment about why you are doing this here?

File: src/backend/executor/execHHashagg.c [hunk 18]
```diff
@@ -1608,26 +1654,81 @@ writeHashEntry(AggState *aggstate, BatchFileInfo *file_info,
...
+
+			fcinfo.arg[0] = pergroupstate->transValue;
+			fcinfo.argnull[0] = pergroupstate->transValueIsNull;
+
+			/* Not necessary to do this if the serialization func has no memory leak */
+			old_ctx = MemoryContextSwitchTo(aggstate->hhashtable->serialization_cxt);
+
+			serializedVal = FunctionCallInvoke(&fcinfo);
+
+			datum_size = datumGetSize(serializedVal, byteaTranstypeByVal, byteaTranstypeLen);
```
Comment (melanieplageman) [inline src/backend/executor/execHHashagg.c]: So, previously, we weren't writing the actually serialized transValue to the spill file at all? This seems like this means this bug would also be in 5X_STABLE, no?

File: src/backend/executor/nodeAgg.c (hunk 7 above)
Comment (adam8157) [reply src/backend/executor/nodeAgg.c]: Spilling could happen in other aggstages, I suppose.

File: src/backend/executor/execHHashagg.c (hunk 8 above)
Comment (adam8157) [reply src/backend/executor/execHHashagg.c]: The reason to use mpool is I failed to get the `used` memory of a normal memory context, mpool has a count.

Serial/Deserial have memory leaks as the last commit shows, even we fixed the memory leaks, I suppose it's better to have a short-life memory context for short-life usages which alloc/free small spaces quite frequently.

File: src/backend/executor/nodeAgg.c (hunk 11 above)
Comment (adam8157) [reply src/backend/executor/nodeAgg.c]: Before this PR, only INTERMEDIATE or PARTIAL aggstages need the serial function, only the INTERMEDIATE or FINAL aggstages need the deserial function, makes sense, only the sender serial, the receiver deserial.

But now, if it's a INTERNAL type and has serial/deserial, we need these functions while spilling in any aggstage.

File: src/test/regress/sql/workfile/hashagg_spill.sql (hunk 13 above)
Comment (adam8157) [reply src/test/regress/sql/workfile/hashagg_spill.sql]: Ah, it's a count(), which doesn't need the NumericAggState... Checkout out the avg() case below, it should go with the new code.

File: src/test/regress/sql/workfile/hashagg_spill.sql (hunk 14 above)
Comment (adam8157) [reply src/test/regress/sql/workfile/hashagg_spill.sql]: Sure, thanks.

File: src/backend/executor/execHHashagg.c (hunk 18 above)
Comment (adam8157) [reply src/backend/executor/execHHashagg.c]: It does not write the trans data, only the pointers of trans data. 5X has not merged #5528, it's fine.

**Comment by adam8157** [comment]
@hlinnaka spilling a numeric aggregate currently works, because it spills and reloads the pointers of transValue in agg context, these pointers are valid while executing agg, however, this doesn't spill much and trigger OOM.

About the memory tracking, don't have a better idea for now, upstream also has some discussions (https://www.postgresql.org/message-id/507ac540ec7c20136364b5272acbcd4574aa76ef.camel@j-davis.com). To not change numeric.c and fix third-party extensions, which probably copies numeric.c's logic allocating memory in agg-context, we might only do an estimation but not tracking...

File: src/backend/executor/execHHashagg.c (hunk 18 above)
Comment (melanieplageman) [reply src/backend/executor/execHHashagg.c]: How do we know that these pointers will point to valid memory in heap when the spill file is reloaded?

Comment (melanieplageman) [reply src/backend/executor/execHHashagg.c]: Okay, talked to @d and apparently it is okay because the pointers will still point to valid memory because we don't free it...

**Comment by melanieplageman** [comment]
> @hlinnaka spilling a numeric aggregate currently works, because it spills and reloads the pointers of transValue in agg context, these pointers are valid while executing agg, however, this doesn't spill much and trigger OOM.
> 
> About the memory tracking, don't have a better idea for now, upstream also has some discussions (https://www.postgresql.org/message-id/507ac540ec7c20136364b5272acbcd4574aa76ef.camel@j-davis.com). To not change numeric.c and fix third-party extensions, which probably copies numeric.c's logic allocating memory in agg-context, we might only do an estimation but not tracking...

@adam8157 This is actually an interesting idea--in the upstream memory accounting, the balance is kept in the memory context and only increased when we malloc() and captures number of bytes in block malloc()d. We track chunks, so it will be much rougher, but, I wonder, if we just applied the patch to do that counting and then used the checking function they provide to see what the balance is, if it is anything close to what we have in `group_buf`, or, if not, if we could tweak the check for when to spill to accommodate this. Only hashagg spill uses a lot of these memory management concepts like `mpool` and `MemoryContainerManagers`. Maybe we could get rid of them?

File: src/backend/executor/execHHashagg.c (hunk 15 above)
Comment (adam8157) [reply src/backend/executor/execHHashagg.c]: Two reasons the `serialization_cxt` is not increased much: 1, the query :) 2, the "Fix the memory leaks in numeric serialization function" patch.

About the deserialization, if the entry `isNew`, `temporary` is false, we use `serialization_cxt` to deserialize.

**Comment by adam8157** [comment]
Thanks, @melanieplageman , a separate context sill requires changing numeric.c, and other third-party extensions' cooperation. The entries are freed by resetting group_buf.

Let me summarize the issue and proposals.

The issue:
numeric and other possible third-party extensions use agg-context to store the transValue, we need to know if it's going to use too much memory and spill. Get rid of `mpool` and `MemoryContainerManagers` if possible.

Proposals:
1. Check the `allBytesAlloc` of agg-context directly, if it's close to the operator memory quota, we spill. It would be simple, and the idea tracking all Agg allocated memory makes sense since that's the root if OOM. But it will be a little rough, probably OK? Basically, it's the same idea as Melanis's but not a separate context, because numeric.c and probably others switch to agg-context explicitly.

2, Hijack the agg-context with modified `alloc` and `free` wrapper functions counting the memory, we maintain another counter which records the memory used by hash table, transValue especially. (sum the number differences before and after transValues allocating) This counter replaces the group_buf usage before.

**Comment by melanieplageman** [comment]
> Thanks, @melanieplageman , a separate context sill requires changing numeric.c, and other third-party extensions' cooperation. The entries are freed by resetting group_buf.
> 
Using a separate context--switching to it explicitly before calling advance_aggregates--seems like it would not require changing numeric.c. We would use the bytes allocated as tracked in that context to decide whether or not to spill. That balance should include anything which was palloc()d in that context, so, we wouldn't need to add in additional bytes inside of any aggregate functions themselves, right?

> Let me summarize the issue and proposals.
> 
> The issue:
> numeric and other possible third-party extensions use agg-context to store the transValue, we need to know if it's going to use too much memory and spill. Get rid of `mpool` and `MemoryContainerManagers` if possible.
> 
> Proposals:
> 
>     1. Check the `allBytesAlloc` of agg-context directly, if it's close to the operator memory quota, we spill. It would be simple, and the idea tracking all Agg allocated memory makes sense since that's the root if OOM. But it will be a little rough, probably OK? Basically, it's the same idea as Melanis's but not a separate context, because numeric.c and probably others switch to agg-context explicitly.
> 

It seems like aggcontext would have a lot of stuff that has a longer lifespan than the hashagg hashtable tuples and therefore the estimate might not be as easy to reason about.

It would also be good to see what it would take to get rid of `datumCopyWithMemManager`.
I think `datumCopyWithMemManager` copies every tuple into the tmpcontext (entry context for hashtable which lasts until a result tuple for the agg is emitted) from the per tuple context to make it last longer so we can spill it and to allow us to use the exact size of the tuple in our memory used balance for deciding to spill. I was just wondering if it was possible to allocate the memory for these tuples in a memory context that is long-lasting enough that we don't need to make this copy.

I think we could try making mpool into a new MemoryContext (basically use the MemoryContext API) and use that as the medium-lifespan memory context to allow us to still get the benefits of the mpool allocation optimizations.

I actually am not sure I understand why using aggcontext is better than making a new context -- does it have to do with 3rd party extensions and user-defined aggregates?

> 
> 2, Hijack the agg-context with modified `alloc` and `free` wrapper functions counting the memory, we maintain another counter which records the memory used by hash table, transValue especially. (sum the number differences before and after transValues allocating) This counter replaces the group_buf usage before.

This is interesting, but, how would this affect other aggregates than hashagg. It seems like it might be sketchy.

**Comment by adam8157** [comment]
I thought agg-context is better than making a new context because in some cases numeric.c switches to agg-context explicitly, then no matter the new context the memory will be allocated in agg-context.

That's what I thought, but after I review the process, our codes won't go to that processing branch.

Will revert all numeric.c changes and try replacing group_buf with a new context.

**Comment by melanieplageman** [comment]
> I thought agg-context is better than making a new context because in some cases numeric.c switches to agg-context explicitly, then no matter the new context the memory will be allocated in agg-context.
> 
> ~That's what I thought, but after I review the process, our codes won't go to that processing branch.~
> 
> ~Will revert all numeric.c changes and try replacing group_buf with a new context.~
> 
> Our codes do call `makeNumericAggState()`, which `palloc0()` in `aggcontext`, while initializing aggregates calls the trans function `numeric_accum()` at the first time.
> 
> The only way not to change numeric.c is accounting `aggcontext`, I suppose.
> 

I feel better about not changing numeric.c, though I don't have a specific example of how it could go wrong -- besides what has already been provided.

> However, for the third-party extensions, if they don't switch memory context, when the trans function is called at the first time, the CurrentMemoryContext should be the per-query context, accounting `aggcontext` doesn't help either... Seems there is not a perfect solution for the third-party extensions for now from my perspective.

So, I'm confused-- you said that for third-party extensions, the CurrentMemoryContext when they are deserializing trans values is the per-query context? Could you give an example? Could this problem be reproduced with a user-defined aggregate instead of a third-party extension?

**Comment by adam8157** [comment]
> So, I'm confused-- you said that for third-party extensions, the CurrentMemoryContext when they are deserializing trans values is the per-query context? Could you give an example? Could this problem be reproduced with a user-defined aggregate instead of a third-party extension?

Oh, check out advance_aggregates(), `When called, CurrentMemoryContext should be the per-query context.`, so my point here is, `numeric_accum()` calls `makeNumericAggState()` which switches to `aggcontext`, good, accounting the `aggcontext` is possible, but if any other user-defined aggregate doesn't switch to `aggcontext`, accounting `aggcontext` doesn't work then. I probably thought too far :)

I'm trying the approach accounting `aggcontext` instead of mpool. Changing numeric.c and using mpool looks ugly to me, but I guess `changing numeric.c && using (mpool || a separate context)` might be the better choice.

**Comment by melanieplageman** [comment]
> > So, I'm confused-- you said that for third-party extensions, the CurrentMemoryContext when they are deserializing trans values is the per-query context? Could you give an example? Could this problem be reproduced with a user-defined aggregate instead of a third-party extension?
> 
> Oh, check out advance_aggregates(), `When called, CurrentMemoryContext should be the per-query context.`, so my point here is, `numeric_accum()` calls `makeNumericAggState()` which switches to `aggcontext`, good, accounting the `aggcontext` is possible, but if any other user-defined aggregate doesn't switch to `aggcontext`, accounting `aggcontext` doesn't work then. I probably thought too far :)
> 

I understand what you are saying now. How about we use the memory context that is set in the AggState (`NumericAggState->agg_context` in this case)? It seems to be a safe assumption that any user-defined aggregate would have an AggState which would have this context specified. Anyway, it is by default `aggcontext` for numericagg.

Could we actually devise a test case which is a UDA which would have this problem?

> I'm trying the approach accounting `aggcontext` instead of mpool. Changing numeric.c and using mpool looks ugly to me, but I guess `changing numeric.c && using (mpool || a separate context)` might be the better choice.

So, let's say we don't use a separate context and, instead, we use aggcontext, like you are working on right now. Can we still check some combination of `allBytesFreed`, `allBytesAlloc`,`maxBytesHeld`, and `localMinHeld` in that MemoryContext before and after returning from the trans functions to give us an estimate of memory requirements of that entry?

The benefit I see of using a separate shorter living memory context than aggcontext is that we can reset it when we don't need the hashtable entries anymore but before we are able to reset the aggcontext. I don't see how it would differ in any other way.

**Comment by adam8157** [comment]
Got the green light from PM.

The next steps:
1, update code comments and merge this PR
2, create another PR which uses sub-context or aggcontext but keep the numeric.c the same as upstream

**Comment by adam8157** [comment]
Backported to 6X, and opened a new PR #8280
