### PR TITLE
Fix pg_stat_statements node type unexpected warning

### LINKED ISSUE #15093: pg_regress report 'WARNING: unrecognized node type' when enable pg_stat_statements
### Greenplum version or build
commit-id : `e3ba21f2b6be257fa22dc806a3cebdd6405d0e0d`
### OS version and uname -a
```shell
Ubuntu 20.04 focal x86_64 Linux 5.15.0-52-generic
```
### autoconf options used ( config.status --config )
`LLVM_CONFIG='/home/llvm-project-11/build/bin/llvm-config' ./configure --prefix=/home/gpdb/build --with-llvm --enable-debug --enable-orca;make -s -j 10;sudo make install`
### Expected behavior
run pg_regress with two case : `olap_setup qp_olap_group`, should be ok.
### Actual behavior
image

### Step to reproduce the behavior
After gpdb build.
```shell
1. make create-demo-cluster
2. set below options into qd's postgresql.conf:
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.max = 10000
pg_stat_statements.track = all

3. psql postgres, input : create extension pg_stat_statements ;
4. ./pg_regress --inputdir=. --bindir='/home/gpadmin/pie-db/gpdb/build/bin'    --load-extension=gp_inject_fault --dlpath=. --max-concurrent-tests=20 --init-file=./init_file olap_setup qp_olap_group
```

### PR DESCRIPTION
**Pull request by ZhangHuiGui**
## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

Fix #15093;

### CODE REVIEW

**Comment by liuxueyang** [comment]
The test case `qp_olap_group` does not pass:

```
../../../src/test/regress/scan_flaky_fault_injectors.sh && ../../../src/test/regress/pg_regress --inputdir=. --bindir='/home/gpadmin/local/gpdb_master/bin'    --load-extension=gp_inject_fault --dlpath=. --max-concurrent-tests=20 --init-file=./init_file  olap_setup qp_olap_group
```

Got the following diff:

```
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /home/gpadmin/workspace/gpdb-master/src/test/regress/expected/qp_olap_group.out /home/gpadmin/workspace/gpdb-master/src/test/regress/results/qp_olap_group.out
--- /home/gpadmin/workspace/gpdb-master/src/test/regress/expected/qp_olap_group.out     2023-03-10 17:19:49.022023409 +0800
+++ /home/gpadmin/workspace/gpdb-master/src/test/regress/results/qp_olap_group.out      2023-03-10 17:19:49.219024332 +0800
@@ -1561,50 +1561,8 @@
 FROM sale,product,vendor,customer
 WHERE sale.pn=product.pn AND sale.vn=vendor.vn AND sale.cn=customer.cn
 GROUP BY CUBE((sale.prc,sale.cn,sale.dt),(sale.pn,sale.vn),(sale.cn),(sale.qty,sale.qty),(sale.vn,sale.pn));

...
...

+DETAIL:  FailedAssertion("!(query_len <= strlen(query))", File: "pg_stat_statements.c", Line: 1130)
+ERROR:  Unexpected internal error (assert.c:48)
 -- ###### Queries involving VARIANCE() function ###### --
 SELECT DISTINCT sale.cn,sale.qty,sale.vn,sale.qty,GROUPING(sale.cn,sale.qty),GROUP_ID(), TO_CHAR(COALESCE(VARIANCE(floor(sale.cn+sale.cn)),0),'99999999.9999999'),TO_CHAR(COALESCE(MAX(floor(sale.vn)),0),'99999999.9999999')
 FROM sale,customer,product
```

**Comment by ZhangHuiGui** [comment]
> The test case `qp_olap_group` does not pass:
> 
> ```
> ../../../src/test/regress/scan_flaky_fault_injectors.sh && ../../../src/test/regress/pg_regress --inputdir=. --bindir='/home/gpadmin/local/gpdb_master/bin'    --load-extension=gp_inject_fault --dlpath=. --max-concurrent-tests=20 --init-file=./init_file  olap_setup qp_olap_group
> ```
> 
> Got the following diff:
> 
> ```
> diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /home/gpadmin/workspace/gpdb-master/src/test/regress/expected/qp_olap_group.out /home/gpadmin/workspace/gpdb-master/src/test/regress/results/qp_olap_group.out
> --- /home/gpadmin/workspace/gpdb-master/src/test/regress/expected/qp_olap_group.out     2023-03-10 17:19:49.022023409 +0800
> +++ /home/gpadmin/workspace/gpdb-master/src/test/regress/results/qp_olap_group.out      2023-03-10 17:19:49.219024332 +0800
> @@ -1561,50 +1561,8 @@
>  FROM sale,product,vendor,customer
>  WHERE sale.pn=product.pn AND sale.vn=vendor.vn AND sale.cn=customer.cn
>  GROUP BY CUBE((sale.prc,sale.cn,sale.dt),(sale.pn,sale.vn),(sale.cn),(sale.qty,sale.qty),(sale.vn,sale.pn));
> 
> ...
> ...
> 
> +DETAIL:  FailedAssertion("!(query_len <= strlen(query))", File: "pg_stat_statements.c", Line: 1130)
> +ERROR:  Unexpected internal error (assert.c:48)
>  -- ###### Queries involving VARIANCE() function ###### --
>  SELECT DISTINCT sale.cn,sale.qty,sale.vn,sale.qty,GROUPING(sale.cn,sale.qty),GROUP_ID(), TO_CHAR(COALESCE(VARIANCE(floor(sale.cn+sale.cn)),0),'99999999.9999999'),TO_CHAR(COALESCE(MAX(floor(sale.vn)),0),'99999999.9999999')
>  FROM sale,customer,product
> ```

Thanks, i'll take a look.

**Comment by liuxueyang** [comment]
@ZhangHuiGui I create a fix for that `Assert` problem.

File: contrib/pg_stat_statements/pg_stat_statements.c [hunk 1]
```diff
@@ -2604,6 +2604,15 @@ JumbleExpr(pgssJumbleState *jstate, Node *node)
 				JumbleExpr(jstate, (Node *) grpnode->refs);
 			}
 			break;
+		case T_GroupId:
+		case T_GroupingSetId:
+		case T_RowIdExpr:
+		case T_AggExprId:
+			/*
+			 * No need to jumble for gpdb's special ops, they don't have
+			 * node type, so we just prevent warning here.
```
Comment (liuxueyang) [inline contrib/pg_stat_statements/pg_stat_statements.c:2621]: This comment should be fixed. Because the node type for them is defined in the file `include/nodes/primnodes.h`.

Besides, why it's safe to just `break` for these nodes without `APP_JUMB` and `JumbleExpr`?

Comment (ZhangHuiGui) [reply contrib/pg_stat_statements/pg_stat_statements.c:2621]: Jumble is just used for producing a hash value for a unique queryId in pg_stat_statements.
And the node type won't be parsed one by one and check their correctness.

Comment (ZhangHuiGui) [reply contrib/pg_stat_statements/pg_stat_statements.c]: sorry, i did't pull your commit,please push again :(

Comment (liuxueyang) [reply contrib/pg_stat_statements/pg_stat_statements.c]: Do you mean that these three types of nodes do not affect the uniqueness of the query?

**Comment by adam8157** [comment]
How is this going?

**Review by Sasasu — APPROVED** [review]
the logic is fine to me.

but for the test case. the test case is copied from `./src/test/regress/sql/olap_group.sql` with out modifition. can you switch to symlink.

then with 2 approvers, we can merge this PR.

**Comment by liuxueyang** [comment]
@Sasasu Thanks. These files are replaced with the corresponding symbolic links.

**Review by Sasasu — APPROVED** [review]

**Review by higuoxing — APPROVED** [review]
Can we craft a simple test case instead of creating a symbolic link to a complex test (If it's not easy to do let's leave it as is)? Otherwise looks good to me!

**Comment by liuxueyang** [comment]
> Can we craft a simple test case instead of creating a symbolic link to a complex test (If it's not easy to do let's leave it as is)? Otherwise looks good to me!

The existing test `olap_setup` and `qp_olap_group` already contain the related warning problem in the issue https://github.com/greenplum-db/gpdb/issues/15093 We don't need to create another test.

I created a dev pipeline https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-fix-pg-stat-statements-node-type-lost-rocky8

I will merge this PR once the pipeline passes.
