### PR TITLE
[6X Only] Use opclass to retrieve operators for partitioned table.

### LINKED ISSUE #14941: GPDB failed to retrieve operator when inserting data into partitioned table.
- 6X (now the top commit is 23ceacc667e9eec964fd3545314420df54377074)
- Main branch does not have the bug due to merging to upstream.

### Steps to reproduce

```
create type myint;
create function myint_in(cstring) returns myint as 'int4in' language internal immutable strict;
create function myint_out(myint) returns cstring as 'int4out' language internal immutable strict;
create function myint_send(myint) returns bytea as 'int4send' language internal immutable strict;
create function myint_recv(internal) returns myint as 'int4recv' language internal immutable strict;
create type myint (input=myint_in, output=myint_out, receive=myint_recv, send=myint_send, passedbyvalue, internallength=4);
create function myint_lt(myint, myint) returns boolean as 'int4lt' language internal immutable strict;
create function myint_le(myint, myint) returns boolean as 'int4le' language internal immutable strict;
create function myint_gt(myint, myint) returns boolean as 'int4gt' language internal immutable strict;
create function myint_ge(myint, myint) returns boolean as 'int4ge' language internal immutable strict;
create function myint_eq(myint, myint) returns boolean as 'int4eq' language internal immutable strict;
create function myint_ne(myint, myint) returns boolean as 'int4ne' language internal immutable strict;
create operator < (leftarg=myint, rightarg=myint, procedure=myint_lt, commutator= >, negator= >=, restrict=scalarltsel, join=scalarltjoinsel);
create operator > (leftarg=myint, rightarg=myint, procedure=myint_gt, commutator= <, negator= <=, restrict=scalargtsel, join=scalargtjoinsel);
create operator <= (leftarg=myint, rightarg=myint, procedure=myint_le, commutator= >=, negator= >, restrict=scalarltsel, join=scalarltjoinsel);
create operator >= (leftarg=myint, rightarg=myint, procedure=myint_ge, commutator= <=, negator= <, restrict=scalargtsel, join=scalargtjoinsel);
create operator = (leftarg=myint, rightarg=myint, procedure=myint_eq, commutator= =, negator= <>, restrict=eqsel, join=eqjoinsel, hashes, merges);
create operator <> (leftarg=myint, rightarg=myint, procedure=myint_ne, commutator= <>, negator= =, restrict=neqsel, join=neqjoinsel, merges);
create function bt_myint_cmp (myint, myint) returns int as 'btint4cmp' language internal immutable strict;
create operator class bt_myint_ops default for type myint using btree family integer_ops as
  operator 1 <,
  operator 2 <=,
  operator 3 =,
  operator 4 >=,
  operator 5 >,
  function 1 bt_myint_cmp (myint, myint);
create cast (int as myint) without function as implicit;
```

Create a partitioned table and insert some data into it.
```

create table table_foo(i myint) partition by list (i) (values ('1', '2'));
insert into table_foo values ('1');
```

### Expected behavior

The insertion can be performed successfully.

### Actual behavior
```
ERROR:  operator does not exist: myint pg_catalog.= myint  (seg1 127.0.0.1:6003 pid=372972)
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

### PR DESCRIPTION
**Pull request by higuoxing**
Historically, we hardedcode searching path in Greenplum when retrieving operators for partitioned table.  When inserting data into gpdb, it looks up operators in the 'pg_catalog' schema.  That is to say, we cannot partition a table with user defined types unless we create the type and its associated operators inside the 'pg_catalog' schema.  This patch helps resolve the problem by looking up operators using the opclass that we use when defining the partitioned table.

Fix #14941

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [x] Pass `make installcheck`

### CODE REVIEW

**Comment by kainwen** [comment]
Thanks for the PR.

* the change on `src/backend/parser/parse_partition.c` seems resolve another issue, better to split in other commits
* recommend to create issues to track the bugs of each problem, and encode the issue link in code and test
* we may split the PR into commits:
  1. 1st commit to just change the function prototype, like opname to strategy number
  2. 2nd commit to use opclass to search the operator
  3. the code change of `parse_partition.c`

File: src/backend/cdb/cdbpartition.c [hunk 1]
```diff
@@ -4172,35 +4158,49 @@ selectListPartition(PartitionNode *partnode, Datum *values, bool *isnull,
...
-
-	Oid			funcid = get_opfuncid_by_opname(opname, lhstypid, rhstypid);
+	Oid opfamily = get_opclass_family(opclass);
+	Oid opno = InvalidOid;
+	/*
+	 * There's no associated operator for domain types, we need to fetch the base type
+	 * of these types.
+	 */
+	Oid lbasetypid = OidIsValid(lhstypid) ? getBaseType(lhstypid) : lhstypid;
+	Oid rbasetypid = OidIsValid(rhstypid) ? getBaseType(rhstypid) : rhstypid;
```
Comment (kainwen) [inline src/backend/cdb/cdbpartition.c:4183]: I don't think we need manually fetch base type here

**Comment by jimmyyih** [comment]
This PR caught my attention because I was actually working on a very similar issue: https://github.com/greenplum-db/gpdb/issues/9405

I tried out the patch in this PR hoping it would fix the above Github issue but it didn't because the CREATE TABLE still relied on search_path being set correctly.  The quick patch that I've been experimenting with fixes the above Github issue by fully qualifying the operator name when setting up the partition rules.  Interestingly, my patch also seems to successfully run against your new tests (the list partition ones only since I haven't touched the range partition logic yet):
https://github.com/jimmyyih/gpdb/commit/f9896c196d32be044f1053133a232329df39f545

To reproduce the issue from the above Github issue, you would just need to reset search_path before creating the partition table.  Example:
```
RESET search_path;
create table student_list_part (s part_op_test.student)
partition by list (s)
(partition one values ('1'::text::part_op_test.student),
partition two values ('2'::text::part_op_test.student),
partition three values ('3'::text::part_op_test.student),
partition four values ('4'::text::part_op_test.student));
```

I haven't fully read the proposed changes in this PR yet but I'm wondering if it is complimentary to the patch I'm working on or not.  Thoughts?  I'll most likely look at this PR closer tomorrow.

**Comment by higuoxing** [comment]
> * the change on `src/backend/parser/parse_partition.c` seems resolve another issue, better to split in other commits

If we want to create partition table on 6X, we must provide the partition boundary spec. e.g.,

```
create table part_tbl(i int) partition by range (i) (start (xxx) end (yyy) every (zzz));
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

When parsing the partition boundary spec, gpdb looks up operators in pg_catalog schema. So, if we want write testcase using custom data types (which is not created under pg_catalog schema), we should fix it in this PR as well. I can split it into another commit if it brings difficulty to reviewers.

>     * recommend to create issues to track the bugs of each problem, and encode the issue link in code and test

Thanks, I will create github issue to track and encode the issue number into the test case.

>     * we may split the PR into commits:
>       
>       1. 1st commit to just change the function prototype, like opname to strategy number
>       2. 2nd commit to use opclass to search the operator
>       3. the code change of `parse_partition.c`

Sure, I will do that.

File: src/backend/cdb/cdbpartition.c (hunk 1 above)
Comment (higuoxing) [reply src/backend/cdb/cdbpartition.c:4183]: If we don't fetch the base type here, we will break the test below

https://github.com/greenplum-db/gpdb/blob/479080f3ff7526742ac4297e65113139e24b6fd4/src/test/regress/sql/partition.sql#L2103

Comment (kainwen) [reply src/backend/cdb/cdbpartition.c:4183]: > If we don't fetch the base type here, we will break the test below
> 
> https://github.com/greenplum-db/gpdb/blob/479080f3ff7526742ac4297e65113139e24b6fd4/src/test/regress/sql/partition.sql#L2103

@higuoxing 
Based on your PR, I modify the code as the following diff it passes the case.

```diff
commit 78ce8ed776ee5d20e8f5a7c0973e5d20e824c6b3 (HEAD -> 6x/remove-hardcode-schema)
Author: Zhenghua Lyu <kainwen@gmail.com>
Date:   Tue Feb 14 11:01:19 2023 +0000

    xxx test.

diff --git a/src/backend/cdb/cdbpartition.c b/src/backend/cdb/cdbpartition.c
index 4a6d1cc377b..ea10ade7027 100644
--- a/src/backend/cdb/cdbpartition.c
+++ b/src/backend/cdb/cdbpartition.c
@@ -4175,14 +4175,8 @@ cdb_retrieve_btree_op(Oid opclass, Oid lhstypid, Oid rhstypid, int16 strategy)
 {
        Oid opfamily = get_opclass_family(opclass);
        Oid opno = InvalidOid;
-       /*
-        * There's no associated operator for domain types, we need to fetch the base type
-        * of these types.
-        */
-       Oid lbasetypid = OidIsValid(lhstypid) ? getBaseType(lhstypid) : lhstypid;
-       Oid rbasetypid = OidIsValid(rhstypid) ? getBaseType(rhstypid) : rhstypid;

-       opno = get_opfamily_member(opfamily, lbasetypid, rbasetypid, strategy);
+       opno = get_opfamily_member(opfamily, lhstypid, rhstypid, strategy);
        if (!OidIsValid(opno))
        {
                /*
@@ -4196,7 +4190,7 @@ cdb_retrieve_btree_op(Oid opclass, Oid lhstypid, Oid rhstypid, int16 strategy)
                 * type is 'VARCHAR'. We use IsBinaryCoercible to handle these binary-compatible types.
                 */
                Oid inctypid = get_opclass_input_type(opclass);
-               if (IsBinaryCoercible(lbasetypid, inctypid) && IsBinaryCoercible(rbasetypid, inctypid))
+               if (IsBinaryCoercible(lhstypid, inctypid) && IsBinaryCoercible(rhstypid, inctypid))
                        opno = get_opfamily_member(opfamily, inctypid, inctypid, strategy);
        }
```

```
gpadmin@zlyu:~/workspace/gpdb/src/test/regress$ git log --oneline | head -3
78ce8ed776e xxx test.
f42e9bb8ef9 [6X Only] Use opclass to retrieve operators for partitioned table.
39de39eb6ed using postgres query optimizer instead of ORCA to run resgroup group pipeline tests (#13990)

gpadmin@zlyu:~/workspace/gpdb/src/test/regress$ psql -c "select version()" -d postgres
                                                                                                            version
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.26 (Greenplum Database 6.23.0+dev.69.g78ce8ed776e build dev) on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit compiled on Feb 14 2023 11:04:02 (with assert checking)
(1 row)


gpadmin@zlyu:~/workspace/gpdb/src/test/regress$ PGOPTIONS='-c optimizer=off' ./pg_regress --init-file=init_file partition
(using postmaster on Unix socket, port 6000)
============== dropping database "regression"         ==============
NOTICE:  database "regression" does not exist, skipping
DROP DATABASE
============== creating database "regression"         ==============
CREATE DATABASE
ALTER DATABASE
============== checking optimizer status              ==============
Optimizer disabled. Using planner answer files
============== checking gp_resource_manager status    ==============
Resource group disabled. Using default answer files
============== running regression test queries        ==============
test partition                ... ok

=====================
 All 1 tests passed.
=====================
```

**Review by kainwen — COMMENTED** [review]
Code change LGTM. I leave some concern on `cdb_retrieve_btree_op`.

I will start a new round of review and I will focus on the dynamic partition prune part.

Thanks for you PR!

File: src/backend/cdb/cdbpartition.c (hunk 1 above)
Comment (higuoxing) [reply src/backend/cdb/cdbpartition.c:4183]: Thanks for the cleanup. `IsBinaryCoercible` cast the domain type to its base type for us.

https://github.com/greenplum-db/gpdb/blob/4e27cd05b29ce9a1ab26a2704059951fced7f8d0/src/backend/parser/parse_coerce.c#L2426

File: src/backend/cdb/cdbpartition.c [hunk 2]
```diff
@@ -4172,35 +4158,49 @@ selectListPartition(PartitionNode *partnode, Datum *values, bool *isnull,
...
+		 *   CREATE TABLE part_tbl_varchar (a VARCHAR(15) NOT NULL, b VARCHAR(8) NOT NULL)
+		 *     DISTRIBUTED BY (a)
+		 *     PARTITION BY RANGE(b)
+		 *       (START('v1') END('v5'), START('v5') END('v9'), DEFAULT PARTITION def);
+		 * The recorded opclass for the partitioning key is text_ops (3126), though the column
+		 * type is 'VARCHAR'. We use IsBinaryCoercible to handle these binary-compatible types.
+		 */
+		Oid inctypid = get_opclass_input_type(opclass);
+		if (IsBinaryCoercible(lbasetypid, inctypid) && IsBinaryCoercible(rbasetypid, inctypid))
+			opno = get_opfamily_member(opfamily, inctypid, inctypid, strategy);
```
Comment (kainwen) [inline src/backend/cdb/cdbpartition.c:4200]: if we still cannot find any, maybe throw an error?

**Review by kainwen — APPROVED** [review]

**Comment by kainwen** [comment]
I have approved this PR. But when reviewing this, I find an issue https://github.com/greenplum-db/gpdb/issues/14982
which need to be resolved in another PR.

Fixing that issue is a pre-condition of this fix's correctness.

NOTE: the above does not block this PR's merging. Let's register this PR to next ship it and better to have internal techtalks to let more people review this.

Thanks for your contribution!

File: src/test/regress/sql/partition.sql [hunk 3]
```diff
@@ -4185,3 +4185,139 @@ alter table tbl_default_distribution exchange partition for (rank(2)) with table
 create table rnd_distribution(a1 int, a int, b int, c int) distributed randomly;
 alter table rnd_distribution drop column a1;
 alter table tbl_default_distribution exchange partition for (rank(2)) with table rnd_distribution;
+
+--
+-- Test that we are able to partition a table by custom created data types.
```
Comment (ashwinstar) [inline src/test/regress/sql/partition.sql:4190]: would be good to validate if main branch at least has test for this case.

Comment (higuoxing) [reply src/test/regress/sql/partition.sql:4190]: Sure, will add this test to the main branch.
