### PR TITLE
Fix memory leak in Dynamic Index/IndexOnly/BitmapIndex Scan during execution (#16797)

### LINKED ISSUE #16797: Dynamic Index Scan under Nestloop Index Join memory leak
## Bug Report
When execute a plan following: 
```
postgres=# explain (analyze, costs off) select * from t_partition join t_join on a = b2;
                                                    QUERY PLAN
------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3) (actual time=31970.378..32665.142 rows=10 loops=1)
   ->  Nested Loop (actual time=2.954..32663.643 rows=5 loops=1)
         Join Filter: true
         ->  Redistribute Motion 3:3  (slice2; segments: 3) (actual time=1.089..30.434 rows=33462 loops=1)
               Hash Key: t_join.b2
               ->  Seq Scan on t_join (actual time=0.104..9.282 rows=33462 loops=1)
         ->  Dynamic Index Scan on t_partition_a_idx on t_partition (actual time=0.000..0.974 rows=0 loops=33462)
               Index Cond: (a = t_join.b2)
               Number of partitions to scan: 5 (out of 5)
               Partitions scanned:  Avg 5.0 x 3 workers of 33462 scans.  Max 5 parts (seg0).
 Optimizer: GPORCA
 Planning Time: 58.855 ms
   (slice0)    Executor memory: 41K bytes.
   (slice1)    Executor memory: 33909K bytes avg x 3 workers, 34039K bytes max (seg0).
   (slice2)    Executor memory: 37K bytes avg x 3 workers, 37K bytes max (seg0).
 Memory used:  128000kB
 Execution Time: 32959.176 ms
(17 rows)
```

The segment memory will increase rapidly, if the test table _t_join_  had more rows, memory usage will exceed gp_vmem_protect_limit，and finally raise an ERROR:
```
ERROR:  Canceling query because of high VMEM usage. Used: xxMB, available xxMB, red zone: xxMB (runaway_cleaner.c:189)
```

Planner's plan with Index Scan won't have this problem.

### Step to reproduce the behavior
create table t_partition (a int, b int) partition by range(b) (start(0) end(10) every (2));
create index on t_partition(a);
create table t_join (a2 int, b2 int);

insert into t_partition select i, i from generate_series(0, 9) i;
insert into t_join values(1, 1);
analyze t_partition;
analyze t_join;
insert into t_join select i, i from generate_series(1, 100000) i;
explain (analyze, costs off) select * from t_partition join t_join on a = b2;

### PR DESCRIPTION
**Pull request by wuyuhao28**
This fix addresses a memory leak that occurs during the execution of DynamicIndexScan, DynamicIndexOnlyScan, and DynamicBitmapIndexScan. Each partition of the DynamicIndexScan creates an IndexScanState for execution usage. Within each IndexScanState, an ExprContext is allocated but not freed in ExecFreeExprContext(). This ExprContext includes a MemoryContext, resulting in a memory leak of the initial context space during each iteration of the DynamicIndexScan partition loop. Which will lead to a significant accumulation of leaked memory if the partition loop is extensive.
The same issue is observed in the execution of DynamicIndexOnlyScan and DynamicBitmapIndexScan.

This fix ensures that the allocated MemoryContext within the ExprContext is properly freed during the execution of each partition in Dynamic Index/IndexOnly/BitmapIndex Scan.

Fix #16797

### CODE REVIEW

File: src/backend/executor/execDynamicIndexes.c [hunk 1]
```diff
@@ -206,12 +206,26 @@ endCurrentIndexScan(DynamicIndexScanState *node)
 {
 	if (node->indexScanState)
 	{
+		/* Free ExprContext allocated in beginCurrentIndexScan */
```
Comment (chrishajas) [inline src/backend/executor/execDynamicIndexes.c:209]: Nice find!

I'm trying to understand this a bit more, since it looks like we tried to clean this up previously. In `ExecEndIndexScan`, we call `ExecFreeExprContext` (which just sets it to null). However, if it's a runtime context, it also calls `FreeExprContext` on this runtime context, which is set to the exprcontext in `ExecInitIndexScanForPartition`. In this case, are we only leaking memory when it doesn't have runtime keys?

 I just want to ensure we're not possibly double freeing anything here.

Comment (wuyuhao28) [reply src/backend/executor/execDynamicIndexes.c:209]: _In this case, are we only leaking memory when it doesn't have runtime keys?_

No, each partition will leak some memory allocated in **initNextIndexToScan()**, when moving from one partition to an other. 
In Nestloop Index Join case, this movement is looped many times when rescan.

**Comment by gpopt** [comment]
@wuyuhao28 Thanks for your contribution, does the memory leak issue exist on 6X_STABLE branch?

File: src/backend/executor/execDynamicIndexes.c (hunk 1 above)
Comment (THANATOSLAVA) [reply src/backend/executor/execDynamicIndexes.c:209]: > I just want to ensure we're not possibly double freeing anything here.

Looking at the following in `nodeIndexscan.c`, runtime context and plan state expr context point to different addresses. I don't think we would be freeing twice.

```c
	/*
	 * If we have runtime keys, we need an ExprContext to evaluate them. The
	 * node's standard context won't do because we want to reset that context
	 * for every tuple.  So, build another context just like the other one...
	 * -tgl 7/11/00
	 */
	if (indexstate->iss_NumRuntimeKeys != 0)
	{
		ExprContext *stdecontext = indexstate->ss.ps.ps_ExprContext;

		ExecAssignExprContext(estate, &indexstate->ss.ps);
		indexstate->iss_RuntimeContext = indexstate->ss.ps.ps_ExprContext;
		indexstate->ss.ps.ps_ExprContext = stdecontext;
	}

```

**Comment by wuyuhao28** [comment]
> @wuyuhao28 Thanks for your contribution, does the memory leak issue exist on 6X_STABLE branch?

Yes, need backport to 6X_STABLE

File: src/backend/executor/execDynamicIndexes.c [hunk 2]
```diff
@@ -206,12 +206,26 @@ endCurrentIndexScan(DynamicIndexScanState *node)
...
 	}
 	else if (node->indexOnlyScanState)
 	{
+		/* Free ExprContext allocated in beginCurrentIndexScan */
+		if (node->indexOnlyScanState->ss.ps.ps_ExprContext)
+		{
+			FreeExprContext(node->indexOnlyScanState->ss.ps.ps_ExprContext, true);
+			node->indexOnlyScanState->ss.ps.ps_ExprContext = NULL;
+		}
+
```
[the remark this answers is not in the document]
Comment (wuyuhao28) [reply src/backend/executor/execDynamicIndexes.c:228]: `ExecEndIndexScan` and `ExecEndIndexOnlyScan` is from upstream code.
Also this PR focus on nodeDynamicIndex's problem, I think we don't want to change nodeIndexScan and nodeIndexOnlyScan behavior now.

File: src/backend/executor/execDynamicIndexes.c (hunk 1 above)
Comment (chrishajas) [reply src/backend/executor/execDynamicIndexes.c:209]: Got it, so `endCurrentIndexScan` is only freeing the runtime context. However, we want to free the expression context that is allocated in each `beginCurrentIndexScan` as well, and that's what this PR does. Thanks!

**Review by chrishajas — APPROVED** [review]
Looks good, nice find!

**Review by nimish350 — APPROVED** [review]
Tested +1 LGTM

Before fix: 
Screenshot 2023-12-13 at 2 45 06 PM

After fix: 
Screenshot 2023-12-13 at 2 45 23 PM

**Review by gpopt — APPROVED** [review]
+1

**Comment by chrishajas** [comment]
Merged, thanks for your contribution! If you'd like to backport this to 6X, we'll also get this merged to 6X_STABLE.

**Comment by wuyuhao28** [comment]
Thanks for reviewing, I will open a PR to backport this fix to 6X
