### PR TITLE
Make alter database set tablespace MPP ready

### LINKED ISSUE #5643: When I set new tablespace for a database, the directory of db doesn't move to the new place
### Greenplum version or build
master branch
### OS version and uname -a
Linux  3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/usr/local/gpdb' '--with-gssapi' '--with-pgport=5432' '--with-libedit-preferred' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-krb5' '--enable-cassert' '--enable-debug' '--enable-debugbreak' '--enable-depend' '--with-libxml' '--disable-orca' 'CFLAGS=-O0 -g3'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -O0 -g3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 9.2beta2
### Expected behavior
the directory of database will be moved to the new directory of the specific tablespace
### Actual behavior
the directory of database is not moved, and some data(relative too small than the amount of database `test1`) is generated
### Step to reproduce the behavior
1.  `create database test1;`
2. `create table a(id int, name text);` // under database test1
3. insert data into table a
4. create tablespace testsp location _new_place_
5. switch to other database
6. `alter database test1 set tablespace testsp`

### PR DESCRIPTION
**Pull request by l-wang**
The alter database set tablesapce command should alter the tablespace on
QD and all the QEs. This patch adds dispatching of the alter database
set tablespace command to QEs. In Greenplum, the transaction should be
atomic across all the segments and master, hence need to use two phase
commit for this operation. Due to usage of 2PC, the implementation needs
to differ compared upstream, can't locally commit the transactions.
Catalog changes are committed and later using pending deletes, old
tablespace directory is removed only on commit.

Other alternative considered was using separate dispatch for deleting
the directory instead of using pending delete after commiting alter
database set tablespace transaction. But that seemed unnecessary
overhead compared to pending deletes approach.

Fixes #5643 Github issue.

Note: `dropdb()` currently is not MPP safe for similar reason, it uses 2PC but it deletes the database directory on each segment before commit. So if a segment fails, the database will remain in the catalog but on-disk files for some of the segments may be deleted. This makes the cluster inconsistent. We plan to fix `dropdb()` using the same logic proposed in this PR via pending deletes by moving the non-catalog related activities post commit. Hence, would really love to seek feedback first for its usage for alter database set tablespace.

Co-authored-by: Ashwin Agrawal <aagrawal@pivotal.io>
Co-authored-by: David Kimura <dkimura@pivotal.io>

## Here are some reminders before you submit the pull request
- [x] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`

### CODE REVIEW

File: src/backend/catalog/storage.c [hunk 1]
```diff
@@ -340,6 +373,16 @@ smgrDoPendingDeletes(bool isCommit)
 			/* do deletion if called for */
 			if (pending->atCommit == isCommit)
 			{
+				if (pending->dbOperation)
+				{
+					Assert(next == NULL);
+					Assert(pending->relnode.node.relNode == InvalidOid);
+					DropDatabaseDirectory(pending->relnode.node.dbNode,
```
Comment (berlin-ab) [inline src/backend/catalog/storage.c]: Seems like we should be able to get the information off of the deeply nested structure here in a way that is not so coupled to the structure. Is there a function that can give you the `dbNode` for a `PendingRelDel`? A `relnode.node.relNode` for a `PendingRelDel`?

File: src/backend/catalog/storage.c [hunk 2]
```diff
@@ -431,7 +475,8 @@ smgrGetPendingDeletes(bool forCommit, RelFileNodeWithStorageType **ptr)
 	*ptr = rptr;
 	for (pending = pendingDeletes; pending != NULL; pending = pending->next)
 	{
-		if (pending->nestLevel >= nestLevel && pending->atCommit == forCommit
+		if (pending->nestLevel >= nestLevel && pending->atCommit == forCommit &&
```
Comment (berlin-ab) [inline src/backend/catalog/storage.c]: An explaining variable, method, or macro would help the understandability of this conditional.

File: src/backend/commands/dbcommands.c [hunk 3]
```diff
@@ -1388,6 +1389,13 @@ movedb(const char *dbname, const char *tblspcname)
 	PG_END_ENSURE_ERROR_CLEANUP(movedb_failure_callback,
 								PointerGetDatum(&fparms));
 
+	/*
+	 * GPDB: GPDB uses two phase commit and pending deletes, hence cannot locally
+	 * commit here. The rest of the logic related to the non-catalog changes from
+	 * this function is extracted into DropDatabseDirectory() which is executed at
```
Comment (jimmyyih) [inline src/backend/commands/dbcommands.c]: s/DropDatabseDirectory()/DropDatabaseDirectory()/

File: src/backend/commands/dbcommands.c [hunk 4]
```diff
@@ -1404,14 +1412,43 @@ movedb(const char *dbname, const char *tblspcname)
 
 	/* Start new transaction for the remaining work; don't need a snapshot */
 	StartTransactionCommand();
+#endif
+
+	if (Gp_role == GP_ROLE_EXECUTE)
+	{
+		/*
+		 * QE needs to release session level locks as can't Prepare Transaction
```
Comment (jimmyyih) [inline src/backend/commands/dbcommands.c]: Why isn't this the case for QD as well?

Comment (l-wang) [reply src/backend/commands/dbcommands.c]: Good question. QD needs to release the session level lock as well. For the case where the transaction gets committed, the lock is released at the end of `DropDatabaseDirectory()`; For the case where the transaction gets aborted, `ProcReleaseLocks()`->`LockReleaseAll()` releases the session level locks. QE needs to release the session level locks here because otherwise will hit "ERROR:  cannot PREPARE while holding both session-level and transaction-level locks on the same object".

File: src/backend/catalog/storage.c (hunk 2 above)
Comment (l-wang) [reply src/backend/catalog/storage.c]: I would totally agree with you if this is not from upstream postgres, but leaving it as it is now probably makes it easier for future merge work.

File: src/backend/catalog/storage.c (hunk 1 above)
Comment (hlinnaka) [reply src/backend/catalog/storage.c]: It might be better to add a separate `Oid databaseId` field to `PendingRelDelete`, to store the database ID, instead of reusing the existing field and burying it in `relnode.node.relNode`.

**Comment by Eulerizeit** [comment]
On Fri, Feb 15, 2019 at 8:50 AM Heikki Linnakangas
<notifications@github.com> wrote:
>
> @hlinnaka approved this pull request.
>
> LGTM. I wonder, though, if we would be better off just disabling ALTER DATABASE SET TABLESPACE, since it's pretty late in the release cycle. I don't see anything wrong with this, though.

If we were to do that how would we be able to leverage tablespaces?
Would the assumption be then that everything was set up initially and
the locations are unchanging?

- Rob

**Comment by hlinnaka** [comment]
On 15/02/2019 17:34, Robert Eckhardt wrote:
> On Fri, Feb 15, 2019 at 8:50 AM Heikki Linnakangas
> <notifications@github.com> wrote:
>  >
>  > @hlinnaka approved this pull request.
>  >
>  > LGTM. I wonder, though, if we would be better off just disabling 
> ALTER DATABASE SET TABLESPACE, since it's pretty late in the release 
> cycle. I don't see anything wrong with this, though.
> 
> If we were to do that how would we be able to leverage tablespaces?
> Would the assumption be then that everything was set up initially and
> the locations are unchanging?

Kind of. You couldn't move a database to a different tablespace after 
creating it. So you'd have to get it right, when you CREATE DATABASE. 
You could still move individual tables with ALTER TABLE SET TABLESPACE, 
though, just not the whole database.

- Heikki

**Comment by ashwinstar** [comment]
On Fri, Feb 15, 2019 at 5:50 AM Heikki Linnakangas <notifications@github.com>
wrote:

> *@hlinnaka* approved this pull request.
>
> LGTM. I wonder, though, if we would be better off just disabling ALTER
> DATABASE SET TABLESPACE, since it's pretty late in the release cycle. I
> don't see anything wrong with this, though.
>
Thanks a lot Heikki for the review. Given the storage tiers evolving these
days seems good functionality to ship if we can. Plus, irrespective we will
have to use this logic for drop database, and we see nothing wrong with it.
I feel we should provide the functionality given we didn't even beta yet,
yes its unfortunate we didn't get to this earlier ideally during merge
itself when we got the new command. But that's the cost we have to pay
delaying dealing with fixme's.

File: src/backend/catalog/storage.c (hunk 1 above)
Comment (ashwinstar) [reply src/backend/catalog/storage.c]: Well we are not burying it in `relnode.node.relNode`, just that `relnode.node.relNode` is invalid for this case. Need to pass in tablespaceId and databaseId which are already 2 members of `node`. If we have to use separate field then need to add 2 extra Oid's variables unnecessarily.
