### PR TITLE
Make Multi-DQA on subquery work.

### LINKED ISSUE #7413: ERROR:  relation not found (OID 0)  causes GP crash
### Greenplum version or build
PostgreSQL 9.4.20 (Greenplum Database 6.0.0-beta.1 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.3.1  
### OS version and uname -a
centos 7.5
 
### Actual behavior
ERROR:  relation not found (OID 0)
DETAIL:  This can be validly caused by a concurrent delete operation on this object
### Step to reproduce the behavior
```sql
CREATE TABLE test_tab (
    dt character varying(8),
    logtimestr character varying(14),
    reqid character varying(40),
    xrealip character varying(20),
    xrealip_desc character varying(60),
    sessionvisitorid character varying(40),
    sessionvistoridnew character varying(2),
    visitorid character varying(40),
    vistoridnew character varying(2),
    ozuid character varying(20),
    halfhourfirstvisit character varying(10),
    wtoipsessionid character varying(40),
    domain character varying(40),
    url character varying(4000),
    title character varying(1000),
    referrer character varying(4000),
    cityid character varying(40),
    channelid character varying(40),
    _type character varying(8),
    page_name character varying(128),
    cfg_url character varying(4000),
    is_city_ind integer,
    next_logtime character varying(40),
    stay_time numeric,
    cid character varying(8),
    skuid character varying(8),
    session_time numeric,
    session_cnt numeric,
    total_session_time numeric
) DISTRIBUTED BY (dt ,_type ,sessionvisitorid);

SELECT
            COALESCE(SUM(pv), 0) AS pv,
            COALESCE(SUM(uv), 0) AS uv,
            COALESCE(SUM(sv), 0) AS sv,
            COALESCE(SUM(stay_sec), 0) AS stay_sec,
            COALESCE(SUM(lst_pv), 0) AS lst_pv,
            COALESCE(SUM(lst_uv), 0) AS lst_uv
        FROM
            (
                SELECT
                    SUM(
                        CASE
                            WHEN dt >= '20190402' THEN pv
                        END
                    ) pv,
                    SUM(
                        CASE
                            WHEN dt >= '20190402' THEN session_time
                        END
                    ) AS stay_sec,
                    COUNT(
                        DISTINCT CASE
                            WHEN dt >= '20190402' THEN visitorid
                        END
                    ) AS uv,
                    COUNT(
                        DISTINCT CASE
                            WHEN dt >= '20190402' THEN sessionvisitorid
                        END
                    ) AS sv,
                    SUM(
                        CASE
                            WHEN dt < '20190402' THEN pv
                        END
                    ) lst_pv,
                    COUNT(
                        DISTINCT CASE
                            WHEN dt < '20190402'
                            AND 1 = 1 THEN visitorid
                        END
                    ) AS lst_uv
                FROM
                    (
                        SELECT
                            cityid,
                            dt,
                            visitorid,
                            sessionvisitorid,
                            xrealip,
                            session_time,
                            COUNT(1) AS pv
                        FROM
                            test_tab
                        WHERE
                            1=1
                            AND dt BETWEEN '20190326'
                            AND '20190408'
                            AND cityid IS NOT NULL
                            AND is_city_ind = 1
                        GROUP BY
                            cityid,
                            dt,
                            visitorid,
                            sessionvisitorid,
                            xrealip,
                            session_time
                    ) r
                GROUP BY
                    dt,
                    cityid
            ) t
```

### PR DESCRIPTION
**Pull request by guofengrichard**
When generating plan for multi-DQA, we need to build a coplan on base of
the shared scan for each distinct DQA, and then join the coplans back
together. And while building the coplan for each DQA, the arrays for
RelOptInfo and RangeTblEntry for the PlannerInfo would be rebuild and
the original arrays would have been replaced. So, for the DQA other than
the first one, we need to restore the arrays to what they are like for
the original shared scan plan before building coplan for it.

This patch fixes #7413

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [ ] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

**Comment by adam8157** [comment]
Better explain in the comment why set_subqueryscan_references() needs the original info.

File: src/backend/cdb/cdbgroup.c [hunk 1]
```diff
@@ -1750,6 +1755,16 @@ make_three_stage_agg_plan(PlannerInfo *root, MppGroupContext *ctx)
...
 			PlannerInfo *coroot;
 
+			/*
+			 * For each distinct DQA, we need to build a coplan on base of the
+			 * shared scan plan. But for the DQA other than the first one, the
+			 * arrays for RelOptInfo and RangeTblEntry for the PlannerInfo have
+			 * been rebuilt. So we need to restore the arrays to what they are
+			 * like for the origin shared scan plan.
+			 */
+			if (i != 0)
```
Comment (berlin-ab) [inline src/backend/cdb/cdbgroup.c]: I could be missing some context, but couldn't you get rid of this conditional on 1765 and remove the memcpy on 1731?

File: src/backend/cdb/cdbgroup.c [hunk 2]
```diff
@@ -1724,6 +1724,11 @@ make_three_stage_agg_plan(PlannerInfo *root, MppGroupContext *ctx)
 		List	   *rtable = NIL;
 		List	   *coplans = NIL;
 		List	   *coroots = NIL;
+		PlannerInfo *scroot = NULL; /* PlannerInfo for shared scan */
+
+		scroot = makeNode(PlannerInfo);
+		/* shallow copy from root at first. */
+		memcpy(scroot, root, sizeof(PlannerInfo));
```
Comment (berlin-ab) [inline src/backend/cdb/cdbgroup.c]: Are there Postgres/GPDB-specific routines that would be more appropriate for dealing with memory here?

File: src/backend/cdb/cdbgroup.c (hunk 1 above)
Comment (guofengrichard) [reply src/backend/cdb/cdbgroup.c]: Hmm.. I don't think so. The memcpy on 1731 is to keep the PlannerInfo for the original shared scan plan and here we need to restore PlannerInfo before building coplan.

Comment (pengzhout) [reply src/backend/cdb/cdbgroup.c]: Should we put the reset of scroot to the behind the make_plan_for_one_dqa()? so root is not affected by the last reconstruct of coplan.

File: src/backend/cdb/cdbgroup.c (hunk 2 above)
Comment (guofengrichard) [reply src/backend/cdb/cdbgroup.c]: Not sure about that. Here just follows how `add_second_stage_agg()` shallow copies PlannerInfo.

File: src/backend/cdb/cdbgroup.c (hunk 1 above)
Comment (guofengrichard) [reply src/backend/cdb/cdbgroup.c]: I don't think it's necessary. After all the coplans have been generated, we will do another rebuild for the arrays of RelOptInfo and RangeTblEntry.

File: src/backend/cdb/cdbgroup.c (hunk 2 above)
Comment (gkokolatos) [reply src/backend/cdb/cdbgroup.c]: There is not one nor for Postgres nor for GPDB.  memcpy() is directly used consistently throughout the codebase for PlannerInfo nodes.

**Comment by guofengrichard** [comment]
> For what is worth I think the code itself is fine.
> 
> However, I would have liked to see one more distinct column on the test, to make certain that the restoration of the root node is done more than once in the loop. Also actually using the plan will be needed to make certain that we don't break things on the executor side in the future. Just populating the test table and executing the select should be sufficient.

Thank you @gkokolatos for reviewing. I have revised the test to include one more distinct column in targetlist, and also made the query be executed in the test.
