### PR TITLE
Enhancing clean up routine for workfile_set.

### LINKED ISSUE #1767: Number of concurrent spilling queries exceeded with abort subtransactions
Test case:
```
CREATE EXTERNAL WEB TABLE exttest (x int)
execute E'echo 1; echo 2; echo 3; echo bogus; echo 5'
on master
format 'text';
do $$                                    
declare                                              
  i  integer;
begin
   for i in 1..10000 loop
     begin
       select * from exttest a, exttest b;
     exception when others then
       raise notice 'caught exception: %', sqlerrm;
     end;
   end loop;
end;
$$ language plpgsql;
```

After running that for a while, it produces an (unexpected) error:
```
...
NOTICE:  caught exception: invalid input syntax for integer: "bogus"
NOTICE:  caught exception: invalid input syntax for integer: "bogus"
NOTICE:  caught exception: invalid input syntax for integer: "bogus"
NOTICE:  caught exception: invalid input syntax for integer: "bogus"
NOTICE:  caught exception: could not create workfile manager entry: exceeded number of concurrent spilling queries
NOTICE:  caught exception: could not create workfile manager entry: exceeded number of concurrent spilling queries
...
```

The syntax errors are expected, but the "could not create workfile manager entry" errors are not. The workfiles should be cleaned up on subtransaction abort.

### PR DESCRIPTION
**Pull request by karthijrk**
Earlier `workfile_set` gets cleaned up only at the top transaction level.  If we
have a lot of sub-transaction, we found that we couldn't create more
`workfile_set` in shared memory. So we used resource owner to clean up
the `workfile_set` at the respective transaction level itself.

Thanks to Robert Mu <dbx_c@hotmail.com> for coming up with the initial
fix through the PR #2325.

This would resolve #1767

Signed-off-by: Karthikeyan Jambu Rajaraman <karthi.jrk@gmail.com>

### CODE REVIEW

**Comment by vraghavan78** [comment]
Please add a test.

File: src/backend/utils/resowner/resowner.c [hunk 1]
```diff
@@ -1058,3 +1058,8 @@ PrintFileLeakWarning(File file)
 		 "temporary file leak: File %d still referenced",
 		 file);
 }
+
+const char* ResourceOwnerName(ResourceOwner owner)
```
Comment (hlinnaka) [inline src/backend/utils/resowner/resowner.c]: Adding this seems like overkill for what's just a "can't happen" check.

File: src/backend/utils/workfile_manager/workfile_mgr.c [hunk 2]
```diff
@@ -49,6 +49,65 @@ static StringInfo get_name_from_nodeType(const NodeTag node_type);
...
+						curr, ResourceOwnerName(curr->owner), ResourceOwnerName(CurrentResourceOwner));
+			}
+			else
+				/*
+				 * In the general case, since sub-transactions follow a stack-like
+				 * pattern, we can break when we find a workfile_set whose resource
+				 * owner is not the CurrentResourceOwner. Our parent transaction
+				 * should clean that up.
+				 */
+				break;
```
Comment (hlinnaka) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: Let's not rely on that here. We don't rely on it anywhere else, AFAIK. This isn't performance-critical.

File: src/backend/utils/workfile_manager/workfile_mgr.c [hunk 3]
```diff
@@ -49,6 +49,65 @@ static StringInfo get_name_from_nodeType(const NodeTag node_type);
...
+			{
+				/*
+				 * This case was intended to be a fallback in case there are any
+				 * workfile_sets left in open_workfile_sets whose resource owner
+				 * is not the CurrentResourceOwner. But, we don’t expect this
+				 * to occur in practice and thus want to catch that here.
+				 */
+				Assert(curr->owner);
+				Assert(CurrentResourceOwner)
+				elog(ERROR, "Found workset object %p whose resource owner '%s' is not"
```
Comment (hlinnaka) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: Throwing an ERROR during abort processing seems like a bad idea.

We don't have checks like this in any other resource-owner callbacks. I'd suggest following the example, and just leave this out.

Comment (karthijrk) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: You are right. Let me change based on your comments.

**Comment by karthijrk** [comment]
@hlinnaka I think I addressed all your comments. Let me know what do you thin.

File: src/backend/utils/workfile_manager/workfile_mgr.c [hunk 4]
```diff
@@ -441,6 +488,13 @@ void
 workfile_mgr_close_set(workfile_set *work_set)
 {
 	Assert(work_set!=NULL);
+	/* Although work_set is in shared memory only this process has access to it */
```
Comment (hlinnaka) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: Is this comment accurate, does work_set really point to shared memory? (I believe it's not)

Comment (karthijrk) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: Yes, it is in shared memory. We create the workset by acquiring the cache entry.
```
workfile_set *
workfile_mgr_create_set(enum ExecWorkFileType type, bool can_be_reused, PlanState *ps)
...........

CacheEntry *newEntry = Cache_AcquireEntry(workfile_mgr_cache, &set_info);

```
`Cache_AcquireEntry` will acquire the entry from `workfile_mgr_cache` to create workset. This workfile_mgr_cache is in shared memory with 8192 entries. That's why in the original issue, when we run in a loop for 10,000 times, towards the end we ran out of entries in the cache.

Comment (karthijrk) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: So, I will push it for now. But if you feel that we need to change it, I will make appropriate modification and push the updates.

Comment (hlinnaka) [inline src/backend/utils/workfile_manager/workfile_mgr.c]: That is scary as hell. To sum it up, some of the fields stored in the shared memory struct are pointers to backend-private memory, and we rely on the fact that no-one else should be accessing those fields while our backend holds the lease on the workfile_set object. That is a highly unusual arrangements, the comments would need to point that out much more strongly, at the very least.

I think it would be much more clear to introduce a new struct along the lines of:
```
struct workfile_set_lease
{
  workfile_set *set; /* the shared memory object */
  
  ResourceOwner owner;
  struct workfile_set *next;
  struct workfile_set *prev;
};
```

And hold those in backend-private memory.
