### PR TITLE
Allocate histogram sample array on heap

### LINKED ISSUE #16021: histogram stack buffer overflow
gpdb 7.0, build with address sanitizer

```
=================================================================
==564280==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd3007a660 at pc 0x0000011d48b7 bp 0x7ffd30076230 sp 0x7ffd30076228
WRITE of size 8 at 0x7ffd3007a660 thread T0
    #0 0x11d48b6 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2089:25
    #1 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #2 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #3 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #4 0x11d48f9 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2091:2
    #5 0x11d48f9 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2091:2
    #6 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #7 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #8 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #9 0x11d4939 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int) /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2092:2
    #10 0x11d4ea0 in gpnaucrates::CHistogram::ComputeSkew() /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2128:2
    #11 0x120cadc in gpnaucrates::CHistogram::GetSkew() /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/../../../../../../src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h:387:4
    #12 0x1202cfd in gpnaucrates::CStatistics::GetSkew(unsigned int) const /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp:208:20
    #13 0x1493623 in gpopt::CPhysical::GetSkew(gpnaucrates::IStatistics*, gpopt::CDistributionSpec*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/operators/CPhysical.cpp:857:31
    #14 0xf83726 in gpdbcost::CCostModelGPDB::CostHashJoin(gpos::CMemoryPool*, gpopt::CExpressionHandle&, gpdbcost::CCostModelGPDB const*, gpopt::ICostModel::SCostingInfo const*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp:1061:20
    #15 0xf9493f in gpdbcost::CCostModelGPDB::Cost(gpopt::CExpressionHandle&, gpopt::ICostModel::SCostingInfo const*) const /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp:2154:11
    #16 0x12be906 in gpopt::CCostContext::CostCompute(gpos::CMemoryPool*, gpos::CDynamicPtrArray<gpopt::CCost, &(void gpos::CleanupDelete<gpopt::CCost>(gpopt::CCost*))>*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/base/CCostContext.cpp:709:14
    #17 0x1562430 in gpopt::CGroupExpression::CostCompute(gpos::CMemoryPool*, gpopt::CCostContext*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CGroupExpression.cpp:577:20
    #18 0x1561f27 in gpopt::CGroupExpression::PccComputeCost(gpos::CMemoryPool*, gpopt::COptimizationContext*, unsigned int, gpos::CDynamicPtrArray<gpopt::COptimizationContext, &(void gpos::CleanupRelease<gpopt::COptimizationContext>(gpopt::COptimizationContext*))>*, bool, gpopt::CCost) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CGroupExpression.cpp:455:17
    #19 0x159eff3 in gpopt::CJobGroupExpressionOptimization::EevtOptimizeSelf(gpopt::CSchedulerContext*, gpopt::CJob*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CJobGroupExpressionOptimization.cpp:631:11
    #20 0x15a2716 in gpopt::CJobStateMachine<gpopt::CJobGroupExpressionOptimization::EState, (gpopt::CJobGroupExpressionOptimization::EState)6, gpopt::CJobGroupExpressionOptimization::EEvent, (gpopt::CJobGroupExpressionOptimization::EEvent)6>::FRun(gpopt::CSchedulerContext*, gpopt::CJob*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/../../../../../../src/backend/gporca/libgpopt/include/gpopt/search/CJobStateMachine.h:162:21
    #21 0x15a1e87 in gpopt::CJobGroupExpressionOptimization::FExecute(gpopt::CSchedulerContext*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CJobGroupExpressionOptimization.cpp:699:15
    #22 0x15c67bf in gpopt::CScheduler::FExecute(gpopt::CJob*, gpopt::CSchedulerContext*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CScheduler.cpp:307:20
    #23 0x15c5f22 in gpopt::CScheduler::ExecuteJobs(gpopt::CSchedulerContext*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CScheduler.cpp:123:21
    #24 0x15c5d58 in gpopt::CScheduler::Run(void*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/search/CScheduler.cpp:95:17
    #25 0x137166b in gpopt::CEngine::Optimize() /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/engine/CEngine.cpp:1710:3
    #26 0x1525641 in gpopt::COptimizer::PexprOptimize(gpos::CMemoryPool*, gpopt::CQueryContext*, gpos::CDynamicPtrArray<gpopt::CSearchStage, &(void gpos::CleanupDelete<gpopt::CSearchStage>(gpopt::CSearchStage*))>*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/optimizer/COptimizer.cpp:422:6
    #27 0x1524ba7 in gpopt::COptimizer::PdxlnOptimize(gpos::CMemoryPool*, gpopt::CMDAccessor*, gpdxl::CDXLNode const*, gpos::CDynamicPtrArray<gpdxl::CDXLNode, &(void gpos::CleanupRelease<gpdxl::CDXLNode>(gpdxl::CDXLNode*))> const*, gpos::CDynamicPtrArray<gpdxl::CDXLNode, &(void gpos::CleanupRelease<gpdxl::CDXLNode>(gpdxl::CDXLNode*))> const*, gpopt::IConstExprEvaluator*, unsigned int, unsigned int, unsigned int, gpos::CDynamicPtrArray<gpopt::CSearchStage, &(void gpos::CleanupDelete<gpopt::CSearchStage>(gpdxl::CDXLNode*))>*, gpopt::COptimizerConfig*, char const*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpopt/src/optimizer/COptimizer.cpp:318:29
    #28 0x185f9f7 in COptTasks::OptimizeTask(void*) /home/fsh/dev/oushudb6.0/src/backend/gpopt/utils/COptTasks.cpp:560:15
    #29 0xf67463 in gpos::CTask::Execute() /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpos/src/task/CTask.cpp:130:12
    #30 0xf6dab9 in gpos::CWorker::Execute(gpos::CTask*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpos/src/task/CWorker.cpp:80:11
    #31 0xf62bae in gpos::CAutoTaskProxy::Execute(gpos::CTask*) const /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpos/src/task/CAutoTaskProxy.cpp:286:11
    #32 0xf7300d in gpos_exec(gpos_exec_params*) /home/fsh/dev/oushudb6.0/src/backend/gporca/libgpos/src/_api.cpp:237:9
    #33 0x185bbe7 in COptTasks::Execute(void* (*)(void*), void*) /home/fsh/dev/oushudb6.0/src/backend/gpopt/utils/COptTasks.cpp:232:10
    #34 0x1861f83 in COptTasks::GPOPTOptimizedPlan(Query*, SOptContext*) /home/fsh/dev/oushudb6.0/src/backend/gpopt/utils/COptTasks.cpp:757:2
    #35 0x1864288 in CGPOptimizer::GPOPTOptimizedPlan(Query*, bool*) /home/fsh/dev/oushudb6.0/src/backend/gpopt/CGPOptimizer.cpp:58:12
    #36 0x186527c in GPOPTOptimizedPlan(Query*, bool*) /home/fsh/dev/oushudb6.0/src/backend/gpopt/CGPOptimizer.cpp:233:9
    #37 0xbfda51 in optimize_query(Query*, int, ParamListInfoData*) /home/fsh/dev/oushudb6.0/src/backend/optimizer/plan/orca.c:156:11
    #38 0xbeaa8d in standard_planner(Query*, int, ParamListInfoData*) /home/fsh/dev/oushudb6.0/src/backend/optimizer/plan/planner.c:374:12
    #39 0xbea9fa in planner(Query*, int, ParamListInfoData*) /home/fsh/dev/oushudb6.0/src/backend/optimizer/plan/planner.c:329:12
    #40 0xce7d1e in pg_plan_query(Query*, int, ParamListInfoData*) /home/fsh/dev/oushudb6.0/src/backend/tcop/postgres.c:1016:9
    #41 0xa51d14 in ExplainOneQuery(Query*, int, IntoClause*, ExplainState*, char const*, ParamListInfoData*, QueryEnvironment*) /home/fsh/dev/oushudb6.0/src/backend/commands/explain.c:508:10
    #42 0xa517eb in ExplainQuery(ParseState*, ExplainStmt*, char const*, ParamListInfoData*, QueryEnvironment*, _DestReceiver*) /home/fsh/dev/oushudb6.0/src/backend/commands/explain.c:299:4
    #43 0xcf1d53 in standard_ProcessUtility(PlannedStmt*, char const*, ProcessUtilityContext, ParamListInfoData*, QueryEnvironment*, _DestReceiver*, char*) /home/fsh/dev/oushudb6.0/src/backend/tcop/utility.c:806:4
    #44 0xcf18a8 in ProcessUtility(PlannedStmt*, char const*, ProcessUtilityContext, ParamListInfoData*, QueryEnvironment*, _DestReceiver*, char*) /home/fsh/dev/oushudb6.0/src/backend/tcop/utility.c:401:4
    #45 0xcf11db in PortalRunUtility(PortalData*, PlannedStmt*, bool, bool, _DestReceiver*, char*) /home/fsh/dev/oushudb6.0/src/backend/tcop/pquery.c:1384:2
    #46 0xcf011c in FillPortalStore(PortalData*, bool) /home/fsh/dev/oushudb6.0/src/backend/tcop/pquery.c:1253:4
    #47 0xcefde9 in PortalRun(PortalData*, long, bool, bool, _DestReceiver*, _DestReceiver*, char*) /home/fsh/dev/oushudb6.0/src/backend/tcop/pquery.c:980:6
    #48 0xcee624 in exec_simple_query(char const*) /home/fsh/dev/oushudb6.0/src/backend/tcop/postgres.c:1921:10
    #49 0xce9ac6 in PostgresMain(int, char**, char const*, char const*) /home/fsh/dev/oushudb6.0/src/backend/tcop/postgres.c
    #50 0xc45a87 in BackendRun(Port*) /home/fsh/dev/oushudb6.0/src/backend/postmaster/postmaster.c:5012:2
    #51 0xc44e24 in BackendStartup(Port*) /home/fsh/dev/oushudb6.0/src/backend/postmaster/postmaster.c:4689:3
    #52 0xc44e24 in ServerLoop() /home/fsh/dev/oushudb6.0/src/backend/postmaster/postmaster.c:2005:7
    #53 0xc41be8 in PostmasterMain(int, char**) /home/fsh/dev/oushudb6.0/src/backend/postmaster/postmaster.c:1631:11
    #54 0xb682ba in main /home/fsh/dev/oushudb6.0/src/backend/main/main.c:240:3
    #55 0x7fef6e902554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    #56 0x7c6607 in _start (/usr/local/gpdb/bin/postgres+0x7c6607)

Address 0x7ffd3007a660 is located in stack of thread T0 at offset 16320 in frame
    #0 0x11d494f in gpnaucrates::CHistogram::ComputeSkew() /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2107

  This frame has 12 object(s):
    [32, 40) 'coerce'
    [64, 8064) 'samples' (line 2123)
    [8320, 16320) 'sample_rate' (line 2124) <== Memory access at offset 16320 overflows this variable
    [16576, 16584) 'accumulated_freq' (line 2134)
    [16608, 16616) 'ref.tmp' (line 2138)
    [16640, 16648) 'ref.tmp25' (line 2147)
    [16672, 16680) 'ref.tmp26' (line 2147)
    [16704, 16712) 'ref.tmp27' (line 2147)
    [16736, 16744) 'ref.tmp35' (line 2150)
    [16768, 16776) 'ref.tmp36' (line 2150)
    [16800, 16808) 'ref.tmp66' (line 2172)
    [16832, 16840) 'ref.tmp68' (line 2176)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/fsh/dev/oushudb6.0/src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2089:25 in gpnaucrates::CHistogram::GetSampleRate(double, double, double*, unsigned int)
Shadow bytes around the buggy address:
  0x100026007470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100026007480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100026007490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000260074a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000260074b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1000260074c0: 00 00 00 00 00 00 00 00 00 00 00 00[f2]f2 f2 f2
  0x1000260074d0: f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x1000260074e0: f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f8 f2 f2 f2
  0x1000260074f0: f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
  0x100026007500: f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f3 f3 f3
  0x100026007510: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==564280==ABORTING

```

```
DOUBLE sample_rate[GPOPT_SKEW_SAMPLE_SIZE];

if (index >= GPOPT_SKEW_SAMPLE_SIZE)
{
	return;
}

// if index is equal to GPOPT_SKEW_SAMPLE_SIZE - 1, this assignment will cause stack buffer overflow.
sample_rate[index + 1] = (left + right) / 2;
```

### PR DESCRIPTION
**Pull request by THANATOSLAVA**
Issue:
Sample array used for skew stats collection caused stack overflow in address sanitizer environment.

Solution:
Allocate the array on heap memory. Also simplified the math in the sample rate populator for better readability.

Fix #16021

### CODE REVIEW

File: src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp [hunk 1]
```diff
@@ -2079,17 +2079,15 @@ void
 CHistogram::GetSampleRate(DOUBLE left, DOUBLE right, DOUBLE *sample_rate,
 						  ULONG index)
 {
-	GPOS_CHECK_STACK_SIZE;
-
 	if (index >= GPOPT_SKEW_SAMPLE_SIZE)
```
Comment (gpopt) [inline src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2082]: Still >=?

**Comment by THANATOSLAVA** [comment]
> Hi @THANATOSLAVA, I understood the changes and just curious to know how are we evaluated these changes

The way I see it is, since this is memory related, so first is passing all the memory pool/ref count checks in ctests and ensuring no query falls back in regression, which can also be due to leaks. After that, we rely on all the reviewers.

I think we might not have as good test coverage in stack allocations as we do on heap. That's probably why accessing outside the array bounds wasn't detected in the first place. I also realized the right thing to do is to ask around before scrambling up something new. It does appear all the data structures and utilities that I've needed have already been created.

File: src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp [hunk 2]
```diff
@@ -2079,17 +2079,15 @@ void
 CHistogram::GetSampleRate(DOUBLE left, DOUBLE right, DOUBLE *sample_rate,
 						  ULONG index)
 {
-	GPOS_CHECK_STACK_SIZE;
```
Comment (khannaekta) [inline src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2082]: why did we remove this?

Comment (THANATOSLAVA) [reply src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2082]: My understanding is this was needed for the thousand element samples array allocated on stack. Now the array is allocated on heap, so I removed the stack size check. Am I missing something?

Comment (khannaekta) [reply src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2082]: I see, that makes sense. But, since we also recurse this function we would still want to guard against stack overflow for the recursion.

Comment (gpopt) [reply src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2082]: We usually need it for recursive call. So I guess it is better to keep it.

Comment (THANATOSLAVA) [reply src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2082]: Gotcha. Lemme add it back.

File: src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp [hunk 3]
```diff
@@ -2086,10 +2086,10 @@ CHistogram::GetSampleRate(DOUBLE left, DOUBLE right, DOUBLE *sample_rate,
 		return;
 	}
 
-	sample_rate[index + 1] = (left + right) / 2;
+	sample_rate[index] = (left + right) / 2;
```
Comment (gpopt) [inline src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2089]: Can you explain why the index here and in L2091, L2127 changed?

Comment (THANATOSLAVA) [reply src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp:2089]: `GetSampleRate` populates a 1000-element array. It uses the existing elements as lower/higher bounds and appends the medium as the next element. The first two elements are predefined as 0 and 1. The function populates the 3rd element onward. The array goes:

0,  1,  0.5,  0.25,  0.75,  0.125,  0.375,  0.625,  0.875, ... 

Previously, we recursively assign the value for `sample_rate[index+1]`. Since we start from the 3rd element, on line 2127 we pass in `index = 1`, so the 3rd element becomes `sample_rate[1+1] = 0.5`. The next two elements to be populated are the 4th and 5th element. Therefore, we pass `index*2` to the first recursive call, and `index*2+1` to the second recursive call. The first recursive call populates the 4th element `sample_rate[1*2+1] = 0.25`, and the second recursive call populates the 5th element `sample_rate[1*2+1+1] = 0.75`.

I realized having `sample_rate[index+1]` on the left side of the equation is less intuitive and thence error prone (accessing address outside array bounds). So I changed it to `sample_rate[index]`. Accordingly, on line 2127 I pass in `index = 2`, so the 3rd element becomes `sample_rate[2] = 0.5`. Going forward, we pass `index*2-1` and `index*2` to the two recursive calls. The first recursive call populates the 4th element `sample_rate[2*2-1] = 0.25`, and the second recursive call populates the 5th element `sample_rate[2*2] = 0.75`.

**Review by gpopt — APPROVED** [review]
+1
It would be nice if you can explain the index changes in the commit messages.

**Review by khannaekta — APPROVED** [review]
LGTM!
