### PR TITLE
ORCA: Fix CreateStatsPredDisj with an ArrayCmpALL disjunct

### LINKED ISSUE #12792: ORCA generates incorrect cardinality estimation if filter contains OR and ALL
### Greenplum version or build
master, 6X_STABLE

### Expected behavior
```sql
create table t (a int, b int);
insert into t select i % 10 from generate_series(1, 100000)i;
analyze t;

explain select * from t where a is null; -- estimates 1 row
explain select * from t where a <> ALL ('{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}'::int[]); -- estimates 1 row
explain select * from t where a is null or a <> ALL ('{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}'::int[]); -- should also estimate 1 row, but estimated 100000 rows.
```

### Actual behavior
```
postgres=# explain select * from t where a is null or a <> ALL ('{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}'::int[]);
                                     QUERY PLAN                                      
-------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..436.27 rows=100000 width=8)
   ->  Seq Scan on t  (cost=0.00..433.29 rows=33334 width=8)
         Filter: ((a IS NULL) OR (a <> ALL ('{0,1,2,3,4,5,6,7,8,9,10}'::integer[])))
 Optimizer: Pivotal Optimizer (GPORCA)
(4 rows)
```

### PR DESCRIPTION
**Pull request by l-wang**
Previously, in CreateStatsPredDisj, if one of the filter's child expression is
an CScalarArrayCmp of type EarrcmpAll, we directly append the CStatsPred of
each ArrayCmp element into the result pred stats array for the parent filter.
While this works if the parent filter is a conjunctive filter, as it flattens
the result conjunctive pred stats array, this generates incorrect result pred
stats for a disjunctive filter.

For example, for the following predicate expression:

a is NULL OR a <> ALL  ('{0, 1, 2}'::int[])

with the previous logic, we would create a disjunctive pred stats for:

a is NULL OR a <> 0 OR a <> 1 OR a <> 2

This patch fixes the problem by creating a new conjunctive pred stats array
only for the ArrayCmpAll expression, and append it to the final disjunctive
pred stats array. So after the fix, we get a disjunctive pred stats for:

a is NULL OR (a <> 0 AND a <> 1 AND a <>2)

Fixes #12792.

### CODE REVIEW

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp [hunk 1]
```diff
@@ -670,7 +670,20 @@ CStatsPredUtils::CreateStatsPredDisj(CMemoryPool *mp,
 			continue;
 		}
 
-		AddSupportedStatsFilters(mp, pred_stats_disj_child, expr, outer_refs);
+		if (COperator::EopScalarArrayCmp == expr->Pop()->Eopid() &&
```
Comment (hardikar) [inline src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:673]: Shouldn't this case be handled inside `AddSupportedStatsFilters()`? There is already an if-check there for ArrayCmps, which takes it to `ProcessArrayCmp()`. Sorry, I didn't take a deep look, so please tell me if I'm wrong.

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp [hunk 2]
```diff
@@ -670,7 +670,20 @@ CStatsPredUtils::CreateStatsPredDisj(CMemoryPool *mp,
...
+				CScalarArrayCmp::PopConvert(expr->Pop())->Earrcmpt())
+		{
+			CStatsPredPtrArry *pred_stats = GPOS_NEW(mp) CStatsPredPtrArry(mp);
+			AddSupportedStatsFilters(mp, pred_stats, expr, outer_refs);
+			pred_stats_disj_child->Append(GPOS_NEW(mp)
+											  CStatsPredConj(pred_stats));
+		}
+		else
+		{
+			AddSupportedStatsFilters(mp, pred_stats_disj_child, expr,
```
Comment (hardikar) [inline src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:684]: Any other case that could cause us trouble? A nested disjunction (although we usually collapse that)?

**Review by hardikar — COMMENTED** [review]
Nice catch! I'm very glad you were able to get to the bottom of this! The code & logic LGTM, only I'm not sure it's in the right place, so please confirm either way.

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp (hunk 1 above)
Comment (khannaekta) [reply src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:673]: The codepath `AddSupportedStatsFilters()->ProcessArrayCmp()` is called from 2 functions `CreateStatsPredDisj()` and `CreateStatsPredConj()`.
In case of `conj`, AddSupportedStatsFilters() does the right thing by flattening the result conjunctive pred stats array,
its only in the case of `disj` that we don't want it to flatten and `AND` it with the other preds. Since, there isn't anyway to know in `AddSupportedStatsFilters()->ProcessArrayCmp()` whether it's being called from `CreateStatsPredDisj()` or `CreateStatsPredConj()`, the logic seems better to be here.

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp (hunk 2 above)
Comment (khannaekta) [reply src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:684]: Did try a couple of tests with nested disjunction and seems to be doing the right thing. Also have a minidump test `Nested-Or-Predicates.mdp` which should cover it.

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp (hunk 1 above)
Comment (l-wang) [reply src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:673]: What @khannaekta said was exactly the reason why I put the logic here.

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp (hunk 2 above)
Comment (l-wang) [reply src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:684]: Right, previously I tried a couple of nested disjunction queries as well, we seem to flatten nested expressions during PexprPreprocess. I did not locate the exact preprocess step which did that though, might be worthwhile to confirm.

**Review by khannaekta — APPROVED** [review]
LGTM!

File: src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp (hunk 2 above)
Comment (l-wang) [reply src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp:684]: I looked more into this. Nested ORs are always flattened. This is done from the Postgres side during constant folding right before we invoke ORCA. Specifically, `simplify_or_arguments()` is the function that does the job.

**Review by sambitesh — APPROVED** [review]

**Comment by l-wang** [comment]
Thank you all for reviewing.
