### PR TITLE
Fix assertion when creating unique index on tables created in utility…

### LINKED ISSUE #5880: Create temp table with primary key will panic in utility mode
### Greenplum version or build
Master

```
$ PGOPTIONS='-c gp_session_role=utility' psql
psql (9.3beta1)
Type "help" for help.

gpadmin=# create temp table t1 ( id int primary key );
FATAL:  Unexpected internal error (cdbcat.c:633)
DETAIL:  FailedAssertion("!(bms_membership(polbm) != BMS_EMPTY_SET)", File: "cdbcat.c", Line: 633)
```

### PR DESCRIPTION
**Pull request by pengzhout**
… mode

checkPolicyForUniqueIndex() checks if distribution key conflict with unique/primary
key, for example, unique index is not allowed for random-distributed table and
allowed for replicated-distributed table, for normal distributed, the set of
columns being indexed should be a superset of the table.

What about entry-distributed table? (eg, table created in utility mode, it has
no records in gp_distribution_policy and GpPolicyFetch translated it to
entry-distributed)? Such tables are localized in a single db, so adding a unique
index should also be allowed.

This is spotted by the assertion in checkPolicyForUniqueIndex() when checking
the conflict for normal distributed tables.

This fixes #5880

## Here are some reminders before you submit the pull request
- [ ] Add tests for the change
- [ ] Document changes
- [ ] Communicate in the mailing list if needed
- [x] Pass `make installcheck`
- [ ] Review a PR in return to support the community

### CODE REVIEW

File: src/test/isolation2/sql/misc.sql [hunk 1]
```diff
@@ -0,0 +1,9 @@
+--
```
Comment (xiong-gang) [inline src/test/isolation2/sql/misc.sql]: I think it's better to rename the file name to something more meaningful.

**Comment by xiong-gang** [comment]
LGTM

**Comment by guofengrichard** [comment]
+1 Glad to see that issue being fixed.

File: src/test/isolation2/sql/misc.sql (hunk 1 above)
Comment (pivotal-ning-yu) [reply src/test/isolation2/sql/misc.sql]: +1 to Gang's suggestion

Comment (pengzhout) [reply src/test/isolation2/sql/misc.sql]: misc.sql means we can have a place to put miscellaneous short and not categorizable test cases which need an isolation framework, for the PR only, it might be no sense, but for a long term it should be useful. Any idea?

**Comment by pengzhout** [comment]
Merged, thanks for the review.
