### PR TITLE
brin ao/co: Summarization/desummarization improvements

### LINKED ISSUE #14836: brin_summarize_new_values() takes very long to run for AO table
### Greenplum version or build
7X

### Expected behavior
Efficient running of `brin_summarize_new_values()` is crucial for BRIN index usage

### Actual behavior
This is crucial function for BRIN working. Regular inserts doesn't keep the BRIN index updated. Using `brin_summarize_new_values()` one can summarize the values.

### Step to reproduce the behavior

```sql
drop table t_list;
create table t_list as select generate_series(1,100000000) id;
drop table if exists table_ao_brin;
create table table_ao_brin (id int, descr text, created_at timestamp) using ao_row with (compresstype=zstd);
CREATE INDEX table_ao_brin_idx_created_at ON table_ao_brin USING brin(created_at) with (pages_per_range=10);
insert into table_ao_brin select id, 'test ' || id, '2012-01-01 0:00'::timestamptz + id * interval '2 sec' from t_list;
analyze table_ao_brin;
select brin_summarize_new_values('table_ao_brin_idx_created_at');
```

`brinsummarize()` has loop `for (; startBlk < heapNumBlocks; startBlk += pagesPerRange)`. In above repro - `heapNumBlocks=33555450`. It extracts it based on `brin_ao_tid_ranges()`, which seems to be using last sequence value from gp_fastsequence table to calculate the nblocks return value

### PR DESCRIPTION
**Pull request by soumyadeep2007**
This contains 3 patches:
1. Fixes specific range summarization for AO/CO tables
2. Fixes specific range desummarization for AO/CO tables (utility mode only for now .. MPP version later)
3. Introduces partial scans support for AO/CO tables (fixes  #14836)

Please review commits individually.

Dev pipeline :https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/partial_scan

### CODE REVIEW

**Comment by soumyadeep2007** [comment]
Force-pushed some optimized changes, that makes hole handling much simpler.

**Comment by soumyadeep2007** [comment]
Force-pushed changes to tests so that they are stronger (both in terms of asserting correctness and efficiency) and more transparent to the reader.

**Comment by haolinw** [comment]
There was a compiler warning (not by this PR)
```c
brin_revmap.c: In function ‘revmap_physical_extend’:
brin_revmap.c:804:27: warning: ‘mapBlk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  804 |                 if (!isAO && BufferGetBlockNumber(buf) != mapBlk)
      |                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

File: src/backend/access/aocs/aocsam.c [hunk 1]
```diff
@@ -638,6 +658,59 @@ aocs_rescan(AOCSScanDesc scan)
...
+
+		/* Open segfiles for the given segno for each col the first time through. */
+		if (!open_scan_seg(scan, fsInfoIdx))
+		{
+			/* target segment is empty/awaiting-drop */
+			return false;
+		}
+	}
+
+	ds = scan->columnScanInfo.ds[colIdx];
```
Comment (haolinw) [inline src/backend/access/aocs/aocsam.c:699]: Seems it should be `ds = scan->columnScanInfo.ds[scan->columnScanInfo.proj_attrs[colIdx]];`

Comment (soumyadeep2007) [reply src/backend/access/aocs/aocsam.c]: You are absolutely right. `columnScanInfo.ds` is always of size `relnatts`. Made your change and the test case passes. Many many thanks for testing and fixing!

File: src/backend/access/aocs/aocsam_handler.c [hunk 2]
```diff
@@ -1847,13 +1850,94 @@ aoco_index_build_range_scan(Relation heapRelation,
...
+																start_blockno,
+																columnGroupNo,
+																&dirEntry,
+																&fsInfoIdx))
+			{
+				/*
+				 * Since we found a block directory entry at/prior to the
+				 * start_blockno, we can attempt to jump ahead.
+				 */
+				if (!aocs_positionscan(aocoscan, &dirEntry, colIdx, fsInfoIdx))
```
[the remark this answers is not in the document]
Comment (soumyadeep2007) [reply src/backend/access/aocs/aocsam_handler.c:1905]: Applied your fix.

**Comment by soumyadeep2007** [comment]
> There was a compiler warning (not by this PR)
> 
> ```c
> brin_revmap.c: In function ‘revmap_physical_extend’:
> brin_revmap.c:804:27: warning: ‘mapBlk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
>   804 |                 if (!isAO && BufferGetBlockNumber(buf) != mapBlk)
>       |                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

Hmm very strange. I have `-Werror=maybe-uninitialized` in my CFLAGS and I'm using gcc 11.3 and this never shows up. We don't get this in CI either.

**Comment by haolinw** [comment]
> > There was a compiler warning (not by this PR)
> > ```c
> > brin_revmap.c: In function ‘revmap_physical_extend’:
> > brin_revmap.c:804:27: warning: ‘mapBlk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> >   804 |                 if (!isAO && BufferGetBlockNumber(buf) != mapBlk)
> >       |                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > ```
> 
> Hmm very strange. I have `-Werror=maybe-uninitialized` in my CFLAGS and I'm using gcc 11.3 and this never shows up. We don't get this in CI either.
> 
> Can you share your compiler and CFLAGS settings?

Ah, I'm using a different CFLAGS other than normal:
`./configure --prefix="/home/gpadmin/local/gpdb" --with-perl --with-python --with-libxml --disable-orca --enable-debug --enable-cassert &&  sed -i 's/-O3/-Og -Wmaybe-uninitialized/g' src/Makefile.global`
my gcc version is 7.3.0

I'm OK either fixing it like current or no fix to be consistent with Upstream. It is a false alarm, sorry.

**Comment by haolinw** [comment]
> > There was a compiler warning (not by this PR)
> > ```c
> > brin_revmap.c: In function ‘revmap_physical_extend’:
> > brin_revmap.c:804:27: warning: ‘mapBlk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> >   804 |                 if (!isAO && BufferGetBlockNumber(buf) != mapBlk)
> >       |                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > ```
> 
> Hmm very strange. I have `-Werror=maybe-uninitialized` in my CFLAGS and I'm using gcc 11.3 and this never shows up. We don't get this in CI either.
> 
> Can you share your compiler and CFLAGS settings?

Ah, I'm using a different CFLAGS other than normal:
`./configure --prefix="/home/gpadmin/local/gpdb" --with-perl --with-python --with-libxml --disable-orca --enable-debug --enable-cassert &&  sed -i 's/-O3/-Og -Wmaybe-uninitialized/g' src/Makefile.global`
my gcc version is 7.3.0

I'm OK either fixing it like current or no fix to be consistent with Upstream. It is a false alarm, sorry.

**Comment by haolinw** [comment]
> > There was a compiler warning (not by this PR)
> > ```c
> > brin_revmap.c: In function ‘revmap_physical_extend’:
> > brin_revmap.c:804:27: warning: ‘mapBlk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> >   804 |                 if (!isAO && BufferGetBlockNumber(buf) != mapBlk)
> >       |                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > ```
> 
> Hmm very strange. I have `-Werror=maybe-uninitialized` in my CFLAGS and I'm using gcc 11.3 and this never shows up. We don't get this in CI either.
> 
> Can you share your compiler and CFLAGS settings?

Ah, I'm using a different CFLAGS other than normal:
`./configure --prefix="/home/gpadmin/local/gpdb" --with-perl --with-python --with-libxml --disable-orca --enable-debug --enable-cassert &&  sed -i 's/-O3/-Og -Wmaybe-uninitialized/g' src/Makefile.global`
my gcc version is 7.3.0

I'm OK either fixing it like current or no fix to be consistent with Upstream. It is a false alarm, sorry.

**Comment by haolinw** [comment]
I've no more comments, code looks pretty!

**Review by haolinw — APPROVED** [review]

**Comment by soumyadeep2007** [comment]
Squashed and rebased against latest main.

File: src/backend/access/appendonly/appendonlyam_handler.c [hunk 3]
```diff
@@ -1613,18 +1618,84 @@ appendonly_index_build_range_scan(Relation heapRelation,
...
+		else
+		{
+			/*
+			 * We were unable to find a block directory row
+			 * encompassing/preceding the start block. This represents an edge
+			 * case where the start block of the range maps to a hole at the
+			 * very beginning of the segfile (and before the first minipage
+			 * entry of the first minipage corresponding to this segfile).
+			 *
+			 * Do nothing in this case. The scan will start anyway from the first
```
Comment (ashwinstar) [inline src/backend/access/appendonly/appendonlyam_handler.c:1693]: Would be good to have reference to where this code is for make happen "scan will start anyway from the first row present in the segfile"

File: src/include/access/appendonlytid.h [hunk 4]
```diff
@@ -94,6 +94,15 @@ typedef struct AOTupleId
  */
 #define AOHeapBlockGet_startHeapBlock(heapBlk)	((heapBlk) & 0xFE000000)
 
+/*
+ * Get the theoretical starting row number for a give logical heap block. All
+ * logical heap blocks can consume up to AO_MAX_TUPLES_PER_HEAP_BLOCK row
+ * numbers (either densely/sparsely). The very first block in an aoseg is an
+ * exception: it can consume up to (AO_MAX_TUPLES_PER_HEAP_BLOCK - 1) row
```
Comment (ashwinstar) [inline src/include/access/appendonlytid.h:101]: do we really need that exception to exist or its just oversight from previous coding due to +1 somewhere for initial fast sequence value?

File: src/backend/access/aocs/aocsam_handler.c [hunk 5]
```diff
@@ -1847,13 +1850,94 @@ aoco_index_build_range_scan(Relation heapRelation,
...
+		AppendOnlyBlockDirectory_Init_forSearch(&existingBlkdir,
+												snapshot,
+												(FileSegInfo **) aocoscan->seginfo,
+												aocoscan->total_seg,
+												heapRelation,
+												relnatts,
+												true,
+												proj);
+
+		for (int colIdx = 0; colIdx < aocoscan->columnScanInfo.num_proj_atts; colIdx++)
```
Comment (ashwinstar) [inline src/backend/access/aocs/aocsam_handler.c:1890]: Do we have summarization tests for CO table with BRIN on multiple columns and the columns having very different block layouts (essentially either using different data types or compression settings to differ the block layout between columns)?

**Review by ashwinstar — COMMENTED** [review]
The commit message is very ao_row centered. Would be good to update it to reflect ao_column reality as well like for ao_column, first indexed column block directory is used to make the similar determinations.

Also,
> In case it falls in a hole, we conservatively start
scanning from the blkdir entry prior to the hole (and discard unneeded
rows).

- Please can you point me to the code having this logic?
- Also, why start scanning from prior to the hole (as that's 100% wastefull) and not from entry after the hole instead? (does block directory not have API to accomplish this?)

File: src/backend/access/aocs/aocsam_handler.c (hunk 5 above)
Comment (soumyadeep2007) [reply src/backend/access/aocs/aocsam_handler.c:1890]: We don't. I'll add them!

File: src/backend/access/appendonly/appendonlyam_handler.c [hunk 6]
```diff
@@ -1613,18 +1618,84 @@ appendonly_index_build_range_scan(Relation heapRelation,
...
+
+		if (AppendOnlyBlockDirectory_GetEntryForPartialScan(&existingBlkdir,
+															start_blockno,
+															0, /* columnGroupNo */
+															&dirEntry,
+															&fsInfoIdx))
+		{
+			/*
+			 * Since we found a block directory entry at/prior to the
+			 * start_blockno, we can attempt to jump ahead.
```
[the remark this answers is not in the document]
Comment (soumyadeep2007) [reply src/backend/access/appendonly/appendonlyam_handler.c:1665]: Sure thing!

File: src/include/access/appendonlytid.h (hunk 4 above)
Comment (soumyadeep2007) [reply src/include/access/appendonlytid.h:101]: I am not sure.

This is what happens:

```
CREATE TABLE ao_partial_scan2(i int, j int) USING ao_row;
INSERT INTO ao_partial_scan2 SELECT 1, j FROM generate_series(1, 32768*5) j;
INSERT 0 163840
postgres=# SELECT distinct(right(split_part(ctid::text, ',', 1), -1)) AS blknum, count(*) FROM ao_partial_scan2 group by 1;
  blknum  | count 
----------+-------
 33554437 |     1
 33554434 | 32768
 33554435 | 32768
 33554433 | 32768
 33554432 | 32767 <----------- 1st block having 32767
 33554436 | 32768
(6 rows)

postgres=# select min(ctid) from ao_partial_scan2 ;
     min      
--------------
 (33554432,2)  <------------- offset starts at 2 instead of 1 and all subsequent offsets are off by 1.
(1 row)
```

The code responsible is:
```
/*
 * Add one to make sure bytes_4_5 is never zero. Since bytes_4_5 form
 * offset part when interpreted as TID, rest of system expects offset to
 * be greater than zero.
 */
h->bytes_4_5 = (0x7FFF & rownum) + 1;
```
This code makes all tids off by 1. I think it is trying to guard against `rownum == 0` case. But all rownums start from 1 (indeed for the 1st row inserted this function is called w/ `rownum=1`), so I don't know why this code is in place.

It was added in b469057ed8e38cba27a0ae37dc4a596a3970c4b1.

I didn't feel comfortable messing with it, since I lack context.

**Comment by soumyadeep2007** [comment]
> The commit message is very ao_row centered. Would be good to update it to reflect ao_column reality as well like for ao_column, first indexed column block directory is used to make the similar determinations.

Will do. But just to be clear, for CO it's not just the first indexed column -> we have to do a blkdir lookup for all indexed columns -> we have to position multiple datum streams appropriately.

> 
> Also,
> 
> > In case it falls in a hole, we conservatively start
> > scanning from the blkdir entry prior to the hole (and discard unneeded
> > rows).
> 
> * Please can you point me to the code having this logic?

```
AppendOnlyBlockDirectory_GetEntryForPartialScan()
...
/*
 * The previous entry is where we shall start our scan from. This is
 * where either the rangeFirstRowNum lies, or rangeFirstRowNum falls in
 * a hole that starts after the previous entry ends.
 * Either way, it is safe to start the scan from this previous entry.
 */
result_entry_no = entry_no - 1;
```
and discarding row logic is here:
```
appendonly_index_build_range_scan()
...
if (currblockno < start_blockno)
{
	/*
	 * If the scan returned some tuples lying before the start of our
	 * desired range, ignore the current tuple, and keep scanning.
	 */
	continue;
}
```

> * Also, why start scanning from prior to the hole (as that's 100% wastefull) and not from entry after the hole instead? (does block directory not have API to accomplish this?)

No API really. We had to cook up our own loop:
```
/* Find 1st entry with firstRowNum greater than rangeFirstRowNum */
while (entry_no < minipageInfo->numMinipageEntries &&
		minipage->entry[entry_no].firstRowNum <= rangeFirstRowNum)
	entry_no++;
```

Consider the situation where we have:
```
minipage0_last_entry: 10k - 11k range
<hole>
minipage1_last_entry: 13k - 14k range
```
And we try to look up 12k, then we will have to read in the next minipage to start from minipage1_last_entry. That makes things complicated in AppendOnlyBlockDirectory_GetEntryForPartialScan(). Instead, we just start from minipage0_last_entry.

But yes if the hole is between 2 entries in a minipage, then we can start from the later one. Although, this wouldn't matter too much for a default ao_row table, but we can avoid reading tuples in for highly compressed CO tables (RLE really packs stuff!). So, yeah let me add some logic so that:
* if hole is in between 2 entries, pick the later one as scan begin point.
* if hole is after the last entry, pick the last entry as scan begin point.

File: src/backend/access/appendonly/appendonlyam_handler.c (hunk 3 above)
Comment (soumyadeep2007) [reply src/backend/access/appendonly/appendonlyam_handler.c:1693]: Done:

```
* Do nothing in this case. The scan will start anyway from the
* beginning of the segfile (offset = 0), i.e. from the first row
* present in the segfile (see BufferedReadInit()).
* This will ensure that we don't skip the other possibly extant
* blocks in the range.
```

File: src/backend/access/aocs/aocsam_handler.c (hunk 5 above)
Comment (soumyadeep2007) [reply src/backend/access/aocs/aocsam_handler.c:1890]: Added. See: https://github.com/greenplum-db/gpdb/pull/15539/commits/04761bde09b742b114a04ec46b7f9b6241dbd2c2

**Comment by soumyadeep2007** [comment]
Added a couple of sq me comments to address all outstanding feedback. I will make the commit message to ack CO more when I do the final squash.

**Comment by ashwinstar** [comment]
> > The commit message is very ao_row centered. Would be good to update it to reflect ao_column reality as well like for ao_column, first indexed column block directory is used to make the similar determinations.
> 
> Will do. But just to be clear, for CO it's not just the first indexed column -> we have to do a blkdir lookup for all indexed columns -> we have to position multiple datum streams appropriately.
> 

Understand all indexed columns related block directory entries are looked up and used. But the logic to continue or ignore non-relevant tuples I am assuming are based on first indexed column only (if first indexed column locates the proper interested tuple with matching range rownumber then only rest of the columns block directory lookups will happen, right?). So, in that context first indexed column entry is playing the role which ao_row single entry plays. (rest of the indexed column block directory entries are purely to fetch the data for that column and not really driving the logic).

**Comment by ashwinstar** [comment]
Not fault of this PR - in-general curious:
- Isn't `systable_getnext_ordered()` have the possibility of returning block directory tuple with triplet (segno=1, colgroup=0, rownum=1) when asked for (segno=2, colgroup=0, rownum=1) if no block directory entry exist for segno=2?
- don't we need protections in code to validate for segno and column group of the block directory tuple before using its minipage - as I don't think indexed scan be coded to perform exact match for first two columns and only for last column rowNumber perform ordered scan

File: src/include/access/appendonlytid.h (hunk 4 above)
Comment (soumyadeep2007) [reply src/include/access/appendonlytid.h:101]: Well the code could have not done this +1 business and just had an `Assert(rownum > 0);` since we take measures to ensure that fastseq begins from 1.

Agree. Let's not change it at the moment. But maybe I should add a XXX comment with this context.

**Comment by soumyadeep2007** [comment]
> Understand all indexed columns related block directory entries are looked up and used. But the logic to continue or ignore non-relevant tuples I am assuming are based on first indexed column only (if first indexed column locates the proper interested tuple with matching range rownumber then only rest of the columns block directory lookups will happen, right?). So, in that context first indexed column entry is playing the role which ao_row single entry plays. (rest of the indexed column block directory entries are purely to fetch the data for that column and not really driving the logic).

Ah yes, understood. Will mention that. Thanks for the explanation.

**Comment by soumyadeep2007** [comment]
> Not fault of this PR - in-general curious:
> 
> * Isn't `systable_getnext_ordered()` have the possibility of returning block directory tuple with triplet (segno=1, colgroup=0, rownum=1) when asked for (segno=2, colgroup=0, rownum=1) if no block directory entry exist for segno=2?
> * don't we need protections in code to validate for segno and column group of the block directory tuple before using its minipage - as I don't think indexed scan be coded to perform exact match for first two columns and only for last column rowNumber perform ordered scan (`extract_minipage()` has assertion for segno but check maybe need if check)


The scankeys used are `(=segmentFileNum, =columnGroupNo, <=rowNum)` with backward scan direction. This means: for this `(segmentFileNum, columnGroupNo)` pair, get me all blkdir rows with first_row_num <= rowNum, starting with the highest such rowNum.

The first 2 scan keys are specified with `=` operator. So if `segno=2` doesn't exist, the scan will return empty. Here is how I verified (w/ uniq index code, which uses the same scan keys):
```
create table ao(i int unique) using ao_row;
insert into ao select 1;
-- now attach to seg1 backend and put a breakpoint on:
-- scanKeys[0].sk_argument = Int32GetDatum(segmentFileNum);
insert into ao select 1;
-- breakpoint will hit
-- set segmentFileNum = 2
-- step through the code and see that systable_getnext_ordered returns nothing as segno=2 doesn't exist.
```

**Review by ashwinstar — APPROVED** [review]
LGTM :+1:

**Comment by soumyadeep2007** [comment]
Thank you Ashwin and Haolin for the reviews! Really appreciate it!
